/*
 * API Interna de PortaFIB que ofereix serveis de firma web.
 * Conjunt de Serveis REST de PortaFIB per atendre peticions de firma a través de web de PortaFIB
 *
 * The version of the OpenAPI document: 1.0-SNAPSHOT
 * Contact: otae@fundaciobit.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package es.caib.portafib.apiinterna.client.firma.v1.api;

import es.caib.portafib.apiinterna.client.firma.v1.services.ApiException;
import es.caib.portafib.apiinterna.client.firma.v1.model.FirmaSimpleSignDocumentRequest;
import es.caib.portafib.apiinterna.client.firma.v1.model.FirmaSimpleSignatureResponse;
import es.caib.portafib.apiinterna.client.firma.v1.model.FirmaSimpleUpgradeRequest;
import es.caib.portafib.apiinterna.client.firma.v1.model.FirmaSimpleUpgradeResponse;
import es.caib.portafib.apiinterna.client.firma.v1.model.RestExceptionInfo;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for FirmaEnServidorV1Api
 */
class FirmaEnServidorV1ApiTest {

    private final FirmaEnServidorV1Api api = new FirmaEnServidorV1Api();

    /**
     * Operacio de firma simple en servidor d&#39;un document
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    void signdocumentTest() throws ApiException {
        //
        //FirmaSimpleSignDocumentRequest firmaSimpleSignDocumentRequest = null;
        //
        //FirmaSimpleSignatureResponse response = api.signdocument(firmaSimpleSignDocumentRequest);

        // TODO: test validations
    }
    /**
     * Operacio de firma simple en servidor d&#39;un document
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    void upgradeSignatureTest() throws ApiException {
        //
        //FirmaSimpleUpgradeRequest firmaSimpleUpgradeRequest = null;
        //
        //FirmaSimpleUpgradeResponse response = api.upgradeSignature(firmaSimpleUpgradeRequest);

        // TODO: test validations
    }
    /**
     * Retorna la versió d&#39;aquest Servei
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    void versioTest() throws ApiException {
        //
        //String response = api.versio();

        // TODO: test validations
    }
}
