/*
 * API Interna de PortaFIB de consulta de serveis d'utilitat
 * Conjunt de Serveis REST de PortaFIB per atendre consultes generiques de Portafib
 *
 * The version of the OpenAPI document: 1.0-SNAPSHOT
 * Contact: otae@fundaciobit.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package es.caib.portafib.apiinterna.client.firma.v1.api;

import es.caib.portafib.apiinterna.client.firma.v1.services.ApiException;
import es.caib.portafib.apiinterna.client.firma.v1.model.AvailableLanguagesRest;
import es.caib.portafib.apiinterna.client.firma.v1.model.AvailableProfilesRest;
import es.caib.portafib.apiinterna.client.firma.v1.model.LlistaTipusDocumentalRest;
import es.caib.portafib.apiinterna.client.firma.v1.model.RestExceptionInfo;
import org.junit.Test;
import org.junit.Ignore;
import org.junit.Assert;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for UtilsV1Api
 */
public class UtilsV1ApiTest {

    private final UtilsV1Api api = new UtilsV1Api();

    /**
     * Retorna els idiomes disponibles.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAvailableLanguagesTest() throws ApiException {
        //
        //String language = null;
        //
        //AvailableLanguagesRest response = api.getAvailableLanguages(language);

        // TODO: test validations
    }
    /**
     * Retorna els perfils de firma.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAvailableProfilesTest() throws ApiException {
        //
        //String language = null;
        //
        //AvailableProfilesRest response = api.getAvailableProfiles(language);

        // TODO: test validations
    }
    /**
     * Retorna la llista de tipus documentals disponibles.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void tipusdocumentalslistTest() throws ApiException {
        //
        //String language = null;
        //
        //String appuser = null;
        //
        //LlistaTipusDocumentalRest response = api.tipusdocumentalslist(language, appuser);

        // TODO: test validations
    }
}
