package org.fundaciobit.plugins.signatureserver.afirmaserver.validarfirmaapi;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by Apache CXF 2.2.12-patch-04
 * Tue Mar 14 13:59:26 CET 2017
 * Generated source version: 2.2.12-patch-04
 * 
 */
 
@WebService(targetNamespace = "urn:oasis:names:tc:dss:1.0:core:schema", name = "DSSSignature")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface DSSSignature {

    @WebResult(name = "verifyReturn", targetNamespace = "urn:oasis:names:tc:dss:1.0:core:schema", partName = "verifyReturn")
    @WebMethod
    public java.lang.String verify(
        @WebParam(partName = "dssXML", name = "dssXML")
        java.lang.String dssXML
    );
}
