/*
 * API Interna de PortaFIB de consulta de informació de versions de PortaFIB
 * Conjunt de Serveis REST de PortaFIB per atendre consultes informació de versions.
 *
 * The version of the OpenAPI document: 1.0-SNAPSHOT
 * Contact: otae@fundaciobit.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package es.caib.portafib.apiinterna.client.infoversio.v1.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for InfoVersio
 */
class InfoVersioTest {
    private final InfoVersio model = new InfoVersio();

    /**
     * Model tests for InfoVersio
     */
    @Test
    void testInfoVersio() {
        // TODO: test InfoVersio
    }

    /**
     * Test the property 'caib'
     */
    @Test
    void caibTest() {
        // TODO: test caib
    }

    /**
     * Test the property 'version'
     */
    @Test
    void versionTest() {
        // TODO: test version
    }

    /**
     * Test the property 'buildTime'
     */
    @Test
    void buildTimeTest() {
        // TODO: test buildTime
    }

    /**
     * Test the property 'jdkVersion'
     */
    @Test
    void jdkVersionTest() {
        // TODO: test jdkVersion
    }

}
