package es.caib.portafib.ws.api.v1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.2.12-patch-04
 * Mon Sep 08 11:00:18 CEST 2014
 * Generated source version: 2.2.12-patch-04
 * 
 */
 
@WebService(targetNamespace = "http://impl.v1.ws.portafib.caib.es/", name = "PortaFIBPeticioDeFirmaWs")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface PortaFIBPeticioDeFirmaWs {

    @WebResult(name = "return", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", partName = "return")
    @WebMethod
    public java.lang.String getEntitatID();

    @WebMethod
    public void startPeticioDeFirma(
        @WebParam(partName = "peticioDeFirmaID", name = "peticioDeFirmaID")
        long peticioDeFirmaID
    ) throws WsI18NException;

    @WebResult(name = "return", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", partName = "return")
    @WebMethod
    public long createPlantillaFluxDeFirmes(
        @WebParam(partName = "fluxDeFirmesWs", name = "fluxDeFirmesWs")
        FluxDeFirmesWs fluxDeFirmesWs,
        @WebParam(partName = "compartir", name = "compartir")
        boolean compartir
    ) throws WsI18NException, WsValidationException;

    @WebResult(name = "return", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", partName = "return")
    @WebMethod
    public int getVersionWs();

    @WebResult(name = "return", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", partName = "return")
    @WebMethod
    public PeticioDeFirmaWs createAndStartPeticioDeFirma(
        @WebParam(partName = "peticioDeFirmaWs", name = "peticioDeFirmaWs")
        PeticioDeFirmaWs peticioDeFirmaWs
    ) throws WsI18NException, WsValidationException;

    @WebResult(name = "return", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", partName = "return")
    @WebMethod
    public PeticioDeFirmaWs createPeticioDeFirma(
        @WebParam(partName = "peticioDeFirmaWs", name = "peticioDeFirmaWs")
        PeticioDeFirmaWs peticioDeFirmaWs
    ) throws WsI18NException, WsValidationException;

    @WebResult(name = "return", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", partName = "return")
    @WebMethod
    public PeticioDeFirmaWs getPeticioDeFirma(
        @WebParam(partName = "peticioDeFirmaID", name = "peticioDeFirmaID")
        long peticioDeFirmaID
    ) throws WsI18NException;

    @WebMethod
    public void deletePeticioDeFirma(
        @WebParam(partName = "peticioDeFirmaID", name = "peticioDeFirmaID")
        long peticioDeFirmaID
    ) throws WsI18NException;

    @WebResult(name = "return", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", partName = "return")
    @WebMethod
    public FitxerBean getLastSignedFileOfPeticioDeFirma(
        @WebParam(partName = "peticioDeFirmaID", name = "peticioDeFirmaID")
        long peticioDeFirmaID
    ) throws WsI18NException;

    @WebResult(name = "return", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", partName = "return")
    @WebMethod
    public int getStateOfPeticioDeFirma(
        @WebParam(partName = "peticioDeFirmaID", name = "peticioDeFirmaID")
        long peticioDeFirmaID
    ) throws WsI18NException;

    @WebResult(name = "return", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", partName = "return")
    @WebMethod
    public CustodiaInfoBean getDefaultCustodiaInfo(
        @WebParam(partName = "title", name = "title")
        java.lang.String title,
        @WebParam(partName = "language", name = "language")
        java.lang.String language
    ) throws WsI18NException;

    @WebMethod
    public void pausePeticioDeFirma(
        @WebParam(partName = "peticioDeFirmaID", name = "peticioDeFirmaID")
        long peticioDeFirmaID
    ) throws WsI18NException;

    @WebResult(name = "return", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", partName = "return")
    @WebMethod
    public java.lang.String getVersion();

    @WebResult(name = "return", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", partName = "return")
    @WebMethod
    public PeticioDeFirmaWs resetPeticioDeFirma(
        @WebParam(partName = "peticioDeFirmaID", name = "peticioDeFirmaID")
        long peticioDeFirmaID
    ) throws WsI18NException;

    @WebResult(name = "return", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", partName = "return")
    @WebMethod
    public FluxDeFirmesWs instantiatePlantillaFluxDeFirmes(
        @WebParam(partName = "plantillaDeFluxDeFirmesID", name = "plantillaDeFluxDeFirmesID")
        long plantillaDeFluxDeFirmesID
    ) throws WsI18NException;

    @WebResult(name = "return", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", partName = "return")
    @WebMethod
    public StringArray getSupportedLanguages() throws WsI18NException;

    @WebResult(name = "return", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", partName = "return")
    @WebMethod
    public java.lang.String getCurrentCustodiaPluginClass() throws WsI18NException;

    @WebResult(name = "return", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", partName = "return")
    @WebMethod
    public TipusDocumentInfoWsArray getTipusDeDocuments(
        @WebParam(partName = "idioma", name = "idioma")
        java.lang.String idioma
    ) throws WsI18NException;

    @WebResult(name = "return", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", partName = "return")
    @WebMethod
    public FitxerBean downloadFileUsingEncryptedFileID(
        @WebParam(partName = "arg0", name = "arg0")
        java.lang.String arg0
    ) throws WsI18NException;
}
