package es.caib.portafib.ws.api.v1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.6
 * 2023-02-15T14:03:33.014+01:00
 * Generated source version: 3.2.6
 *
 */
@WebService(targetNamespace = "http://impl.v1.ws.portafib.caib.es/", name = "PortaFIBPeticioDeFirmaWs")
@XmlSeeAlso({ObjectFactory.class})
public interface PortaFIBPeticioDeFirmaWs {

    @WebMethod
    @RequestWrapper(localName = "getDefaultCustodiaInfo", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.GetDefaultCustodiaInfo")
    @ResponseWrapper(localName = "getDefaultCustodiaInfoResponse", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.GetDefaultCustodiaInfoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public es.caib.portafib.ws.api.v1.CustodiaInfoBean getDefaultCustodiaInfo(
        @WebParam(name = "title", targetNamespace = "")
        java.lang.String title,
        @WebParam(name = "language", targetNamespace = "")
        java.lang.String language
    ) throws WsI18NException;

    @WebMethod
    @RequestWrapper(localName = "createPlantillaFluxDeFirmes", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.CreatePlantillaFluxDeFirmes")
    @ResponseWrapper(localName = "createPlantillaFluxDeFirmesResponse", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.CreatePlantillaFluxDeFirmesResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.Long createPlantillaFluxDeFirmes(
        @WebParam(name = "fluxDeFirmesWs", targetNamespace = "")
        es.caib.portafib.ws.api.v1.FluxDeFirmesWs fluxDeFirmesWs,
        @WebParam(name = "compartir", targetNamespace = "")
        boolean compartir
    ) throws WsI18NException, WsValidationException;

    @WebMethod
    @RequestWrapper(localName = "createPeticioDeFirma", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.CreatePeticioDeFirma")
    @ResponseWrapper(localName = "createPeticioDeFirmaResponse", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.CreatePeticioDeFirmaResponse")
    @WebResult(name = "return", targetNamespace = "")
    public es.caib.portafib.ws.api.v1.PeticioDeFirmaWs createPeticioDeFirma(
        @WebParam(name = "peticioDeFirmaWs", targetNamespace = "")
        es.caib.portafib.ws.api.v1.PeticioDeFirmaWs peticioDeFirmaWs
    ) throws WsI18NException, WsValidationException;

    @WebMethod
    @RequestWrapper(localName = "getVersion", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.GetVersion")
    @ResponseWrapper(localName = "getVersionResponse", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.GetVersionResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String getVersion();

    @WebMethod
    @RequestWrapper(localName = "instantiatePlantillaFluxDeFirmes", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.InstantiatePlantillaFluxDeFirmes")
    @ResponseWrapper(localName = "instantiatePlantillaFluxDeFirmesResponse", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.InstantiatePlantillaFluxDeFirmesResponse")
    @WebResult(name = "return", targetNamespace = "")
    public es.caib.portafib.ws.api.v1.FluxDeFirmesWs instantiatePlantillaFluxDeFirmes(
        @WebParam(name = "plantillaDeFluxDeFirmesID", targetNamespace = "")
        long plantillaDeFluxDeFirmesID
    ) throws WsI18NException;

    @WebMethod
    @RequestWrapper(localName = "pausePeticioDeFirma", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.PausePeticioDeFirma")
    @ResponseWrapper(localName = "pausePeticioDeFirmaResponse", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.PausePeticioDeFirmaResponse")
    public void pausePeticioDeFirma(
        @WebParam(name = "peticioDeFirmaID", targetNamespace = "")
        long peticioDeFirmaID
    ) throws WsI18NException;

    @WebMethod
    @RequestWrapper(localName = "getTipusDeDocuments", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.GetTipusDeDocuments")
    @ResponseWrapper(localName = "getTipusDeDocumentsResponse", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.GetTipusDeDocumentsResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<es.caib.portafib.ws.api.v1.TipusDocumentInfoWs> getTipusDeDocuments(
        @WebParam(name = "idioma", targetNamespace = "")
        java.lang.String idioma
    ) throws WsI18NException;

    @WebMethod
    @RequestWrapper(localName = "resetPeticioDeFirma", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.ResetPeticioDeFirma")
    @ResponseWrapper(localName = "resetPeticioDeFirmaResponse", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.ResetPeticioDeFirmaResponse")
    @WebResult(name = "return", targetNamespace = "")
    public es.caib.portafib.ws.api.v1.PeticioDeFirmaWs resetPeticioDeFirma(
        @WebParam(name = "peticioDeFirmaID", targetNamespace = "")
        long peticioDeFirmaID
    ) throws WsI18NException;

    @WebMethod
    @RequestWrapper(localName = "createAndStartPeticioDeFirma", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.CreateAndStartPeticioDeFirma")
    @ResponseWrapper(localName = "createAndStartPeticioDeFirmaResponse", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.CreateAndStartPeticioDeFirmaResponse")
    @WebResult(name = "return", targetNamespace = "")
    public es.caib.portafib.ws.api.v1.PeticioDeFirmaWs createAndStartPeticioDeFirma(
        @WebParam(name = "peticioDeFirmaWs", targetNamespace = "")
        es.caib.portafib.ws.api.v1.PeticioDeFirmaWs peticioDeFirmaWs
    ) throws WsI18NException, WsValidationException;

    @WebMethod
    @RequestWrapper(localName = "getPeticioDeFirma", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.GetPeticioDeFirma")
    @ResponseWrapper(localName = "getPeticioDeFirmaResponse", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.GetPeticioDeFirmaResponse")
    @WebResult(name = "return", targetNamespace = "")
    public es.caib.portafib.ws.api.v1.PeticioDeFirmaWs getPeticioDeFirma(
        @WebParam(name = "peticioDeFirmaID", targetNamespace = "")
        long peticioDeFirmaID
    ) throws WsI18NException;

    @WebMethod
    @RequestWrapper(localName = "getStateOfPeticioDeFirma", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.GetStateOfPeticioDeFirma")
    @ResponseWrapper(localName = "getStateOfPeticioDeFirmaResponse", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.GetStateOfPeticioDeFirmaResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.Integer getStateOfPeticioDeFirma(
        @WebParam(name = "peticioDeFirmaID", targetNamespace = "")
        long peticioDeFirmaID
    ) throws WsI18NException;

    @WebMethod
    @RequestWrapper(localName = "downloadFileUsingEncryptedFileID", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.DownloadFileUsingEncryptedFileID")
    @ResponseWrapper(localName = "downloadFileUsingEncryptedFileIDResponse", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.DownloadFileUsingEncryptedFileIDResponse")
    @WebResult(name = "return", targetNamespace = "")
    public es.caib.portafib.ws.api.v1.FitxerBean downloadFileUsingEncryptedFileID(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    ) throws WsI18NException;

    @WebMethod
    @RequestWrapper(localName = "deletePlantillaFluxDeFirmes", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.DeletePlantillaFluxDeFirmes")
    @ResponseWrapper(localName = "deletePlantillaFluxDeFirmesResponse", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.DeletePlantillaFluxDeFirmesResponse")
    public void deletePlantillaFluxDeFirmes(
        @WebParam(name = "plantillaDeFluxDeFirmesID", targetNamespace = "")
        long plantillaDeFluxDeFirmesID
    ) throws WsI18NException;

    @WebMethod
    @RequestWrapper(localName = "deletePeticioDeFirma", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.DeletePeticioDeFirma")
    @ResponseWrapper(localName = "deletePeticioDeFirmaResponse", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.DeletePeticioDeFirmaResponse")
    public void deletePeticioDeFirma(
        @WebParam(name = "peticioDeFirmaID", targetNamespace = "")
        long peticioDeFirmaID
    ) throws WsI18NException;

    @WebMethod
    @RequestWrapper(localName = "getEntitatID", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.GetEntitatID")
    @ResponseWrapper(localName = "getEntitatIDResponse", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.GetEntitatIDResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String getEntitatID();

    @WebMethod
    @RequestWrapper(localName = "getVersionWs", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.GetVersionWs")
    @ResponseWrapper(localName = "getVersionWsResponse", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.GetVersionWsResponse")
    @WebResult(name = "return", targetNamespace = "")
    public int getVersionWs();

    @WebMethod
    @RequestWrapper(localName = "startPeticioDeFirma", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.StartPeticioDeFirma")
    @ResponseWrapper(localName = "startPeticioDeFirmaResponse", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.StartPeticioDeFirmaResponse")
    public void startPeticioDeFirma(
        @WebParam(name = "peticioDeFirmaID", targetNamespace = "")
        long peticioDeFirmaID
    ) throws WsI18NException;

    @WebMethod
    @RequestWrapper(localName = "getLastSignedFileOfPeticioDeFirma", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.GetLastSignedFileOfPeticioDeFirma")
    @ResponseWrapper(localName = "getLastSignedFileOfPeticioDeFirmaResponse", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.GetLastSignedFileOfPeticioDeFirmaResponse")
    @WebResult(name = "return", targetNamespace = "")
    public es.caib.portafib.ws.api.v1.FitxerBean getLastSignedFileOfPeticioDeFirma(
        @WebParam(name = "peticioDeFirmaID", targetNamespace = "")
        long peticioDeFirmaID
    ) throws WsI18NException;

    @WebMethod
    @RequestWrapper(localName = "getSupportedLanguages", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.GetSupportedLanguages")
    @ResponseWrapper(localName = "getSupportedLanguagesResponse", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.GetSupportedLanguagesResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<java.lang.String> getSupportedLanguages() throws WsI18NException;
}
