
/*
 * 
 */

package es.caib.portafib.ws.api.v1;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.2.12-patch-04
 * Mon Sep 08 11:00:18 CEST 2014
 * Generated source version: 2.2.12-patch-04
 * 
 */


@WebServiceClient(name = "PortaFIBPeticioDeFirmaWsService", 
                  wsdlLocation = "http://localhost:8080/portafib/ws/v1/PortaFIBPeticioDeFirma?wsdl",
                  targetNamespace = "http://impl.v1.ws.portafib.caib.es/") 
public class PortaFIBPeticioDeFirmaWsService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://impl.v1.ws.portafib.caib.es/", "PortaFIBPeticioDeFirmaWsService");
    public final static QName PortaFIBPeticioDeFirmaWs = new QName("http://impl.v1.ws.portafib.caib.es/", "PortaFIBPeticioDeFirmaWs");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/portafib/ws/v1/PortaFIBPeticioDeFirma?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://localhost:8080/portafib/ws/v1/PortaFIBPeticioDeFirma?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public PortaFIBPeticioDeFirmaWsService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PortaFIBPeticioDeFirmaWsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PortaFIBPeticioDeFirmaWsService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     * 
     * @return
     *     returns PortaFIBPeticioDeFirmaWs
     */
    @WebEndpoint(name = "PortaFIBPeticioDeFirmaWs")
    public PortaFIBPeticioDeFirmaWs getPortaFIBPeticioDeFirmaWs() {
        return super.getPort(PortaFIBPeticioDeFirmaWs, PortaFIBPeticioDeFirmaWs.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PortaFIBPeticioDeFirmaWs
     */
    @WebEndpoint(name = "PortaFIBPeticioDeFirmaWs")
    public PortaFIBPeticioDeFirmaWs getPortaFIBPeticioDeFirmaWs(WebServiceFeature... features) {
        return super.getPort(PortaFIBPeticioDeFirmaWs, PortaFIBPeticioDeFirmaWs.class, features);
    }

}
