package es.caib.portafib.ws.api.v1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.6
 * 2023-02-15T14:03:23.915+01:00
 * Generated source version: 3.2.6
 *
 */
@WebService(targetNamespace = "http://impl.v1.ws.portafib.caib.es/", name = "PortaFIBUsuariAplicacioWs")
@XmlSeeAlso({ObjectFactory.class})
public interface PortaFIBUsuariAplicacioWs {

    @WebMethod
    @RequestWrapper(localName = "getUsuariAplicacio", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.GetUsuariAplicacio")
    @ResponseWrapper(localName = "getUsuariAplicacioResponse", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.GetUsuariAplicacioResponse")
    @WebResult(name = "return", targetNamespace = "")
    public es.caib.portafib.ws.api.v1.UsuariAplicacioBean getUsuariAplicacio(
        @WebParam(name = "usuariAplicacioID", targetNamespace = "")
        java.lang.String usuariAplicacioID
    ) throws WsI18NException;

    @WebMethod
    @RequestWrapper(localName = "addRolUserToUsuariAplicacio", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.AddRolUserToUsuariAplicacio")
    @ResponseWrapper(localName = "addRolUserToUsuariAplicacioResponse", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.AddRolUserToUsuariAplicacioResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean addRolUserToUsuariAplicacio(
        @WebParam(name = "usuariAplicacioID", targetNamespace = "")
        java.lang.String usuariAplicacioID
    ) throws WsI18NException;

    @WebMethod
    @RequestWrapper(localName = "getVersion", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.GetVersion")
    @ResponseWrapper(localName = "getVersionResponse", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.GetVersionResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String getVersion();

    @WebMethod
    @RequestWrapper(localName = "removeRolAdminToUsuariAplicacio", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.RemoveRolAdminToUsuariAplicacio")
    @ResponseWrapper(localName = "removeRolAdminToUsuariAplicacioResponse", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.RemoveRolAdminToUsuariAplicacioResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean removeRolAdminToUsuariAplicacio(
        @WebParam(name = "usuariAplicacioID", targetNamespace = "")
        java.lang.String usuariAplicacioID
    ) throws WsI18NException;

    @WebMethod
    @RequestWrapper(localName = "removeRolUserToUsuariAplicacio", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.RemoveRolUserToUsuariAplicacio")
    @ResponseWrapper(localName = "removeRolUserToUsuariAplicacioResponse", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.RemoveRolUserToUsuariAplicacioResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean removeRolUserToUsuariAplicacio(
        @WebParam(name = "usuariAplicacioID", targetNamespace = "")
        java.lang.String usuariAplicacioID
    ) throws WsI18NException;

    @WebMethod
    @RequestWrapper(localName = "downloadFileUsingEncryptedFileID", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.DownloadFileUsingEncryptedFileID")
    @ResponseWrapper(localName = "downloadFileUsingEncryptedFileIDResponse", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.DownloadFileUsingEncryptedFileIDResponse")
    @WebResult(name = "return", targetNamespace = "")
    public es.caib.portafib.ws.api.v1.FitxerBean downloadFileUsingEncryptedFileID(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    ) throws WsI18NException;

    @WebMethod
    @RequestWrapper(localName = "createUsuariAplicacio", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.CreateUsuariAplicacio")
    @ResponseWrapper(localName = "createUsuariAplicacioResponse", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.CreateUsuariAplicacioResponse")
    public void createUsuariAplicacio(
        @WebParam(name = "usuariAplicacioBean", targetNamespace = "")
        es.caib.portafib.ws.api.v1.UsuariAplicacioBean usuariAplicacioBean
    ) throws WsI18NException, WsValidationException;

    @WebMethod
    @RequestWrapper(localName = "getEntitatID", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.GetEntitatID")
    @ResponseWrapper(localName = "getEntitatIDResponse", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.GetEntitatIDResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String getEntitatID();

    @WebMethod
    @RequestWrapper(localName = "getVersionWs", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.GetVersionWs")
    @ResponseWrapper(localName = "getVersionWsResponse", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.GetVersionWsResponse")
    @WebResult(name = "return", targetNamespace = "")
    public int getVersionWs();

    @WebMethod
    @RequestWrapper(localName = "listUsuariAplicacio", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.ListUsuariAplicacio")
    @ResponseWrapper(localName = "listUsuariAplicacioResponse", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.ListUsuariAplicacioResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<es.caib.portafib.ws.api.v1.UsuariAplicacioBean> listUsuariAplicacio(
        @WebParam(name = "usuariAplicacioFilterWs", targetNamespace = "")
        es.caib.portafib.ws.api.v1.UsuariAplicacioFilterWs usuariAplicacioFilterWs
    ) throws WsI18NException;

    @WebMethod
    @RequestWrapper(localName = "deleteUsuariAplicacio", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.DeleteUsuariAplicacio")
    @ResponseWrapper(localName = "deleteUsuariAplicacioResponse", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.DeleteUsuariAplicacioResponse")
    public void deleteUsuariAplicacio(
        @WebParam(name = "usuariAplicacioID", targetNamespace = "")
        java.lang.String usuariAplicacioID
    ) throws WsI18NException;

    @WebMethod
    @RequestWrapper(localName = "addRolAdminToUsuariAplicacio", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.AddRolAdminToUsuariAplicacio")
    @ResponseWrapper(localName = "addRolAdminToUsuariAplicacioResponse", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.AddRolAdminToUsuariAplicacioResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean addRolAdminToUsuariAplicacio(
        @WebParam(name = "usuariAplicacioID", targetNamespace = "")
        java.lang.String usuariAplicacioID
    ) throws WsI18NException;

    @WebMethod
    @RequestWrapper(localName = "getSupportedLanguages", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.GetSupportedLanguages")
    @ResponseWrapper(localName = "getSupportedLanguagesResponse", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.GetSupportedLanguagesResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<java.lang.String> getSupportedLanguages() throws WsI18NException;
}
