package es.caib.portafib.ws.api.v1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.6
 * 2023-04-17T12:25:31.746+02:00
 * Generated source version: 3.2.6
 *
 */
@WebService(targetNamespace = "http://impl.v1.ws.portafib.caib.es/", name = "PortaFIBUsuariEntitatWs")
@XmlSeeAlso({ObjectFactory.class})
public interface PortaFIBUsuariEntitatWs {

    @WebMethod
    @RequestWrapper(localName = "createCarrec", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.CreateCarrec")
    @ResponseWrapper(localName = "createCarrecResponse", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.CreateCarrecResponse")
    public void createCarrec(
        @WebParam(name = "carrec", targetNamespace = "")
        es.caib.portafib.ws.api.v1.CarrecWs carrec
    ) throws WsI18NException, WsValidationException;

    @WebMethod
    @RequestWrapper(localName = "removeRoleAdministradorDeEntitat", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.RemoveRoleAdministradorDeEntitat")
    @ResponseWrapper(localName = "removeRoleAdministradorDeEntitatResponse", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.RemoveRoleAdministradorDeEntitatResponse")
    public void removeRoleAdministradorDeEntitat(
        @WebParam(name = "usuariEntitatID", targetNamespace = "")
        java.lang.String usuariEntitatID
    ) throws WsI18NException;

    @WebMethod
    @RequestWrapper(localName = "createUsuariEntitat", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.CreateUsuariEntitat")
    @ResponseWrapper(localName = "createUsuariEntitatResponse", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.CreateUsuariEntitatResponse")
    @WebResult(name = "return", targetNamespace = "")
    public es.caib.portafib.ws.api.v1.UsuariEntitatBean createUsuariEntitat(
        @WebParam(name = "usuariEntitatBean", targetNamespace = "")
        es.caib.portafib.ws.api.v1.UsuariEntitatBean usuariEntitatBean
    ) throws WsI18NException, WsValidationException;

    @WebMethod
    @RequestWrapper(localName = "createCarrecSimple", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.CreateCarrecSimple")
    @ResponseWrapper(localName = "createCarrecSimpleResponse", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.CreateCarrecSimpleResponse")
    @WebResult(name = "return", targetNamespace = "")
    public es.caib.portafib.ws.api.v1.CarrecWs createCarrecSimple(
        @WebParam(name = "administrationID", targetNamespace = "")
        java.lang.String administrationID,
        @WebParam(name = "entitatID", targetNamespace = "")
        java.lang.String entitatID,
        @WebParam(name = "carrecUsername", targetNamespace = "")
        java.lang.String carrecUsername,
        @WebParam(name = "carrecName", targetNamespace = "")
        java.lang.String carrecName
    ) throws WsI18NException, WsValidationException;

    @WebMethod
    @RequestWrapper(localName = "deleteUsuariEntitat", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.DeleteUsuariEntitat")
    @ResponseWrapper(localName = "deleteUsuariEntitatResponse", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.DeleteUsuariEntitatResponse")
    public void deleteUsuariEntitat(
        @WebParam(name = "usuariEntitatID", targetNamespace = "")
        java.lang.String usuariEntitatID
    ) throws WsI18NException;

    @WebMethod
    @RequestWrapper(localName = "getUsuariEntitatIDByUsuariPersonaID", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.GetUsuariEntitatIDByUsuariPersonaID")
    @ResponseWrapper(localName = "getUsuariEntitatIDByUsuariPersonaIDResponse", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.GetUsuariEntitatIDByUsuariPersonaIDResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String getUsuariEntitatIDByUsuariPersonaID(
        @WebParam(name = "usuariPersonaID", targetNamespace = "")
        java.lang.String usuariPersonaID,
        @WebParam(name = "entitatID", targetNamespace = "")
        java.lang.String entitatID
    ) throws WsI18NException;

    @WebMethod
    @RequestWrapper(localName = "getCarrec", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.GetCarrec")
    @ResponseWrapper(localName = "getCarrecResponse", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.GetCarrecResponse")
    @WebResult(name = "return", targetNamespace = "")
    public es.caib.portafib.ws.api.v1.CarrecWs getCarrec(
        @WebParam(name = "carrecID", targetNamespace = "")
        java.lang.String carrecID
    );

    @WebMethod
    @RequestWrapper(localName = "getVersion", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.GetVersion")
    @ResponseWrapper(localName = "getVersionResponse", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.GetVersionResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String getVersion();

    @WebMethod
    @RequestWrapper(localName = "addRoleSolicitant", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.AddRoleSolicitant")
    @ResponseWrapper(localName = "addRoleSolicitantResponse", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.AddRoleSolicitantResponse")
    public void addRoleSolicitant(
        @WebParam(name = "usuariEntitatID", targetNamespace = "")
        java.lang.String usuariEntitatID
    ) throws WsI18NException;

    @WebMethod
    @RequestWrapper(localName = "deleteUsuariPersona", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.DeleteUsuariPersona")
    @ResponseWrapper(localName = "deleteUsuariPersonaResponse", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.DeleteUsuariPersonaResponse")
    public void deleteUsuariPersona(
        @WebParam(name = "usuariPersonaID", targetNamespace = "")
        java.lang.String usuariPersonaID
    ) throws WsI18NException;

    @WebMethod
    @RequestWrapper(localName = "getUsuariEntitat", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.GetUsuariEntitat")
    @ResponseWrapper(localName = "getUsuariEntitatResponse", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.GetUsuariEntitatResponse")
    @WebResult(name = "return", targetNamespace = "")
    public es.caib.portafib.ws.api.v1.UsuariEntitatBean getUsuariEntitat(
        @WebParam(name = "usuariEntitatID", targetNamespace = "")
        java.lang.String usuariEntitatID
    );

    @WebMethod
    @RequestWrapper(localName = "createUsuariPersona", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.CreateUsuariPersona")
    @ResponseWrapper(localName = "createUsuariPersonaResponse", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.CreateUsuariPersonaResponse")
    public void createUsuariPersona(
        @WebParam(name = "usuariPersonaBean", targetNamespace = "")
        es.caib.portafib.ws.api.v1.UsuariPersonaBean usuariPersonaBean
    ) throws WsI18NException, WsValidationException;

    @WebMethod
    @RequestWrapper(localName = "getCarrecsByEntitatID", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.GetCarrecsByEntitatID")
    @ResponseWrapper(localName = "getCarrecsByEntitatIDResponse", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.GetCarrecsByEntitatIDResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<es.caib.portafib.ws.api.v1.CarrecWs> getCarrecsByEntitatID(
        @WebParam(name = "entitatID", targetNamespace = "")
        java.lang.String entitatID
    ) throws WsI18NException;

    @WebMethod
    @RequestWrapper(localName = "downloadFileUsingEncryptedFileID", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.DownloadFileUsingEncryptedFileID")
    @ResponseWrapper(localName = "downloadFileUsingEncryptedFileIDResponse", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.DownloadFileUsingEncryptedFileIDResponse")
    @WebResult(name = "return", targetNamespace = "")
    public es.caib.portafib.ws.api.v1.FitxerBean downloadFileUsingEncryptedFileID(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    ) throws WsI18NException;

    @WebMethod
    @RequestWrapper(localName = "getInfoFromPluginUserInfoByAdministrationID", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.GetInfoFromPluginUserInfoByAdministrationID")
    @ResponseWrapper(localName = "getInfoFromPluginUserInfoByAdministrationIDResponse", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.GetInfoFromPluginUserInfoByAdministrationIDResponse")
    @WebResult(name = "return", targetNamespace = "")
    public es.caib.portafib.ws.api.v1.UsuariPersonaBean getInfoFromPluginUserInfoByAdministrationID(
        @WebParam(name = "administrationID", targetNamespace = "")
        java.lang.String administrationID
    ) throws WsI18NException;

    @WebMethod
    @RequestWrapper(localName = "getUsuariEntitatIDInMyEntitatByUsuariPersonaID", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.GetUsuariEntitatIDInMyEntitatByUsuariPersonaID")
    @ResponseWrapper(localName = "getUsuariEntitatIDInMyEntitatByUsuariPersonaIDResponse", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.GetUsuariEntitatIDInMyEntitatByUsuariPersonaIDResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String getUsuariEntitatIDInMyEntitatByUsuariPersonaID(
        @WebParam(name = "usuariPersonaID", targetNamespace = "")
        java.lang.String usuariPersonaID
    ) throws WsI18NException;

    @WebMethod
    @RequestWrapper(localName = "getSupportedLanguages", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.GetSupportedLanguages")
    @ResponseWrapper(localName = "getSupportedLanguagesResponse", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.GetSupportedLanguagesResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<java.lang.String> getSupportedLanguages() throws WsI18NException;

    @WebMethod
    @RequestWrapper(localName = "getUsuariPersonaIDByAdministrationID", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.GetUsuariPersonaIDByAdministrationID")
    @ResponseWrapper(localName = "getUsuariPersonaIDByAdministrationIDResponse", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.GetUsuariPersonaIDByAdministrationIDResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String getUsuariPersonaIDByAdministrationID(
        @WebParam(name = "administrationID", targetNamespace = "")
        java.lang.String administrationID
    ) throws WsI18NException, WsValidationException;

    @WebMethod
    @RequestWrapper(localName = "updateAdministrationIDOfCarrec", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.UpdateAdministrationIDOfCarrec")
    @ResponseWrapper(localName = "updateAdministrationIDOfCarrecResponse", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.UpdateAdministrationIDOfCarrecResponse")
    public void updateAdministrationIDOfCarrec(
        @WebParam(name = "carrecID", targetNamespace = "")
        java.lang.String carrecID,
        @WebParam(name = "administrationID", targetNamespace = "")
        java.lang.String administrationID
    ) throws WsI18NException, WsValidationException;

    @WebMethod
    @RequestWrapper(localName = "getUsuariEntitatIDInMyEntitatByAdministrationID", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.GetUsuariEntitatIDInMyEntitatByAdministrationID")
    @ResponseWrapper(localName = "getUsuariEntitatIDInMyEntitatByAdministrationIDResponse", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.GetUsuariEntitatIDInMyEntitatByAdministrationIDResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String getUsuariEntitatIDInMyEntitatByAdministrationID(
        @WebParam(name = "administrationID", targetNamespace = "")
        java.lang.String administrationID
    ) throws WsI18NException;

    @WebMethod
    @RequestWrapper(localName = "createUsuariEntitatSimple", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.CreateUsuariEntitatSimple")
    @ResponseWrapper(localName = "createUsuariEntitatSimpleResponse", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.CreateUsuariEntitatSimpleResponse")
    @WebResult(name = "return", targetNamespace = "")
    public es.caib.portafib.ws.api.v1.UsuariEntitatBean createUsuariEntitatSimple(
        @WebParam(name = "administrationID", targetNamespace = "")
        java.lang.String administrationID,
        @WebParam(name = "entitatID", targetNamespace = "")
        java.lang.String entitatID
    ) throws WsI18NException, WsValidationException;

    @WebMethod
    @RequestWrapper(localName = "updateUsuariPersona", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.UpdateUsuariPersona")
    @ResponseWrapper(localName = "updateUsuariPersonaResponse", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.UpdateUsuariPersonaResponse")
    public void updateUsuariPersona(
        @WebParam(name = "usuariPersonaBean", targetNamespace = "")
        es.caib.portafib.ws.api.v1.UsuariPersonaBean usuariPersonaBean
    ) throws WsI18NException;

    @WebMethod
    @RequestWrapper(localName = "deactivateCarrec", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.DeactivateCarrec")
    @ResponseWrapper(localName = "deactivateCarrecResponse", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.DeactivateCarrecResponse")
    public void deactivateCarrec(
        @WebParam(name = "carrecID", targetNamespace = "")
        java.lang.String carrecID
    ) throws WsI18NException;

    @WebMethod
    @RequestWrapper(localName = "activateCarrec", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.ActivateCarrec")
    @ResponseWrapper(localName = "activateCarrecResponse", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.ActivateCarrecResponse")
    public void activateCarrec(
        @WebParam(name = "carrecID", targetNamespace = "")
        java.lang.String carrecID
    ) throws WsI18NException;

    @WebMethod
    @RequestWrapper(localName = "deactivateUsuariEntitat", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.DeactivateUsuariEntitat")
    @ResponseWrapper(localName = "deactivateUsuariEntitatResponse", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.DeactivateUsuariEntitatResponse")
    public void deactivateUsuariEntitat(
        @WebParam(name = "usuariEntitatID", targetNamespace = "")
        java.lang.String usuariEntitatID
    ) throws WsI18NException;

    @WebMethod
    @RequestWrapper(localName = "getCarrecsOfMyEntitat", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.GetCarrecsOfMyEntitat")
    @ResponseWrapper(localName = "getCarrecsOfMyEntitatResponse", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.GetCarrecsOfMyEntitatResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<es.caib.portafib.ws.api.v1.CarrecWs> getCarrecsOfMyEntitat();

    @WebMethod
    @RequestWrapper(localName = "deleteCarrec", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.DeleteCarrec")
    @ResponseWrapper(localName = "deleteCarrecResponse", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.DeleteCarrecResponse")
    public void deleteCarrec(
        @WebParam(name = "carrecID", targetNamespace = "")
        java.lang.String carrecID
    ) throws WsI18NException;

    @WebMethod
    @RequestWrapper(localName = "getInfoFromPluginUserInfoByUsername", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.GetInfoFromPluginUserInfoByUsername")
    @ResponseWrapper(localName = "getInfoFromPluginUserInfoByUsernameResponse", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.GetInfoFromPluginUserInfoByUsernameResponse")
    @WebResult(name = "return", targetNamespace = "")
    public es.caib.portafib.ws.api.v1.UsuariPersonaBean getInfoFromPluginUserInfoByUsername(
        @WebParam(name = "administrationID", targetNamespace = "")
        java.lang.String administrationID
    ) throws WsI18NException;

    @WebMethod
    @RequestWrapper(localName = "addRoleAdministradorDeEntitat", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.AddRoleAdministradorDeEntitat")
    @ResponseWrapper(localName = "addRoleAdministradorDeEntitatResponse", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.AddRoleAdministradorDeEntitatResponse")
    public void addRoleAdministradorDeEntitat(
        @WebParam(name = "usuariEntitatID", targetNamespace = "")
        java.lang.String usuariEntitatID
    ) throws WsI18NException;

    @WebMethod
    @RequestWrapper(localName = "getEntitatID", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.GetEntitatID")
    @ResponseWrapper(localName = "getEntitatIDResponse", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.GetEntitatIDResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String getEntitatID();

    @WebMethod
    @RequestWrapper(localName = "getUsuariPersona", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.GetUsuariPersona")
    @ResponseWrapper(localName = "getUsuariPersonaResponse", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.GetUsuariPersonaResponse")
    @WebResult(name = "return", targetNamespace = "")
    public es.caib.portafib.ws.api.v1.UsuariPersonaBean getUsuariPersona(
        @WebParam(name = "usuariPersonaID", targetNamespace = "")
        java.lang.String usuariPersonaID
    ) throws WsI18NException, WsValidationException;

    @WebMethod
    @RequestWrapper(localName = "getVersionWs", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.GetVersionWs")
    @ResponseWrapper(localName = "getVersionWsResponse", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.GetVersionWsResponse")
    @WebResult(name = "return", targetNamespace = "")
    public int getVersionWs();

    @WebMethod
    @RequestWrapper(localName = "activateUsuariEntitat", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.ActivateUsuariEntitat")
    @ResponseWrapper(localName = "activateUsuariEntitatResponse", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.ActivateUsuariEntitatResponse")
    public void activateUsuariEntitat(
        @WebParam(name = "usuariEntitatID", targetNamespace = "")
        java.lang.String usuariEntitatID
    ) throws WsI18NException;

    @WebMethod
    @RequestWrapper(localName = "removeRoleSolicitant", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.RemoveRoleSolicitant")
    @ResponseWrapper(localName = "removeRoleSolicitantResponse", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.RemoveRoleSolicitantResponse")
    public void removeRoleSolicitant(
        @WebParam(name = "usuariEntitatID", targetNamespace = "")
        java.lang.String usuariEntitatID
    ) throws WsI18NException;

    @WebMethod
    @RequestWrapper(localName = "getUsuariEntitatIDByAdministrationID", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.GetUsuariEntitatIDByAdministrationID")
    @ResponseWrapper(localName = "getUsuariEntitatIDByAdministrationIDResponse", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.GetUsuariEntitatIDByAdministrationIDResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String getUsuariEntitatIDByAdministrationID(
        @WebParam(name = "administrationID", targetNamespace = "")
        java.lang.String administrationID,
        @WebParam(name = "entitatID", targetNamespace = "")
        java.lang.String entitatID
    ) throws WsI18NException;
}
