package es.caib.portafib.ws.api.v1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.2.12-patch-04
 * Mon Sep 08 11:00:10 CEST 2014
 * Generated source version: 2.2.12-patch-04
 * 
 */
 
@WebService(targetNamespace = "http://impl.v1.ws.portafib.caib.es/", name = "PortaFIBUsuariAplicacioWs")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface PortaFIBUsuariAplicacioWs {

    @WebResult(name = "return", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", partName = "return")
    @WebMethod
    public java.lang.String getEntitatID();

    @WebMethod
    public void deleteUsuariAplicacio(
        @WebParam(partName = "usuariAplicacioID", name = "usuariAplicacioID")
        java.lang.String usuariAplicacioID
    ) throws WsI18NException;

    @WebResult(name = "return", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", partName = "return")
    @WebMethod
    public int getVersionWs();

    @WebResult(name = "return", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", partName = "return")
    @WebMethod
    public UsuariAplicacioBeanArray listUsuariAplicacio(
        @WebParam(partName = "usuariAplicacioFilterWs", name = "usuariAplicacioFilterWs")
        UsuariAplicacioFilterWs usuariAplicacioFilterWs
    ) throws WsI18NException;

    @WebResult(name = "return", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", partName = "return")
    @WebMethod
    public boolean removeRolUserToUsuariAplicacio(
        @WebParam(partName = "usuariAplicacioID", name = "usuariAplicacioID")
        java.lang.String usuariAplicacioID
    ) throws WsI18NException;

    @WebResult(name = "return", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", partName = "return")
    @WebMethod
    public boolean addRolAdminToUsuariAplicacio(
        @WebParam(partName = "usuariAplicacioID", name = "usuariAplicacioID")
        java.lang.String usuariAplicacioID
    ) throws WsI18NException;

    @WebMethod
    public void createUsuariAplicacio(
        @WebParam(partName = "usuariAplicacioBean", name = "usuariAplicacioBean")
        UsuariAplicacioBean usuariAplicacioBean
    ) throws WsI18NException, WsValidationException;

    @WebResult(name = "return", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", partName = "return")
    @WebMethod
    public java.lang.String getVersion();

    @WebResult(name = "return", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", partName = "return")
    @WebMethod
    public UsuariAplicacioBean getUsuariAplicacio(
        @WebParam(partName = "usuariAplicacioID", name = "usuariAplicacioID")
        java.lang.String usuariAplicacioID
    ) throws WsI18NException;

    @WebResult(name = "return", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", partName = "return")
    @WebMethod
    public StringArray getSupportedLanguages() throws WsI18NException;

    @WebResult(name = "return", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", partName = "return")
    @WebMethod
    public boolean addRolUserToUsuariAplicacio(
        @WebParam(partName = "usuariAplicacioID", name = "usuariAplicacioID")
        java.lang.String usuariAplicacioID
    ) throws WsI18NException;

    @WebResult(name = "return", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", partName = "return")
    @WebMethod
    public FitxerBean downloadFileUsingEncryptedFileID(
        @WebParam(partName = "arg0", name = "arg0")
        java.lang.String arg0
    ) throws WsI18NException;

    @WebResult(name = "return", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", partName = "return")
    @WebMethod
    public boolean removeRolAdminToUsuariAplicacio(
        @WebParam(partName = "usuariAplicacioID", name = "usuariAplicacioID")
        java.lang.String usuariAplicacioID
    ) throws WsI18NException;
}
