package es.caib.portafib.ws.api.v1;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.6.4
 * 2017-07-26T09:51:00.999+02:00
 * Generated source version: 2.6.4
 * 
 */
@WebServiceClient(name = "PortaFIBHelloWorldWsService", 
                  wsdlLocation = "http://localhost:8080/portafib/ws/v1/PortaFIBHelloWorld?wsdl",
                  targetNamespace = "http://impl.v1.ws.portafib.caib.es/") 
public class PortaFIBHelloWorldWsService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.v1.ws.portafib.caib.es/", "PortaFIBHelloWorldWsService");
    public final static QName PortaFIBHelloWorldWs = new QName("http://impl.v1.ws.portafib.caib.es/", "PortaFIBHelloWorldWs");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/portafib/ws/v1/PortaFIBHelloWorld?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(PortaFIBHelloWorldWsService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/portafib/ws/v1/PortaFIBHelloWorld?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public PortaFIBHelloWorldWsService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PortaFIBHelloWorldWsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PortaFIBHelloWorldWsService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns PortaFIBHelloWorldWs
     */
    @WebEndpoint(name = "PortaFIBHelloWorldWs")
    public PortaFIBHelloWorldWs getPortaFIBHelloWorldWs() {
        return super.getPort(PortaFIBHelloWorldWs, PortaFIBHelloWorldWs.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PortaFIBHelloWorldWs
     */
    @WebEndpoint(name = "PortaFIBHelloWorldWs")
    public PortaFIBHelloWorldWs getPortaFIBHelloWorldWs(WebServiceFeature... features) {
        return super.getPort(PortaFIBHelloWorldWs, PortaFIBHelloWorldWs.class, features);
    }

}
