
package es.caib.portafib.ws.api.v1;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.2.12-patch-04
 * Wed Nov 12 09:08:19 CET 2014
 * Generated source version: 2.2.12-patch-04
 * 
 */

@WebFault(name = "WsI18NError", targetNamespace = "http://impl.v1.ws.portafib.caib.es/")
public class WsI18NException extends Exception {
    public static final long serialVersionUID = 20141112090819L;
    
    private es.caib.portafib.ws.api.v1.WsI18NError wsI18NError;

    public WsI18NException() {
        super();
    }
    
    public WsI18NException(String message) {
        super(message);
    }
    
    public WsI18NException(String message, Throwable cause) {
        super(message, cause);
    }

    public WsI18NException(String message, es.caib.portafib.ws.api.v1.WsI18NError wsI18NError) {
        super(message);
        this.wsI18NError = wsI18NError;
    }

    public WsI18NException(String message, es.caib.portafib.ws.api.v1.WsI18NError wsI18NError, Throwable cause) {
        super(message, cause);
        this.wsI18NError = wsI18NError;
    }

    public es.caib.portafib.ws.api.v1.WsI18NError getFaultInfo() {
        return this.wsI18NError;
    }
}
