
package es.caib.portafib.ws.api.v1;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.6
 * 2023-02-15T14:03:33.001+01:00
 * Generated source version: 3.2.6
 */

@WebFault(name = "WsValidationErrors", targetNamespace = "http://impl.v1.ws.portafib.caib.es/")
public class WsValidationException extends Exception {

    private es.caib.portafib.ws.api.v1.WsValidationErrors wsValidationErrors;

    public WsValidationException() {
        super();
    }

    public WsValidationException(String message) {
        super(message);
    }

    public WsValidationException(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public WsValidationException(String message, es.caib.portafib.ws.api.v1.WsValidationErrors wsValidationErrors) {
        super(message);
        this.wsValidationErrors = wsValidationErrors;
    }

    public WsValidationException(String message, es.caib.portafib.ws.api.v1.WsValidationErrors wsValidationErrors, java.lang.Throwable cause) {
        super(message, cause);
        this.wsValidationErrors = wsValidationErrors;
    }

    public es.caib.portafib.ws.api.v1.WsValidationErrors getFaultInfo() {
        return this.wsValidationErrors;
    }
}
