buildscript {
    repositories {
        google()
        mavenCentral()  // Canvia jcenter() per mavenCentral()
    }
    dependencies {
        // Actualitza a una versió compatible amb Gradle 7.2
        classpath 'com.android.tools.build:gradle:7.0.4'
        // O prova amb: classpath 'com.android.tools.build:gradle:7.2.0'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()  // Canvia jcenter() per mavenCentral()
        maven {
            url "https://governib.github.io/maven/maven/"
            name 'GovernIB'
        }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}