/*
 * API Interna de PortaFIB que ofereix serveis de firma web immediada.
 * Conjunt de Serveis REST de PortaFIB per atendre peticions de firma a través de web de forma immediata.
 *
 * The version of the OpenAPI document: 1.0-SNAPSHOT
 * Contact: otae@fundaciobit.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package es.caib.portafib.apiinterna.client.signature.v1.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import es.caib.portafib.apiinterna.client.signature.v1.model.FileInfoSignature;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * AddFileToSignRequest
 */
@JsonPropertyOrder({
  AddFileToSignRequest.JSON_PROPERTY_TRANSACTION_I_D,
  AddFileToSignRequest.JSON_PROPERTY_FILE_INFO_SIGNATURE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class AddFileToSignRequest {
  public static final String JSON_PROPERTY_TRANSACTION_I_D = "transactionID";
  @javax.annotation.Nonnull
  private String transactionID;

  public static final String JSON_PROPERTY_FILE_INFO_SIGNATURE = "fileInfoSignature";
  @javax.annotation.Nonnull
  private FileInfoSignature fileInfoSignature;

  public AddFileToSignRequest() {
  }

  public AddFileToSignRequest transactionID(@javax.annotation.Nonnull String transactionID) {
    
    this.transactionID = transactionID;
    return this;
  }

  /**
   * Identificador de transacció
   * @return transactionID
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TRANSACTION_I_D)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getTransactionID() {
    return transactionID;
  }


  @JsonProperty(JSON_PROPERTY_TRANSACTION_I_D)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTransactionID(@javax.annotation.Nonnull String transactionID) {
    this.transactionID = transactionID;
  }

  public AddFileToSignRequest fileInfoSignature(@javax.annotation.Nonnull FileInfoSignature fileInfoSignature) {
    
    this.fileInfoSignature = fileInfoSignature;
    return this;
  }

  /**
   * Get fileInfoSignature
   * @return fileInfoSignature
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_FILE_INFO_SIGNATURE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public FileInfoSignature getFileInfoSignature() {
    return fileInfoSignature;
  }


  @JsonProperty(JSON_PROPERTY_FILE_INFO_SIGNATURE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFileInfoSignature(@javax.annotation.Nonnull FileInfoSignature fileInfoSignature) {
    this.fileInfoSignature = fileInfoSignature;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AddFileToSignRequest addFileToSignRequest = (AddFileToSignRequest) o;
    return Objects.equals(this.transactionID, addFileToSignRequest.transactionID) &&
        Objects.equals(this.fileInfoSignature, addFileToSignRequest.fileInfoSignature);
  }

  @Override
  public int hashCode() {
    return Objects.hash(transactionID, fileInfoSignature);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AddFileToSignRequest {\n");
    sb.append("    transactionID: ").append(toIndentedString(transactionID)).append("\n");
    sb.append("    fileInfoSignature: ").append(toIndentedString(fileInfoSignature)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

