/*
 * API Interna de PortaFIB que ofereix serveis associats amb la firma digital
 * Conjunt de Serveis REST de PortaFIB per atendre peticions de firma en servidor, firma web síncrona, firma web asíncrona, validació de firma i plantilla de flux de firma.
 *
 * The version of the OpenAPI document: 1.0-SNAPSHOT
 * Contact: firma@fundaciobit.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package es.caib.portafib.apiinterna.client.signature.v1.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * * ESEAL: Certificado de sello electrónico. Pertenece a una persona jurídica pero NO incluye un custodio. * ESIG: Certificado para firma electrónica (persona física). * WSA: Certificado para autenticación de servidor web.      public static final String EIDAS_UNKNOWN &#x3D; \&quot;UNKNOWN\&quot;; // Se desconoce el tipo del certificado                                                            // (Se considera no cualificado a menos                                                            // que se indique lo contrario en                                                            // certQualified).
 */
public enum CertificateTypeEidasConstants {
  
  /**
   *  
   */
  ESEAL("ESEAL"),
  
  /**
   *  
   */
  ESIG("ESIG"),
  
  /**
   *  
   */
  WSA("WSA"),
  
  /**
   *  
   */
  UNKNOWN("UNKNOWN");

  private String value;

  CertificateTypeEidasConstants(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static CertificateTypeEidasConstants fromValue(String value) {
    for (CertificateTypeEidasConstants b : CertificateTypeEidasConstants.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }
}

