/*
 * API Interna de PortaFIB que ofereix serveis de firma web.
 * Conjunt de Serveis REST de PortaFIB per atendre peticions de firma a través de web de PortaFIB
 *
 * The version of the OpenAPI document: 1.0-SNAPSHOT
 * Contact: otae@fundaciobit.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package es.caib.portafib.apiinterna.client.signature.v1.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import es.caib.portafib.apiinterna.client.signature.v1.model.DocumentaryType;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * DocumentaryTypes
 */
@JsonPropertyOrder({
  DocumentaryTypes.JSON_PROPERTY_DOCUMENTARY_TYPES
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class DocumentaryTypes {
  public static final String JSON_PROPERTY_DOCUMENTARY_TYPES = "documentaryTypes";
  @javax.annotation.Nullable
  private List<DocumentaryType> documentaryTypes = new ArrayList<>();

  public DocumentaryTypes() {
  }

  public DocumentaryTypes documentaryTypes(@javax.annotation.Nullable List<DocumentaryType> documentaryTypes) {
    
    this.documentaryTypes = documentaryTypes;
    return this;
  }

  public DocumentaryTypes addDocumentaryTypesItem(DocumentaryType documentaryTypesItem) {
    if (this.documentaryTypes == null) {
      this.documentaryTypes = new ArrayList<>();
    }
    this.documentaryTypes.add(documentaryTypesItem);
    return this;
  }

  /**
   * Get documentaryTypes
   * @return documentaryTypes
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DOCUMENTARY_TYPES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<DocumentaryType> getDocumentaryTypes() {
    return documentaryTypes;
  }


  @JsonProperty(JSON_PROPERTY_DOCUMENTARY_TYPES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDocumentaryTypes(@javax.annotation.Nullable List<DocumentaryType> documentaryTypes) {
    this.documentaryTypes = documentaryTypes;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DocumentaryTypes documentaryTypes = (DocumentaryTypes) o;
    return Objects.equals(this.documentaryTypes, documentaryTypes.documentaryTypes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(documentaryTypes);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DocumentaryTypes {\n");
    sb.append("    documentaryTypes: ").append(toIndentedString(documentaryTypes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

