/*
 * API Interna de PortaFIB que ofereix serveis de firma web immediada.
 * Conjunt de Serveis REST de PortaFIB per atendre peticions de firma a través de web de forma immediata.
 *
 * The version of the OpenAPI document: 1.0-SNAPSHOT
 * Contact: otae@fundaciobit.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package es.caib.portafib.apiinterna.client.signature.v1.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Valors: TOKEN &#x3D; 1;  PASSWORD &#x3D; 2;  CERTIFICATE &#x3D; 4;
 */
public enum ExternalSignerSecurityLevel {
  
  /**
   * token
   */
  TOKEN(1),
  
  /**
   * contrasenya
   */
  PASSWORD(2),
  
  /**
   * certificat
   */
  CERTIFICATE(4);

  private Integer value;

  ExternalSignerSecurityLevel(Integer value) {
    this.value = value;
  }

  @JsonValue
  public Integer getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static ExternalSignerSecurityLevel fromValue(Integer value) {
    for (ExternalSignerSecurityLevel b : ExternalSignerSecurityLevel.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }
}

