/*
 * API Interna de PortaFIB que ofereix serveis de firma web immediada.
 * Conjunt de Serveis REST de PortaFIB per atendre peticions de firma a través de web de forma immediata.
 *
 * The version of the OpenAPI document: 1.0-SNAPSHOT
 * Contact: otae@fundaciobit.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package es.caib.portafib.apiinterna.client.signature.v1.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Informació requerida per definir un Usuari Extern per a la firma electrònica.
 */
@JsonPropertyOrder({
  ExternalSigner.JSON_PROPERTY_ADMINISTRATION_ID,
  ExternalSigner.JSON_PROPERTY_NAME,
  ExternalSigner.JSON_PROPERTY_SURNAMES,
  ExternalSigner.JSON_PROPERTY_EMAIL,
  ExternalSigner.JSON_PROPERTY_LANGUAGE,
  ExternalSigner.JSON_PROPERTY_SECURITY_LEVEL
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class ExternalSigner {
  public static final String JSON_PROPERTY_ADMINISTRATION_ID = "administrationId";
  @javax.annotation.Nonnull
  private String administrationId;

  public static final String JSON_PROPERTY_NAME = "name";
  @javax.annotation.Nonnull
  private String name;

  public static final String JSON_PROPERTY_SURNAMES = "surnames";
  @javax.annotation.Nonnull
  private String surnames;

  public static final String JSON_PROPERTY_EMAIL = "email";
  @javax.annotation.Nonnull
  private String email;

  public static final String JSON_PROPERTY_LANGUAGE = "language";
  @javax.annotation.Nonnull
  private String language;

  public static final String JSON_PROPERTY_SECURITY_LEVEL = "securityLevel";
  @javax.annotation.Nonnull
  private Integer securityLevel;

  public ExternalSigner() {
  }

  public ExternalSigner administrationId(@javax.annotation.Nonnull String administrationId) {
    
    this.administrationId = administrationId;
    return this;
  }

  /**
   * NIF o DNI
   * @return administrationId
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ADMINISTRATION_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getAdministrationId() {
    return administrationId;
  }


  @JsonProperty(JSON_PROPERTY_ADMINISTRATION_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAdministrationId(@javax.annotation.Nonnull String administrationId) {
    this.administrationId = administrationId;
  }

  public ExternalSigner name(@javax.annotation.Nonnull String name) {
    
    this.name = name;
    return this;
  }

  /**
   * Nom de la Persona
   * @return name
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setName(@javax.annotation.Nonnull String name) {
    this.name = name;
  }

  public ExternalSigner surnames(@javax.annotation.Nonnull String surnames) {
    
    this.surnames = surnames;
    return this;
  }

  /**
   * Llinatges de la Persona
   * @return surnames
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SURNAMES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getSurnames() {
    return surnames;
  }


  @JsonProperty(JSON_PROPERTY_SURNAMES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSurnames(@javax.annotation.Nonnull String surnames) {
    this.surnames = surnames;
  }

  public ExternalSigner email(@javax.annotation.Nonnull String email) {
    
    this.email = email;
    return this;
  }

  /**
   * Correu electrònic de la persona
   * @return email
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_EMAIL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getEmail() {
    return email;
  }


  @JsonProperty(JSON_PROPERTY_EMAIL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setEmail(@javax.annotation.Nonnull String email) {
    this.email = email;
  }

  public ExternalSigner language(@javax.annotation.Nonnull String language) {
    
    this.language = language;
    return this;
  }

  /**
   * Idioma en que mostrar les pantalles web.
   * @return language
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_LANGUAGE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getLanguage() {
    return language;
  }


  @JsonProperty(JSON_PROPERTY_LANGUAGE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLanguage(@javax.annotation.Nonnull String language) {
    this.language = language;
  }

  public ExternalSigner securityLevel(@javax.annotation.Nonnull Integer securityLevel) {
    
    this.securityLevel = securityLevel;
    return this;
  }

  /**
   * Nivell de Seguretat
   * @return securityLevel
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SECURITY_LEVEL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getSecurityLevel() {
    return securityLevel;
  }


  @JsonProperty(JSON_PROPERTY_SECURITY_LEVEL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSecurityLevel(@javax.annotation.Nonnull Integer securityLevel) {
    this.securityLevel = securityLevel;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExternalSigner externalSigner = (ExternalSigner) o;
    return Objects.equals(this.administrationId, externalSigner.administrationId) &&
        Objects.equals(this.name, externalSigner.name) &&
        Objects.equals(this.surnames, externalSigner.surnames) &&
        Objects.equals(this.email, externalSigner.email) &&
        Objects.equals(this.language, externalSigner.language) &&
        Objects.equals(this.securityLevel, externalSigner.securityLevel);
  }

  @Override
  public int hashCode() {
    return Objects.hash(administrationId, name, surnames, email, language, securityLevel);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExternalSigner {\n");
    sb.append("    administrationId: ").append(toIndentedString(administrationId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    surnames: ").append(toIndentedString(surnames)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    language: ").append(toIndentedString(language)).append("\n");
    sb.append("    securityLevel: ").append(toIndentedString(securityLevel)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

