/*
 * API Interna de PortaFIB que ofereix serveis de firma web immediada.
 * Conjunt de Serveis REST de PortaFIB per atendre peticions de firma a través de web de forma immediata.
 *
 * The version of the OpenAPI document: 1.0-SNAPSHOT
 * Contact: otae@fundaciobit.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package es.caib.portafib.apiinterna.client.signature.v1.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * SignatureRequestState
 */
@JsonPropertyOrder({
  SignatureRequestState.JSON_PROPERTY_STATE,
  SignatureRequestState.JSON_PROPERTY_REJECTED_REASON
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class SignatureRequestState {
  public static final String JSON_PROPERTY_STATE = "state";
  @javax.annotation.Nullable
  private Integer state;

  public static final String JSON_PROPERTY_REJECTED_REASON = "rejectedReason";
  @javax.annotation.Nullable
  private String rejectedReason;

  public SignatureRequestState() {
  }

  public SignatureRequestState state(@javax.annotation.Nullable Integer state) {
    
    this.state = state;
    return this;
  }

  /**
   * Get state
   * @return state
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getState() {
    return state;
  }


  @JsonProperty(JSON_PROPERTY_STATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setState(@javax.annotation.Nullable Integer state) {
    this.state = state;
  }

  public SignatureRequestState rejectedReason(@javax.annotation.Nullable String rejectedReason) {
    
    this.rejectedReason = rejectedReason;
    return this;
  }

  /**
   * Get rejectedReason
   * @return rejectedReason
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REJECTED_REASON)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getRejectedReason() {
    return rejectedReason;
  }


  @JsonProperty(JSON_PROPERTY_REJECTED_REASON)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRejectedReason(@javax.annotation.Nullable String rejectedReason) {
    this.rejectedReason = rejectedReason;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SignatureRequestState signatureRequestState = (SignatureRequestState) o;
    return Objects.equals(this.state, signatureRequestState.state) &&
        Objects.equals(this.rejectedReason, signatureRequestState.rejectedReason);
  }

  @Override
  public int hashCode() {
    return Objects.hash(state, rejectedReason);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SignatureRequestState {\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    rejectedReason: ").append(toIndentedString(rejectedReason)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

