/*
 * API Interna de PortaFIB que ofereix serveis de firma web immediada.
 * Conjunt de Serveis REST de PortaFIB per atendre peticions de firma a través de web de forma immediata.
 *
 * The version of the OpenAPI document: 1.0-SNAPSHOT
 * Contact: otae@fundaciobit.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package es.caib.portafib.apiinterna.client.signature.v1.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Informació requerida a que el sistema retorni un identificador de transacció per a la creació web d&#39;una plantilla de flux de signatura
 */
@JsonPropertyOrder({
  SignatureFlowTemplateTransactionIdRequest.JSON_PROPERTY_LANGUAGE_U_I,
  SignatureFlowTemplateTransactionIdRequest.JSON_PROPERTY_SAVE_ON_SERVER,
  SignatureFlowTemplateTransactionIdRequest.JSON_PROPERTY_NAME,
  SignatureFlowTemplateTransactionIdRequest.JSON_PROPERTY_DESCRIPTION,
  SignatureFlowTemplateTransactionIdRequest.JSON_PROPERTY_VISIBLE_DESCRIPTION
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class SignatureFlowTemplateTransactionIdRequest {
  public static final String JSON_PROPERTY_LANGUAGE_U_I = "languageUI";
  @javax.annotation.Nullable
  private String languageUI;

  public static final String JSON_PROPERTY_SAVE_ON_SERVER = "saveOnServer";
  @javax.annotation.Nullable
  private Boolean saveOnServer;

  public static final String JSON_PROPERTY_NAME = "name";
  @javax.annotation.Nullable
  private String name;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  @javax.annotation.Nullable
  private String description;

  public static final String JSON_PROPERTY_VISIBLE_DESCRIPTION = "visibleDescription";
  @javax.annotation.Nullable
  private Boolean visibleDescription;

  public SignatureFlowTemplateTransactionIdRequest() {
  }

  public SignatureFlowTemplateTransactionIdRequest languageUI(@javax.annotation.Nullable String languageUI) {
    
    this.languageUI = languageUI;
    return this;
  }

  /**
   * Codi de l&#39;idioma de la interfície d&#39;usuari
   * @return languageUI
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LANGUAGE_U_I)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLanguageUI() {
    return languageUI;
  }


  @JsonProperty(JSON_PROPERTY_LANGUAGE_U_I)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLanguageUI(@javax.annotation.Nullable String languageUI) {
    this.languageUI = languageUI;
  }

  public SignatureFlowTemplateTransactionIdRequest saveOnServer(@javax.annotation.Nullable Boolean saveOnServer) {
    
    this.saveOnServer = saveOnServer;
    return this;
  }

  /**
   * Indica si s&#39;ha de guardar la plantilla al servidor
   * @return saveOnServer
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SAVE_ON_SERVER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getSaveOnServer() {
    return saveOnServer;
  }


  @JsonProperty(JSON_PROPERTY_SAVE_ON_SERVER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSaveOnServer(@javax.annotation.Nullable Boolean saveOnServer) {
    this.saveOnServer = saveOnServer;
  }

  public SignatureFlowTemplateTransactionIdRequest name(@javax.annotation.Nullable String name) {
    
    this.name = name;
    return this;
  }

  /**
   * Nom de la plantilla de flux
   * @return name
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(@javax.annotation.Nullable String name) {
    this.name = name;
  }

  public SignatureFlowTemplateTransactionIdRequest description(@javax.annotation.Nullable String description) {
    
    this.description = description;
    return this;
  }

  /**
   * Descripció de la plantilla de flux
   * @return description
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDescription() {
    return description;
  }


  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDescription(@javax.annotation.Nullable String description) {
    this.description = description;
  }

  public SignatureFlowTemplateTransactionIdRequest visibleDescription(@javax.annotation.Nullable Boolean visibleDescription) {
    
    this.visibleDescription = visibleDescription;
    return this;
  }

  /**
   * Indica si la descripció de la plantilla de flux és visible per l&#39;usuari que l&#39;edita o el veu.
   * @return visibleDescription
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VISIBLE_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getVisibleDescription() {
    return visibleDescription;
  }


  @JsonProperty(JSON_PROPERTY_VISIBLE_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVisibleDescription(@javax.annotation.Nullable Boolean visibleDescription) {
    this.visibleDescription = visibleDescription;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SignatureFlowTemplateTransactionIdRequest signatureFlowTemplateTransactionIdRequest = (SignatureFlowTemplateTransactionIdRequest) o;
    return Objects.equals(this.languageUI, signatureFlowTemplateTransactionIdRequest.languageUI) &&
        Objects.equals(this.saveOnServer, signatureFlowTemplateTransactionIdRequest.saveOnServer) &&
        Objects.equals(this.name, signatureFlowTemplateTransactionIdRequest.name) &&
        Objects.equals(this.description, signatureFlowTemplateTransactionIdRequest.description) &&
        Objects.equals(this.visibleDescription, signatureFlowTemplateTransactionIdRequest.visibleDescription);
  }

  @Override
  public int hashCode() {
    return Objects.hash(languageUI, saveOnServer, name, description, visibleDescription);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SignatureFlowTemplateTransactionIdRequest {\n");
    sb.append("    languageUI: ").append(toIndentedString(languageUI)).append("\n");
    sb.append("    saveOnServer: ").append(toIndentedString(saveOnServer)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    visibleDescription: ").append(toIndentedString(visibleDescription)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

