/*
 * API Interna de PortaFIB que ofereix serveis de firma web.
 * Conjunt de Serveis REST de PortaFIB per atendre peticions de firma a través de web de PortaFIB
 *
 * The version of the OpenAPI document: 1.0-SNAPSHOT
 * Contact: otae@fundaciobit.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package es.caib.portafib.apiinterna.client.signature.v1.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Perfil empleado en una firma con certificado electrónico. Los posibles valores asignables son los siguientes:    AdES-BES    AdES-EPES    AdES-T    AdES-C    AdES-X    AdES-X1    AdES-X2    AdES-XL    AdES-XL1    AdES-XL2    AdES-A    PAdES-LTV    PAdES-Basic
 */
public enum SignProfileConstants {
  
  /**
   *  
   */
  SIGN_PROFILE_BES("AdES-BES"),
  
  /**
   *  
   */
  SIGN_PROFILE_EPES("AdES-EPES"),
  
  /**
   *  
   */
  SIGN_PROFILE_T("AdES-T"),
  
  /**
   *  
   */
  SIGN_PROFILE_C("AdES-C"),
  
  /**
   *  
   */
  SIGN_PROFILE_X("AdES-X"),
  
  /**
   *  
   */
  SIGN_PROFILE_X1("AdES-X1"),
  
  /**
   *  
   */
  SIGN_PROFILE_X2("AdES-X2"),
  
  /**
   *  
   */
  SIGN_PROFILE_XL("AdES-XL"),
  
  /**
   *  
   */
  SIGN_PROFILE_XL1("AdES-XL1"),
  
  /**
   *  
   */
  SIGN_PROFILE_XL2("AdES-XL2"),
  
  /**
   *  
   */
  SIGN_PROFILE_A("AdES-A"),
  
  /**
   *  
   */
  SIGN_PROFILE_PADES_LTV("PAdES-LTV"),
  
  /**
   *  
   */
  SIGN_PROFILE_PADES_BASIC("PAdES-Basic");

  private String value;

  SignProfileConstants(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static SignProfileConstants fromValue(String value) {
    for (SignProfileConstants b : SignProfileConstants.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }
}

