/*
 * API Interna de PortaFIB que ofereix serveis associats amb la firma digital
 * Conjunt de Serveis REST de PortaFIB per atendre peticions de firma en servidor, firma web síncrona, firma web asíncrona, validació de firma i plantilla de flux de firma.
 *
 * The version of the OpenAPI document: 1.0-SNAPSHOT
 * Contact: firma@fundaciobit.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package es.caib.portafib.apiinterna.client.signature.v1.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import es.caib.portafib.apiinterna.client.signature.v1.model.ExternalSigner;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Classe que representa un firmant. Només s&#39;ha d&#39;omplir un camp dels que conté.
 */
@JsonPropertyOrder({
  Signer.JSON_PROPERTY_POSITION_IN_THE_COMPANY,
  Signer.JSON_PROPERTY_ADMINISTRATION_I_D,
  Signer.JSON_PROPERTY_USERNAME,
  Signer.JSON_PROPERTY_INTERMEDIATE_SERVER_USERNAME,
  Signer.JSON_PROPERTY_EXTERNAL_SIGNER
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class Signer {
  public static final String JSON_PROPERTY_POSITION_IN_THE_COMPANY = "positionInTheCompany";
  @javax.annotation.Nullable
  private String positionInTheCompany;

  public static final String JSON_PROPERTY_ADMINISTRATION_I_D = "administrationID";
  @javax.annotation.Nullable
  private String administrationID;

  public static final String JSON_PROPERTY_USERNAME = "username";
  @javax.annotation.Nullable
  private String username;

  public static final String JSON_PROPERTY_INTERMEDIATE_SERVER_USERNAME = "intermediateServerUsername";
  @javax.annotation.Nullable
  private String intermediateServerUsername;

  public static final String JSON_PROPERTY_EXTERNAL_SIGNER = "externalSigner";
  @javax.annotation.Nullable
  private ExternalSigner externalSigner;

  public Signer() {
  }

  public Signer positionInTheCompany(@javax.annotation.Nullable String positionInTheCompany) {
    
    this.positionInTheCompany = positionInTheCompany;
    return this;
  }

  /**
   * Identificador que representa un Càrrec. Exemples: fundaciobit_gerent, caib_president, ...
   * @return positionInTheCompany
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_POSITION_IN_THE_COMPANY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPositionInTheCompany() {
    return positionInTheCompany;
  }


  @JsonProperty(JSON_PROPERTY_POSITION_IN_THE_COMPANY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPositionInTheCompany(@javax.annotation.Nullable String positionInTheCompany) {
    this.positionInTheCompany = positionInTheCompany;
  }

  public Signer administrationID(@javax.annotation.Nullable String administrationID) {
    
    this.administrationID = administrationID;
    return this;
  }

  /**
   * Identificador administratiu. En el cas de PortaFIB serà NIF, NIE, ...
   * @return administrationID
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ADMINISTRATION_I_D)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAdministrationID() {
    return administrationID;
  }


  @JsonProperty(JSON_PROPERTY_ADMINISTRATION_I_D)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAdministrationID(@javax.annotation.Nullable String administrationID) {
    this.administrationID = administrationID;
  }

  public Signer username(@javax.annotation.Nullable String username) {
    
    this.username = username;
    return this;
  }

  /**
   * Nom d&#39;usuari que té la persona en la corporació o entitat. Exemples: u806666 o anadal
   * @return username
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_USERNAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUsername() {
    return username;
  }


  @JsonProperty(JSON_PROPERTY_USERNAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUsername(@javax.annotation.Nullable String username) {
    this.username = username;
  }

  public Signer intermediateServerUsername(@javax.annotation.Nullable String intermediateServerUsername) {
    
    this.intermediateServerUsername = intermediateServerUsername;
    return this;
  }

  /**
   * ID intern del servidor intermedi (en el nostre cas PortaFIB). Exemples: fundaciobit_anadal, caib_u80067, ...
   * @return intermediateServerUsername
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_INTERMEDIATE_SERVER_USERNAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getIntermediateServerUsername() {
    return intermediateServerUsername;
  }


  @JsonProperty(JSON_PROPERTY_INTERMEDIATE_SERVER_USERNAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIntermediateServerUsername(@javax.annotation.Nullable String intermediateServerUsername) {
    this.intermediateServerUsername = intermediateServerUsername;
  }

  public Signer externalSigner(@javax.annotation.Nullable ExternalSigner externalSigner) {
    
    this.externalSigner = externalSigner;
    return this;
  }

  /**
   * Get externalSigner
   * @return externalSigner
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EXTERNAL_SIGNER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ExternalSigner getExternalSigner() {
    return externalSigner;
  }


  @JsonProperty(JSON_PROPERTY_EXTERNAL_SIGNER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExternalSigner(@javax.annotation.Nullable ExternalSigner externalSigner) {
    this.externalSigner = externalSigner;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Signer signer = (Signer) o;
    return Objects.equals(this.positionInTheCompany, signer.positionInTheCompany) &&
        Objects.equals(this.administrationID, signer.administrationID) &&
        Objects.equals(this.username, signer.username) &&
        Objects.equals(this.intermediateServerUsername, signer.intermediateServerUsername) &&
        Objects.equals(this.externalSigner, signer.externalSigner);
  }

  @Override
  public int hashCode() {
    return Objects.hash(positionInTheCompany, administrationID, username, intermediateServerUsername, externalSigner);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Signer {\n");
    sb.append("    positionInTheCompany: ").append(toIndentedString(positionInTheCompany)).append("\n");
    sb.append("    administrationID: ").append(toIndentedString(administrationID)).append("\n");
    sb.append("    username: ").append(toIndentedString(username)).append("\n");
    sb.append("    intermediateServerUsername: ").append(toIndentedString(intermediateServerUsername)).append("\n");
    sb.append("    externalSigner: ").append(toIndentedString(externalSigner)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

