/*
 * API Interna de PortaFIB que ofereix serveis de firma web immediada.
 * Conjunt de Serveis REST de PortaFIB per atendre peticions de firma a través de web de forma immediata.
 *
 * The version of the OpenAPI document: 1.0-SNAPSHOT
 * Contact: otae@fundaciobit.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package es.caib.portafib.apiinterna.client.signature.v1.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import es.caib.portafib.apiinterna.client.signature.v1.model.Reviser;
import es.caib.portafib.apiinterna.client.signature.v1.model.Signer;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Definició d&#39;una Firma
 */
@JsonPropertyOrder({
  Signature.JSON_PROPERTY_SIGNER,
  Signature.JSON_PROPERTY_REQUIRED,
  Signature.JSON_PROPERTY_REASON,
  Signature.JSON_PROPERTY_MINIMUM_NUMBER_OF_REVISERS,
  Signature.JSON_PROPERTY_REVISERS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class Signature {
  public static final String JSON_PROPERTY_SIGNER = "signer";
  @javax.annotation.Nonnull
  private Signer signer;

  public static final String JSON_PROPERTY_REQUIRED = "required";
  @javax.annotation.Nonnull
  private Boolean required;

  public static final String JSON_PROPERTY_REASON = "reason";
  @javax.annotation.Nullable
  private String reason;

  public static final String JSON_PROPERTY_MINIMUM_NUMBER_OF_REVISERS = "minimumNumberOfRevisers";
  @javax.annotation.Nonnull
  private Integer minimumNumberOfRevisers = 0;

  public static final String JSON_PROPERTY_REVISERS = "revisers";
  @javax.annotation.Nullable
  private List<Reviser> revisers = new ArrayList<>();

  public Signature() {
  }

  public Signature signer(@javax.annotation.Nonnull Signer signer) {
    
    this.signer = signer;
    return this;
  }

  /**
   * Get signer
   * @return signer
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SIGNER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Signer getSigner() {
    return signer;
  }


  @JsonProperty(JSON_PROPERTY_SIGNER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSigner(@javax.annotation.Nonnull Signer signer) {
    this.signer = signer;
  }

  public Signature required(@javax.annotation.Nonnull Boolean required) {
    
    this.required = required;
    return this;
  }

  /**
   * És obligatori que aquesta persona firmi
   * @return required
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_REQUIRED)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Boolean getRequired() {
    return required;
  }


  @JsonProperty(JSON_PROPERTY_REQUIRED)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRequired(@javax.annotation.Nonnull Boolean required) {
    this.required = required;
  }

  public Signature reason(@javax.annotation.Nullable String reason) {
    
    this.reason = reason;
    return this;
  }

  /**
   * Raó de firma específica per aquesta firma. Sinó es defineix s&#39;utilitzarà la raó definida en la Petició de Firma.
   * @return reason
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REASON)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getReason() {
    return reason;
  }


  @JsonProperty(JSON_PROPERTY_REASON)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReason(@javax.annotation.Nullable String reason) {
    this.reason = reason;
  }

  public Signature minimumNumberOfRevisers(@javax.annotation.Nonnull Integer minimumNumberOfRevisers) {
    
    this.minimumNumberOfRevisers = minimumNumberOfRevisers;
    return this;
  }

  /**
   * Número mínim de revisors. Per defecte 0.
   * @return minimumNumberOfRevisers
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_MINIMUM_NUMBER_OF_REVISERS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getMinimumNumberOfRevisers() {
    return minimumNumberOfRevisers;
  }


  @JsonProperty(JSON_PROPERTY_MINIMUM_NUMBER_OF_REVISERS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMinimumNumberOfRevisers(@javax.annotation.Nonnull Integer minimumNumberOfRevisers) {
    this.minimumNumberOfRevisers = minimumNumberOfRevisers;
  }

  public Signature revisers(@javax.annotation.Nullable List<Reviser> revisers) {
    
    this.revisers = revisers;
    return this;
  }

  public Signature addRevisersItem(Reviser revisersItem) {
    if (this.revisers == null) {
      this.revisers = new ArrayList<>();
    }
    this.revisers.add(revisersItem);
    return this;
  }

  /**
   * Llistat de revisors de la Firma. Abans de que aquest destinatari firma, els revisors hauran d&#39;haver acceptat el document.
   * @return revisers
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REVISERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Reviser> getRevisers() {
    return revisers;
  }


  @JsonProperty(JSON_PROPERTY_REVISERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRevisers(@javax.annotation.Nullable List<Reviser> revisers) {
    this.revisers = revisers;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Signature signature = (Signature) o;
    return Objects.equals(this.signer, signature.signer) &&
        Objects.equals(this.required, signature.required) &&
        Objects.equals(this.reason, signature.reason) &&
        Objects.equals(this.minimumNumberOfRevisers, signature.minimumNumberOfRevisers) &&
        Objects.equals(this.revisers, signature.revisers);
  }

  @Override
  public int hashCode() {
    return Objects.hash(signer, required, reason, minimumNumberOfRevisers, revisers);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Signature {\n");
    sb.append("    signer: ").append(toIndentedString(signer)).append("\n");
    sb.append("    required: ").append(toIndentedString(required)).append("\n");
    sb.append("    reason: ").append(toIndentedString(reason)).append("\n");
    sb.append("    minimumNumberOfRevisers: ").append(toIndentedString(minimumNumberOfRevisers)).append("\n");
    sb.append("    revisers: ").append(toIndentedString(revisers)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

