/*
 * API Interna de PortaFIB que ofereix serveis associats amb la firma digital
 * Conjunt de Serveis REST de PortaFIB per atendre peticions de firma en servidor, firma web síncrona, firma web asíncrona, validació de firma i plantilla de flux de firma.
 *
 * The version of the OpenAPI document: 1.0-SNAPSHOT
 * Contact: firma@fundaciobit.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package es.caib.portafib.apiinterna.client.signature.v1.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import es.caib.portafib.apiinterna.client.signature.v1.model.Annex;
import es.caib.portafib.apiinterna.client.signature.v1.model.Document;
import es.caib.portafib.apiinterna.client.signature.v1.model.Metadata;
import es.caib.portafib.apiinterna.client.signature.v1.model.SignatureBlock;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Estructura de dades per a la sol·licitud de signatura electrònica a partir d&#39;una llista de blocs de signatura
 */
@JsonPropertyOrder({
  SignatureRequestWithSignBlockList.JSON_PROPERTY_PROFILE_CODE,
  SignatureRequestWithSignBlockList.JSON_PROPERTY_FILE_TO_SIGN,
  SignatureRequestWithSignBlockList.JSON_PROPERTY_ORIGINAL_DETACHED_SIGNATURE,
  SignatureRequestWithSignBlockList.JSON_PROPERTY_TITLE,
  SignatureRequestWithSignBlockList.JSON_PROPERTY_DESCRIPTION,
  SignatureRequestWithSignBlockList.JSON_PROPERTY_REASON,
  SignatureRequestWithSignBlockList.JSON_PROPERTY_DOCUMENT_TYPE,
  SignatureRequestWithSignBlockList.JSON_PROPERTY_DOCUMENT_TYPE_DESCRIPTION,
  SignatureRequestWithSignBlockList.JSON_PROPERTY_LANGUAGE_DOC,
  SignatureRequestWithSignBlockList.JSON_PROPERTY_LANGUAGE_U_I,
  SignatureRequestWithSignBlockList.JSON_PROPERTY_PRIORITY,
  SignatureRequestWithSignBlockList.JSON_PROPERTY_SENDER_NAME,
  SignatureRequestWithSignBlockList.JSON_PROPERTY_EXPIRATION_DATE,
  SignatureRequestWithSignBlockList.JSON_PROPERTY_REQUIRES_TIME_STAMP_IN_SIGNATURE,
  SignatureRequestWithSignBlockList.JSON_PROPERTY_SENDER_DESCRIPTION,
  SignatureRequestWithSignBlockList.JSON_PROPERTY_EXPEDIENT_CODE,
  SignatureRequestWithSignBlockList.JSON_PROPERTY_EXPEDIENT_NAME,
  SignatureRequestWithSignBlockList.JSON_PROPERTY_EXPEDIENT_URL,
  SignatureRequestWithSignBlockList.JSON_PROPERTY_PROCEDURE_CODE,
  SignatureRequestWithSignBlockList.JSON_PROPERTY_PROCEDURE_NAME,
  SignatureRequestWithSignBlockList.JSON_PROPERTY_ADDITIONAL_INFORMATION,
  SignatureRequestWithSignBlockList.JSON_PROPERTY_ADDITIONAL_INFORMATION_EVALUABLE,
  SignatureRequestWithSignBlockList.JSON_PROPERTY_ANNEXS,
  SignatureRequestWithSignBlockList.JSON_PROPERTY_METADADA_LIST,
  SignatureRequestWithSignBlockList.JSON_PROPERTY_SIGNATURE_BLOCKS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class SignatureRequestWithSignBlockList {
  public static final String JSON_PROPERTY_PROFILE_CODE = "profileCode";
  @javax.annotation.Nonnull
  private String profileCode;

  public static final String JSON_PROPERTY_FILE_TO_SIGN = "fileToSign";
  @javax.annotation.Nonnull
  private Document fileToSign;

  public static final String JSON_PROPERTY_ORIGINAL_DETACHED_SIGNATURE = "originalDetachedSignature";
  @javax.annotation.Nullable
  private Document originalDetachedSignature;

  public static final String JSON_PROPERTY_TITLE = "title";
  @javax.annotation.Nonnull
  private String title;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  @javax.annotation.Nonnull
  private String description;

  public static final String JSON_PROPERTY_REASON = "reason";
  @javax.annotation.Nonnull
  private String reason;

  public static final String JSON_PROPERTY_DOCUMENT_TYPE = "documentType";
  @javax.annotation.Nonnull
  private Long documentType;

  public static final String JSON_PROPERTY_DOCUMENT_TYPE_DESCRIPTION = "documentTypeDescription";
  @javax.annotation.Nullable
  private String documentTypeDescription;

  public static final String JSON_PROPERTY_LANGUAGE_DOC = "languageDoc";
  @javax.annotation.Nonnull
  private String languageDoc;

  public static final String JSON_PROPERTY_LANGUAGE_U_I = "languageUI";
  @javax.annotation.Nonnull
  private String languageUI;

  public static final String JSON_PROPERTY_PRIORITY = "priority";
  @javax.annotation.Nonnull
  private Integer priority;

  public static final String JSON_PROPERTY_SENDER_NAME = "senderName";
  @javax.annotation.Nonnull
  private String senderName;

  public static final String JSON_PROPERTY_EXPIRATION_DATE = "expirationDate";
  @javax.annotation.Nullable
  private OffsetDateTime expirationDate;

  public static final String JSON_PROPERTY_REQUIRES_TIME_STAMP_IN_SIGNATURE = "requiresTimeStampInSignature";
  @javax.annotation.Nullable
  private Boolean requiresTimeStampInSignature;

  public static final String JSON_PROPERTY_SENDER_DESCRIPTION = "senderDescription";
  @javax.annotation.Nullable
  private String senderDescription;

  public static final String JSON_PROPERTY_EXPEDIENT_CODE = "expedientCode";
  @javax.annotation.Nullable
  private String expedientCode;

  public static final String JSON_PROPERTY_EXPEDIENT_NAME = "expedientName";
  @javax.annotation.Nullable
  private String expedientName;

  public static final String JSON_PROPERTY_EXPEDIENT_URL = "expedientUrl";
  @javax.annotation.Nullable
  private String expedientUrl;

  public static final String JSON_PROPERTY_PROCEDURE_CODE = "procedureCode";
  @javax.annotation.Nullable
  private String procedureCode;

  public static final String JSON_PROPERTY_PROCEDURE_NAME = "procedureName";
  @javax.annotation.Nullable
  private String procedureName;

  public static final String JSON_PROPERTY_ADDITIONAL_INFORMATION = "additionalInformation";
  @javax.annotation.Nullable
  private String additionalInformation;

  public static final String JSON_PROPERTY_ADDITIONAL_INFORMATION_EVALUABLE = "additionalInformationEvaluable";
  @javax.annotation.Nullable
  private Double additionalInformationEvaluable;

  public static final String JSON_PROPERTY_ANNEXS = "annexs";
  @javax.annotation.Nullable
  private List<Annex> annexs = new ArrayList<>();

  public static final String JSON_PROPERTY_METADADA_LIST = "metadadaList";
  @javax.annotation.Nullable
  private List<Metadata> metadadaList = new ArrayList<>();

  public static final String JSON_PROPERTY_SIGNATURE_BLOCKS = "signatureBlocks";
  @javax.annotation.Nonnull
  private List<SignatureBlock> signatureBlocks = new ArrayList<>();

  public SignatureRequestWithSignBlockList() {
  }

  public SignatureRequestWithSignBlockList profileCode(@javax.annotation.Nonnull String profileCode) {
    
    this.profileCode = profileCode;
    return this;
  }

  /**
   * Perfil a utilitzar per la Firma.Consultar amb administrador del PortaFirmes
   * @return profileCode
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_PROFILE_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getProfileCode() {
    return profileCode;
  }


  @JsonProperty(JSON_PROPERTY_PROFILE_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setProfileCode(@javax.annotation.Nonnull String profileCode) {
    this.profileCode = profileCode;
  }

  public SignatureRequestWithSignBlockList fileToSign(@javax.annotation.Nonnull Document fileToSign) {
    
    this.fileToSign = fileToSign;
    return this;
  }

  /**
   * Get fileToSign
   * @return fileToSign
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_FILE_TO_SIGN)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Document getFileToSign() {
    return fileToSign;
  }


  @JsonProperty(JSON_PROPERTY_FILE_TO_SIGN)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFileToSign(@javax.annotation.Nonnull Document fileToSign) {
    this.fileToSign = fileToSign;
  }

  public SignatureRequestWithSignBlockList originalDetachedSignature(@javax.annotation.Nullable Document originalDetachedSignature) {
    
    this.originalDetachedSignature = originalDetachedSignature;
    return this;
  }

  /**
   * Get originalDetachedSignature
   * @return originalDetachedSignature
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ORIGINAL_DETACHED_SIGNATURE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Document getOriginalDetachedSignature() {
    return originalDetachedSignature;
  }


  @JsonProperty(JSON_PROPERTY_ORIGINAL_DETACHED_SIGNATURE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOriginalDetachedSignature(@javax.annotation.Nullable Document originalDetachedSignature) {
    this.originalDetachedSignature = originalDetachedSignature;
  }

  public SignatureRequestWithSignBlockList title(@javax.annotation.Nonnull String title) {
    
    this.title = title;
    return this;
  }

  /**
   * Títol de la Petició de Firma
   * @return title
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TITLE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getTitle() {
    return title;
  }


  @JsonProperty(JSON_PROPERTY_TITLE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTitle(@javax.annotation.Nonnull String title) {
    this.title = title;
  }

  public SignatureRequestWithSignBlockList description(@javax.annotation.Nonnull String description) {
    
    this.description = description;
    return this;
  }

  /**
   * Descripció de la Petició de Firma
   * @return description
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getDescription() {
    return description;
  }


  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDescription(@javax.annotation.Nonnull String description) {
    this.description = description;
  }

  public SignatureRequestWithSignBlockList reason(@javax.annotation.Nonnull String reason) {
    
    this.reason = reason;
    return this;
  }

  /**
   * Raó de la realització de la firma
   * @return reason
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_REASON)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getReason() {
    return reason;
  }


  @JsonProperty(JSON_PROPERTY_REASON)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setReason(@javax.annotation.Nonnull String reason) {
    this.reason = reason;
  }

  public SignatureRequestWithSignBlockList documentType(@javax.annotation.Nonnull Long documentType) {
    
    this.documentType = documentType;
    return this;
  }

  /**
   * Identificador de Tipus de Document.Els valors base s poden obtenir de l&#39;enumeració DocumentaryTypeConstants però es recomana fer una consulta al mètode getDocumentaryTypes()
   * @return documentType
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_DOCUMENT_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getDocumentType() {
    return documentType;
  }


  @JsonProperty(JSON_PROPERTY_DOCUMENT_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDocumentType(@javax.annotation.Nonnull Long documentType) {
    this.documentType = documentType;
  }

  public SignatureRequestWithSignBlockList documentTypeDescription(@javax.annotation.Nullable String documentTypeDescription) {
    
    this.documentTypeDescription = documentTypeDescription;
    return this;
  }

  /**
   * Descripció detallada del Tipus documental.
   * @return documentTypeDescription
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DOCUMENT_TYPE_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDocumentTypeDescription() {
    return documentTypeDescription;
  }


  @JsonProperty(JSON_PROPERTY_DOCUMENT_TYPE_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDocumentTypeDescription(@javax.annotation.Nullable String documentTypeDescription) {
    this.documentTypeDescription = documentTypeDescription;
  }

  public SignatureRequestWithSignBlockList languageDoc(@javax.annotation.Nonnull String languageDoc) {
    
    this.languageDoc = languageDoc;
    return this;
  }

  /**
   * Idioma en que està escrit el document.Valors són &#39;es&#39; o &#39;ca&#39; però es realitzar una cridada al mètode getLanguages()
   * @return languageDoc
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_LANGUAGE_DOC)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getLanguageDoc() {
    return languageDoc;
  }


  @JsonProperty(JSON_PROPERTY_LANGUAGE_DOC)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLanguageDoc(@javax.annotation.Nonnull String languageDoc) {
    this.languageDoc = languageDoc;
  }

  public SignatureRequestWithSignBlockList languageUI(@javax.annotation.Nonnull String languageUI) {
    
    this.languageUI = languageUI;
    return this;
  }

  /**
   * Idioma de la interficie d&#39;usuari (es o ca)
   * @return languageUI
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_LANGUAGE_U_I)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getLanguageUI() {
    return languageUI;
  }


  @JsonProperty(JSON_PROPERTY_LANGUAGE_U_I)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLanguageUI(@javax.annotation.Nonnull String languageUI) {
    this.languageUI = languageUI;
  }

  public SignatureRequestWithSignBlockList priority(@javax.annotation.Nonnull Integer priority) {
    
    this.priority = priority;
    return this;
  }

  /**
   * Prioritat de la Petició. Veure enumeració PriorityConstants.
   * @return priority
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_PRIORITY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getPriority() {
    return priority;
  }


  @JsonProperty(JSON_PROPERTY_PRIORITY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPriority(@javax.annotation.Nonnull Integer priority) {
    this.priority = priority;
  }

  public SignatureRequestWithSignBlockList senderName(@javax.annotation.Nonnull String senderName) {
    
    this.senderName = senderName;
    return this;
  }

  /**
   * Nom de la persona/aplicació que envia la petició.
   * @return senderName
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SENDER_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getSenderName() {
    return senderName;
  }


  @JsonProperty(JSON_PROPERTY_SENDER_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSenderName(@javax.annotation.Nonnull String senderName) {
    this.senderName = senderName;
  }

  public SignatureRequestWithSignBlockList expirationDate(@javax.annotation.Nullable OffsetDateTime expirationDate) {
    
    this.expirationDate = expirationDate;
    return this;
  }

  /**
   * Data en que caducarà aquesta petició de firma. Si la data es inferior a 3 dies a partir de la data d&#39;avui, llavors es posa 1 mes a partir d&#39;avui. Si val null automàticament es posa a 30 dies a partir de la creació de la petició.
   * @return expirationDate
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EXPIRATION_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getExpirationDate() {
    return expirationDate;
  }


  @JsonProperty(JSON_PROPERTY_EXPIRATION_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExpirationDate(@javax.annotation.Nullable OffsetDateTime expirationDate) {
    this.expirationDate = expirationDate;
  }

  public SignatureRequestWithSignBlockList requiresTimeStampInSignature(@javax.annotation.Nullable Boolean requiresTimeStampInSignature) {
    
    this.requiresTimeStampInSignature = requiresTimeStampInSignature;
    return this;
  }

  /**
   * Indica si es requereix que la firma tingui un segell de temps associat. També depen de la politica de Segellat de Temps de l&#39;usuari aplicació. Només es farà cas d&#39;aquest camp si les politiques són POLITICA_DE_SEGELLAT_DE_TEMPS_USUARI_ELEGEIX_PER_DEFECTE_SI o POLITICA_DE_SEGELLAT_DE_TEMPS_USUARI_ELEGEIX_PER_DEFECTE_NO. En el cas de que la politica sigui diferent a les dues anteriors i aquest camp es defineixi, llavors es llançarà un error.
   * @return requiresTimeStampInSignature
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REQUIRES_TIME_STAMP_IN_SIGNATURE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getRequiresTimeStampInSignature() {
    return requiresTimeStampInSignature;
  }


  @JsonProperty(JSON_PROPERTY_REQUIRES_TIME_STAMP_IN_SIGNATURE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRequiresTimeStampInSignature(@javax.annotation.Nullable Boolean requiresTimeStampInSignature) {
    this.requiresTimeStampInSignature = requiresTimeStampInSignature;
  }

  public SignatureRequestWithSignBlockList senderDescription(@javax.annotation.Nullable String senderDescription) {
    
    this.senderDescription = senderDescription;
    return this;
  }

  /**
   * Descripció de la persona o responsable de l&#39;aplicació que envia la petició. Es sol posar el correu electronic de la persona que que envia la petició.
   * @return senderDescription
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SENDER_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSenderDescription() {
    return senderDescription;
  }


  @JsonProperty(JSON_PROPERTY_SENDER_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSenderDescription(@javax.annotation.Nullable String senderDescription) {
    this.senderDescription = senderDescription;
  }

  public SignatureRequestWithSignBlockList expedientCode(@javax.annotation.Nullable String expedientCode) {
    
    this.expedientCode = expedientCode;
    return this;
  }

  /**
   * Codi de l&#39;expedient
   * @return expedientCode
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EXPEDIENT_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getExpedientCode() {
    return expedientCode;
  }


  @JsonProperty(JSON_PROPERTY_EXPEDIENT_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExpedientCode(@javax.annotation.Nullable String expedientCode) {
    this.expedientCode = expedientCode;
  }

  public SignatureRequestWithSignBlockList expedientName(@javax.annotation.Nullable String expedientName) {
    
    this.expedientName = expedientName;
    return this;
  }

  /**
   * Nom de l&#39;expedient
   * @return expedientName
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EXPEDIENT_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getExpedientName() {
    return expedientName;
  }


  @JsonProperty(JSON_PROPERTY_EXPEDIENT_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExpedientName(@javax.annotation.Nullable String expedientName) {
    this.expedientName = expedientName;
  }

  public SignatureRequestWithSignBlockList expedientUrl(@javax.annotation.Nullable String expedientUrl) {
    
    this.expedientUrl = expedientUrl;
    return this;
  }

  /**
   * URL de l&#39;expedient
   * @return expedientUrl
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EXPEDIENT_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getExpedientUrl() {
    return expedientUrl;
  }


  @JsonProperty(JSON_PROPERTY_EXPEDIENT_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExpedientUrl(@javax.annotation.Nullable String expedientUrl) {
    this.expedientUrl = expedientUrl;
  }

  public SignatureRequestWithSignBlockList procedureCode(@javax.annotation.Nullable String procedureCode) {
    
    this.procedureCode = procedureCode;
    return this;
  }

  /**
   * Codi del Procediment 
   * @return procedureCode
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PROCEDURE_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getProcedureCode() {
    return procedureCode;
  }


  @JsonProperty(JSON_PROPERTY_PROCEDURE_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProcedureCode(@javax.annotation.Nullable String procedureCode) {
    this.procedureCode = procedureCode;
  }

  public SignatureRequestWithSignBlockList procedureName(@javax.annotation.Nullable String procedureName) {
    
    this.procedureName = procedureName;
    return this;
  }

  /**
   * Nom del Procediment
   * @return procedureName
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PROCEDURE_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getProcedureName() {
    return procedureName;
  }


  @JsonProperty(JSON_PROPERTY_PROCEDURE_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProcedureName(@javax.annotation.Nullable String procedureName) {
    this.procedureName = procedureName;
  }

  public SignatureRequestWithSignBlockList additionalInformation(@javax.annotation.Nullable String additionalInformation) {
    
    this.additionalInformation = additionalInformation;
    return this;
  }

  /**
   * Informació Addicional
   * @return additionalInformation
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ADDITIONAL_INFORMATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAdditionalInformation() {
    return additionalInformation;
  }


  @JsonProperty(JSON_PROPERTY_ADDITIONAL_INFORMATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAdditionalInformation(@javax.annotation.Nullable String additionalInformation) {
    this.additionalInformation = additionalInformation;
  }

  public SignatureRequestWithSignBlockList additionalInformationEvaluable(@javax.annotation.Nullable Double additionalInformationEvaluable) {
    
    this.additionalInformationEvaluable = additionalInformationEvaluable;
    return this;
  }

  /**
   * Informació Addicional avauluable. Per exemple en documents de tipus factura en aquest camp s&#39;insereix la quantitat final de la factura.
   * @return additionalInformationEvaluable
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ADDITIONAL_INFORMATION_EVALUABLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getAdditionalInformationEvaluable() {
    return additionalInformationEvaluable;
  }


  @JsonProperty(JSON_PROPERTY_ADDITIONAL_INFORMATION_EVALUABLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAdditionalInformationEvaluable(@javax.annotation.Nullable Double additionalInformationEvaluable) {
    this.additionalInformationEvaluable = additionalInformationEvaluable;
  }

  public SignatureRequestWithSignBlockList annexs(@javax.annotation.Nullable List<Annex> annexs) {
    
    this.annexs = annexs;
    return this;
  }

  public SignatureRequestWithSignBlockList addAnnexsItem(Annex annexsItem) {
    if (this.annexs == null) {
      this.annexs = new ArrayList<>();
    }
    this.annexs.add(annexsItem);
    return this;
  }

  /**
   * Llista de document annexes a la petició de firma
   * @return annexs
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ANNEXS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Annex> getAnnexs() {
    return annexs;
  }


  @JsonProperty(JSON_PROPERTY_ANNEXS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAnnexs(@javax.annotation.Nullable List<Annex> annexs) {
    this.annexs = annexs;
  }

  public SignatureRequestWithSignBlockList metadadaList(@javax.annotation.Nullable List<Metadata> metadadaList) {
    
    this.metadadaList = metadadaList;
    return this;
  }

  public SignatureRequestWithSignBlockList addMetadadaListItem(Metadata metadadaListItem) {
    if (this.metadadaList == null) {
      this.metadadaList = new ArrayList<>();
    }
    this.metadadaList.add(metadadaListItem);
    return this;
  }

  /**
   * Llista de Metadades associades a la Petició de Firma
   * @return metadadaList
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_METADADA_LIST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Metadata> getMetadadaList() {
    return metadadaList;
  }


  @JsonProperty(JSON_PROPERTY_METADADA_LIST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMetadadaList(@javax.annotation.Nullable List<Metadata> metadadaList) {
    this.metadadaList = metadadaList;
  }

  public SignatureRequestWithSignBlockList signatureBlocks(@javax.annotation.Nonnull List<SignatureBlock> signatureBlocks) {
    
    this.signatureBlocks = signatureBlocks;
    return this;
  }

  public SignatureRequestWithSignBlockList addSignatureBlocksItem(SignatureBlock signatureBlocksItem) {
    if (this.signatureBlocks == null) {
      this.signatureBlocks = new ArrayList<>();
    }
    this.signatureBlocks.add(signatureBlocksItem);
    return this;
  }

  /**
   * Estructura del Flux de Firmes, és a dir, dels destinataris que han de signar el document.
   * @return signatureBlocks
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SIGNATURE_BLOCKS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<SignatureBlock> getSignatureBlocks() {
    return signatureBlocks;
  }


  @JsonProperty(JSON_PROPERTY_SIGNATURE_BLOCKS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSignatureBlocks(@javax.annotation.Nonnull List<SignatureBlock> signatureBlocks) {
    this.signatureBlocks = signatureBlocks;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SignatureRequestWithSignBlockList signatureRequestWithSignBlockList = (SignatureRequestWithSignBlockList) o;
    return Objects.equals(this.profileCode, signatureRequestWithSignBlockList.profileCode) &&
        Objects.equals(this.fileToSign, signatureRequestWithSignBlockList.fileToSign) &&
        Objects.equals(this.originalDetachedSignature, signatureRequestWithSignBlockList.originalDetachedSignature) &&
        Objects.equals(this.title, signatureRequestWithSignBlockList.title) &&
        Objects.equals(this.description, signatureRequestWithSignBlockList.description) &&
        Objects.equals(this.reason, signatureRequestWithSignBlockList.reason) &&
        Objects.equals(this.documentType, signatureRequestWithSignBlockList.documentType) &&
        Objects.equals(this.documentTypeDescription, signatureRequestWithSignBlockList.documentTypeDescription) &&
        Objects.equals(this.languageDoc, signatureRequestWithSignBlockList.languageDoc) &&
        Objects.equals(this.languageUI, signatureRequestWithSignBlockList.languageUI) &&
        Objects.equals(this.priority, signatureRequestWithSignBlockList.priority) &&
        Objects.equals(this.senderName, signatureRequestWithSignBlockList.senderName) &&
        Objects.equals(this.expirationDate, signatureRequestWithSignBlockList.expirationDate) &&
        Objects.equals(this.requiresTimeStampInSignature, signatureRequestWithSignBlockList.requiresTimeStampInSignature) &&
        Objects.equals(this.senderDescription, signatureRequestWithSignBlockList.senderDescription) &&
        Objects.equals(this.expedientCode, signatureRequestWithSignBlockList.expedientCode) &&
        Objects.equals(this.expedientName, signatureRequestWithSignBlockList.expedientName) &&
        Objects.equals(this.expedientUrl, signatureRequestWithSignBlockList.expedientUrl) &&
        Objects.equals(this.procedureCode, signatureRequestWithSignBlockList.procedureCode) &&
        Objects.equals(this.procedureName, signatureRequestWithSignBlockList.procedureName) &&
        Objects.equals(this.additionalInformation, signatureRequestWithSignBlockList.additionalInformation) &&
        Objects.equals(this.additionalInformationEvaluable, signatureRequestWithSignBlockList.additionalInformationEvaluable) &&
        Objects.equals(this.annexs, signatureRequestWithSignBlockList.annexs) &&
        Objects.equals(this.metadadaList, signatureRequestWithSignBlockList.metadadaList) &&
        Objects.equals(this.signatureBlocks, signatureRequestWithSignBlockList.signatureBlocks);
  }

  @Override
  public int hashCode() {
    return Objects.hash(profileCode, fileToSign, originalDetachedSignature, title, description, reason, documentType, documentTypeDescription, languageDoc, languageUI, priority, senderName, expirationDate, requiresTimeStampInSignature, senderDescription, expedientCode, expedientName, expedientUrl, procedureCode, procedureName, additionalInformation, additionalInformationEvaluable, annexs, metadadaList, signatureBlocks);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SignatureRequestWithSignBlockList {\n");
    sb.append("    profileCode: ").append(toIndentedString(profileCode)).append("\n");
    sb.append("    fileToSign: ").append(toIndentedString(fileToSign)).append("\n");
    sb.append("    originalDetachedSignature: ").append(toIndentedString(originalDetachedSignature)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    reason: ").append(toIndentedString(reason)).append("\n");
    sb.append("    documentType: ").append(toIndentedString(documentType)).append("\n");
    sb.append("    documentTypeDescription: ").append(toIndentedString(documentTypeDescription)).append("\n");
    sb.append("    languageDoc: ").append(toIndentedString(languageDoc)).append("\n");
    sb.append("    languageUI: ").append(toIndentedString(languageUI)).append("\n");
    sb.append("    priority: ").append(toIndentedString(priority)).append("\n");
    sb.append("    senderName: ").append(toIndentedString(senderName)).append("\n");
    sb.append("    expirationDate: ").append(toIndentedString(expirationDate)).append("\n");
    sb.append("    requiresTimeStampInSignature: ").append(toIndentedString(requiresTimeStampInSignature)).append("\n");
    sb.append("    senderDescription: ").append(toIndentedString(senderDescription)).append("\n");
    sb.append("    expedientCode: ").append(toIndentedString(expedientCode)).append("\n");
    sb.append("    expedientName: ").append(toIndentedString(expedientName)).append("\n");
    sb.append("    expedientUrl: ").append(toIndentedString(expedientUrl)).append("\n");
    sb.append("    procedureCode: ").append(toIndentedString(procedureCode)).append("\n");
    sb.append("    procedureName: ").append(toIndentedString(procedureName)).append("\n");
    sb.append("    additionalInformation: ").append(toIndentedString(additionalInformation)).append("\n");
    sb.append("    additionalInformationEvaluable: ").append(toIndentedString(additionalInformationEvaluable)).append("\n");
    sb.append("    annexs: ").append(toIndentedString(annexs)).append("\n");
    sb.append("    metadadaList: ").append(toIndentedString(metadadaList)).append("\n");
    sb.append("    signatureBlocks: ").append(toIndentedString(signatureBlocks)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

