/*
 * API Interna de PortaFIB que ofereix serveis associats amb la firma digital
 * Conjunt de Serveis REST de PortaFIB per atendre peticions de firma en servidor, firma web síncrona, firma web asíncrona, validació de firma i plantilla de flux de firma.
 *
 * The version of the OpenAPI document: 1.0-SNAPSHOT
 * Contact: firma@fundaciobit.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package es.caib.portafib.apiinterna.client.signature.v1.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import es.caib.portafib.apiinterna.client.signature.v1.model.ProcessStatus;
import es.caib.portafib.apiinterna.client.signature.v1.model.SignPlugin;
import es.caib.portafib.apiinterna.client.signature.v1.model.SignatureStatus;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * informació de l&#39;estat d&#39;una Transaccio de tipus Firma Web Directe
 */
@JsonPropertyOrder({
  TransactionStatusResponse.JSON_PROPERTY_TRANSACTION_STATUS,
  TransactionStatusResponse.JSON_PROPERTY_SIGNATURES_STATUS_LIST,
  TransactionStatusResponse.JSON_PROPERTY_SIGN_PLUGIN
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class TransactionStatusResponse {
  public static final String JSON_PROPERTY_TRANSACTION_STATUS = "transactionStatus";
  @javax.annotation.Nonnull
  private ProcessStatus transactionStatus;

  public static final String JSON_PROPERTY_SIGNATURES_STATUS_LIST = "signaturesStatusList";
  @javax.annotation.Nonnull
  private List<SignatureStatus> signaturesStatusList = new ArrayList<>();

  public static final String JSON_PROPERTY_SIGN_PLUGIN = "signPlugin";
  @javax.annotation.Nullable
  private SignPlugin signPlugin;

  public TransactionStatusResponse() {
  }

  public TransactionStatusResponse transactionStatus(@javax.annotation.Nonnull ProcessStatus transactionStatus) {
    
    this.transactionStatus = transactionStatus;
    return this;
  }

  /**
   * Get transactionStatus
   * @return transactionStatus
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TRANSACTION_STATUS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public ProcessStatus getTransactionStatus() {
    return transactionStatus;
  }


  @JsonProperty(JSON_PROPERTY_TRANSACTION_STATUS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTransactionStatus(@javax.annotation.Nonnull ProcessStatus transactionStatus) {
    this.transactionStatus = transactionStatus;
  }

  public TransactionStatusResponse signaturesStatusList(@javax.annotation.Nonnull List<SignatureStatus> signaturesStatusList) {
    
    this.signaturesStatusList = signaturesStatusList;
    return this;
  }

  public TransactionStatusResponse addSignaturesStatusListItem(SignatureStatus signaturesStatusListItem) {
    if (this.signaturesStatusList == null) {
      this.signaturesStatusList = new ArrayList<>();
    }
    this.signaturesStatusList.add(signaturesStatusListItem);
    return this;
  }

  /**
   * Estat de cada firma. Pot passar que l&#39;estat general sigui que tot ha anat bé, però que totes o algunes de les firmes no.
   * @return signaturesStatusList
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SIGNATURES_STATUS_LIST)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<SignatureStatus> getSignaturesStatusList() {
    return signaturesStatusList;
  }


  @JsonProperty(JSON_PROPERTY_SIGNATURES_STATUS_LIST)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSignaturesStatusList(@javax.annotation.Nonnull List<SignatureStatus> signaturesStatusList) {
    this.signaturesStatusList = signaturesStatusList;
  }

  public TransactionStatusResponse signPlugin(@javax.annotation.Nullable SignPlugin signPlugin) {
    
    this.signPlugin = signPlugin;
    return this;
  }

  /**
   * Get signPlugin
   * @return signPlugin
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SIGN_PLUGIN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public SignPlugin getSignPlugin() {
    return signPlugin;
  }


  @JsonProperty(JSON_PROPERTY_SIGN_PLUGIN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSignPlugin(@javax.annotation.Nullable SignPlugin signPlugin) {
    this.signPlugin = signPlugin;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TransactionStatusResponse transactionStatusResponse = (TransactionStatusResponse) o;
    return Objects.equals(this.transactionStatus, transactionStatusResponse.transactionStatus) &&
        Objects.equals(this.signaturesStatusList, transactionStatusResponse.signaturesStatusList) &&
        Objects.equals(this.signPlugin, transactionStatusResponse.signPlugin);
  }

  @Override
  public int hashCode() {
    return Objects.hash(transactionStatus, signaturesStatusList, signPlugin);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TransactionStatusResponse {\n");
    sb.append("    transactionStatus: ").append(toIndentedString(transactionStatus)).append("\n");
    sb.append("    signaturesStatusList: ").append(toIndentedString(signaturesStatusList)).append("\n");
    sb.append("    signPlugin: ").append(toIndentedString(signPlugin)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

