/*
 * API Interna de PortaFIB que ofereix serveis de firma web.
 * Conjunt de Serveis REST de PortaFIB per atendre peticions de firma a través de web de PortaFIB
 *
 * The version of the OpenAPI document: 1.0-SNAPSHOT
 * Contact: otae@fundaciobit.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package es.caib.portafib.apiinterna.client.signature.v1.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ValidacioCompletaResponseCertificateLastSignIssuerX500Principal
 */
@JsonPropertyOrder({
  ValidacioCompletaResponseCertificateLastSignIssuerX500Principal.JSON_PROPERTY_NAME,
  ValidacioCompletaResponseCertificateLastSignIssuerX500Principal.JSON_PROPERTY_ENCODED
})
@JsonTypeName("ValidacioCompletaResponse_certificateLastSign_issuerX500Principal")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class ValidacioCompletaResponseCertificateLastSignIssuerX500Principal {
  public static final String JSON_PROPERTY_NAME = "name";
  @javax.annotation.Nullable
  private String name;

  public static final String JSON_PROPERTY_ENCODED = "encoded";
  @javax.annotation.Nullable
  private List<byte[]> encoded = new ArrayList<>();

  public ValidacioCompletaResponseCertificateLastSignIssuerX500Principal() {
  }

  public ValidacioCompletaResponseCertificateLastSignIssuerX500Principal name(@javax.annotation.Nullable String name) {
    
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(@javax.annotation.Nullable String name) {
    this.name = name;
  }

  public ValidacioCompletaResponseCertificateLastSignIssuerX500Principal encoded(@javax.annotation.Nullable List<byte[]> encoded) {
    
    this.encoded = encoded;
    return this;
  }

  public ValidacioCompletaResponseCertificateLastSignIssuerX500Principal addEncodedItem(byte[] encodedItem) {
    if (this.encoded == null) {
      this.encoded = new ArrayList<>();
    }
    this.encoded.add(encodedItem);
    return this;
  }

  /**
   * Get encoded
   * @return encoded
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ENCODED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<byte[]> getEncoded() {
    return encoded;
  }


  @JsonProperty(JSON_PROPERTY_ENCODED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEncoded(@javax.annotation.Nullable List<byte[]> encoded) {
    this.encoded = encoded;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ValidacioCompletaResponseCertificateLastSignIssuerX500Principal validacioCompletaResponseCertificateLastSignIssuerX500Principal = (ValidacioCompletaResponseCertificateLastSignIssuerX500Principal) o;
    return Objects.equals(this.name, validacioCompletaResponseCertificateLastSignIssuerX500Principal.name) &&
        Objects.equals(this.encoded, validacioCompletaResponseCertificateLastSignIssuerX500Principal.encoded);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, encoded);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ValidacioCompletaResponseCertificateLastSignIssuerX500Principal {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    encoded: ").append(toIndentedString(encoded)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

