
INSERT INTO pfi_traduccio(traduccioid) VALUES (-1);
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-1, 'es', 'Aprobación de comisión informática');
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-1, 'ca', 'Aprovació de comissió informàtica');
INSERT INTO pfi_traduccio(traduccioid) VALUES (-3);
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-3, 'es', 'Firma del servicio de seguridad de la DGTIC');
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-3, 'ca', 'Signatura del servei de seguretat de la DGTIC');
INSERT INTO pfi_traduccio(traduccioid) VALUES (-4);
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-4, 'es', 'Asiento registral');
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-4, 'ca', 'Assentament registral');
INSERT INTO pfi_traduccio(traduccioid) VALUES (-10);
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-10, 'es', 'Autorizaciones de licencias de juegos');
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-10, 'ca', 'Autoritzacions de llicències de jocs');
INSERT INTO pfi_traduccio(traduccioid) VALUES (-11);
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-11, 'es', 'Subsanación de autorizaciones de licencias de juegos');
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-11, 'ca', 'Esmena d''autoritzacions de llicències de jocs');
INSERT INTO pfi_traduccio(traduccioid) VALUES (-13);
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-13, 'es', 'Resoluciones de autorizaciones de licencias de juegos');
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-13, 'ca', 'Resolucions d''autoritzacions de llicències de jocs');
INSERT INTO pfi_traduccio(traduccioid) VALUES (-21);
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-21, 'es', 'Certificado FPP');
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-21, 'ca', 'Certificat FPP');
INSERT INTO pfi_traduccio(traduccioid) VALUES (-22);
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-22, 'es', 'Acta FPP actividades internas');
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-22, 'ca', 'Acta FPP activitats internes');
INSERT INTO pfi_traduccio(traduccioid) VALUES (-23);
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-23, 'es', 'Extracto de expediente personal');
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-23, 'ca', 'Extracte d''expedient personal');
INSERT INTO pfi_traduccio(traduccioid) VALUES (-24);
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-24, 'es', 'Certificado de servicios prestados');
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-24, 'ca', 'Certificat de serveis prestats');
INSERT INTO pfi_traduccio(traduccioid) VALUES (-26);
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-26, 'es', 'Certificado para comisión de servicios de caracter voluntario');
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-26, 'ca', 'Certificat per comissió de serveis de caràcter voluntari');
INSERT INTO pfi_traduccio(traduccioid) VALUES (-27);
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-27, 'es', 'Certificado de servicios previos');
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-27, 'ca', 'Certificat de serveis previs');
INSERT INTO pfi_traduccio(traduccioid) VALUES (-28);
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-28, 'es', 'Acta curso IBSALUT');
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-28, 'ca', 'Acta curs IBSALUT');
INSERT INTO pfi_traduccio(traduccioid) VALUES (-29);
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-29, 'es', 'Acta asistencia curso IBSALUT');
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-29, 'ca', 'Acta assistència curs IBSALUT');
INSERT INTO pfi_traduccio(traduccioid) VALUES (-30);
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-30, 'es', 'Certificado de cursos del EBAP');
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-30, 'ca', 'Certificat de cursos de l''EBAP');
INSERT INTO pfi_traduccio(traduccioid) VALUES (-31);
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-31, 'es', 'Diplomas cursos EBAP');
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-31, 'ca', 'Diplomes cursos EBAP');
INSERT INTO pfi_traduccio(traduccioid) VALUES (-50);
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-50, 'es', 'Notificación');
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-50, 'ca', 'Notificació');
INSERT INTO pfi_traduccio(traduccioid) VALUES (-51);
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-51, 'es', 'Oficio de notificación');
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-51, 'ca', 'Ofici de notificació');
INSERT INTO pfi_traduccio(traduccioid) VALUES (-52);
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-52, 'es', 'Anuncio publicación en catalán');
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-52, 'ca', 'Anunci publicació en català');
INSERT INTO pfi_traduccio(traduccioid) VALUES (-53);
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-53, 'es', 'Anuncio publicación en castellano');
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-53, 'ca', 'Anunci publicació en castellà');
INSERT INTO pfi_traduccio(traduccioid) VALUES (-54);
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-54, 'es', 'Anuncio edicto');
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-54, 'ca', 'Anunci edicte');
INSERT INTO pfi_traduccio(traduccioid) VALUES (-60);
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-60, 'es', 'Consejo de Gobierno: Órden del día');
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-60, 'ca', 'Consell de Govern: Ordre del dia');
INSERT INTO pfi_traduccio(traduccioid) VALUES (-61);
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-61, 'es', 'Consejo de Gobierno: Certificados');
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-61, 'ca', 'Consell de Govern: Certificats');
INSERT INTO pfi_traduccio(traduccioid) VALUES (-62);
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-62, 'es', 'Consejo de Gobierno: Órdenes del día (Comisiones de secretarios)');
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-62, 'ca', 'Consell de Govern: Ordres del dia (Comissions de secretaris)');
INSERT INTO pfi_traduccio(traduccioid) VALUES (-63);
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-63, 'es', 'Consejo de Gobierno: Actas');
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-63, 'ca', 'Consell de Govern: Actes');
INSERT INTO pfi_traduccio(traduccioid) VALUES (-64);
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-64, 'es', 'Consejo de Gobierno: Actas (Comisiones de secretarios)');
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-64, 'ca', 'Consell de Govern: Actes (Comissions de secretaris)');
INSERT INTO pfi_traduccio(traduccioid) VALUES (-65);
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-65, 'es', 'Consejo de gobierno: Decreto BOIB');
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-65, 'ca', 'Consell de govern: Decret BOIB');
INSERT INTO pfi_traduccio(traduccioid) VALUES (-66);
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-66, 'es', 'Consejo de Gobierno: Remisión decretos BOIB');
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-66, 'ca', 'Consell de Govern: Remissió decrets BOIB');
INSERT INTO pfi_traduccio(traduccioid) VALUES (-67);
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-67, 'es', 'Consejo de Gobierno: Acuerdo BOIB');
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-67, 'ca', 'Consell de Govern: Acord BOIB');
INSERT INTO pfi_traduccio(traduccioid) VALUES (-68);
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-68, 'es', 'Consejo de Gobierno: Envío acuerdo BOIB');
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-68, 'ca', 'Consell de Govern: Enviament acord BOIB');
INSERT INTO pfi_traduccio(traduccioid) VALUES (-69);
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-69, 'es', 'Consejo de Gobierno: Órden de publicación');
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-69, 'ca', 'Consell de Govern: Órden de publicació');
INSERT INTO pfi_traduccio(traduccioid) VALUES (-200);
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-200, 'es', 'Homologación de títulos de Catalán');
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-200, 'ca', 'Homologació de títols de Català');
INSERT INTO pfi_traduccio(traduccioid) VALUES (-201);
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-201, 'es', 'Exenciones de catalán');
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-201, 'ca', 'Exempcions de català');
INSERT INTO pfi_traduccio(traduccioid) VALUES (-202);
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-202, 'es', 'Equivalencias de nivel de Catalán');
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-202, 'ca', 'Equivalències de nivell de Català');
INSERT INTO pfi_traduccio(traduccioid) VALUES (-203);
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-203, 'es', 'Certificados de pruebas de Catalán');
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-203, 'ca', 'Certificats de proves de Català');
INSERT INTO pfi_traduccio(traduccioid) VALUES (-204);
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-204, 'es', 'Convalidaciones de asignaturas del Plan de Reciclaje y Formación Lingüística y Cultural');
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-204, 'ca', 'Convalidacions d’assignatures del Pla de Reciclatge i Formació Lingüística i Cultural');
INSERT INTO pfi_traduccio(traduccioid) VALUES (-205);
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-205, 'es', 'Títulos del FOLC');
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-205, 'ca', 'Títols del FOLC');
INSERT INTO pfi_traduccio(traduccioid) VALUES (-206);
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-206, 'es', 'Homologaciones denegadas');
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-206, 'ca', 'Homologacions denegades');
INSERT INTO pfi_traduccio(traduccioid) VALUES (-207);
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-207, 'es', 'Adjudicaciones de Transporte Escolar');
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-207, 'ca', 'Adjudicacions de Transport Escolar');
INSERT INTO pfi_traduccio(traduccioid) VALUES (-208);
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-208, 'es', 'Contratos de Transporte Escolar');
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-208, 'ca', 'Contractes de Transport Escolar');
INSERT INTO pfi_traduccio(traduccioid) VALUES (-301);
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-301, 'es', 'Actas');
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-301, 'ca', 'Actes');
INSERT INTO pfi_traduccio(traduccioid) VALUES (-302);
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-302, 'es', 'Dictámenes');
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-302, 'ca', 'Dictàmens');
INSERT INTO pfi_traduccio(traduccioid) VALUES (-303);
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-303, 'es', 'Oficios');
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-303, 'ca', 'Oficis');
INSERT INTO pfi_traduccio(traduccioid) VALUES (-305);
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-305, 'es', 'PINFO');
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-305, 'ca', 'Pinfo');
INSERT INTO pfi_traduccio(traduccioid) VALUES (-306);
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-306, 'es', 'Notas internas');
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-306, 'ca', 'Notes internes');
INSERT INTO pfi_traduccio(traduccioid) VALUES (-307);
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-307, 'es', 'Contratos');
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-307, 'ca', 'Contractes');
INSERT INTO pfi_traduccio(traduccioid) VALUES (-308);
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-308, 'es', 'Diligencias');
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-308, 'ca', 'Diligències');
INSERT INTO pfi_traduccio(traduccioid) VALUES (-309);
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-309, 'es', 'Informes');
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-309, 'ca', 'Informes');
INSERT INTO pfi_traduccio(traduccioid) VALUES (-310);
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-310, 'es', 'Carta');
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-310, 'ca', 'Carta');
INSERT INTO pfi_traduccio(traduccioid) VALUES (-311);
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-311, 'es', 'Certificado');
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-311, 'ca', 'Certificat');
INSERT INTO pfi_traduccio(traduccioid) VALUES (-312);
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-312, 'es', 'Resolución');
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-312, 'ca', 'Resolució');
INSERT INTO pfi_traduccio(traduccioid) VALUES (-313);
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-313, 'es', 'Propuestas');
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-313, 'ca', 'Propostes');
INSERT INTO pfi_traduccio(traduccioid) VALUES (-315);
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-315, 'es', 'Verificaciones del artículo 13 Reglamento (CE) 1828/2006');
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-315, 'ca', 'Verificacions de l''article 13 reglament (ce) 1828/2006');
INSERT INTO pfi_traduccio(traduccioid) VALUES (-316);
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-316, 'es', 'Homologaciones de estudios reglados');
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-316, 'ca', 'Homologacions d''estudis reglats');
INSERT INTO pfi_traduccio(traduccioid) VALUES (-317);
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-317, 'es', 'Subvenciones arquitectura / vivienda');
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-317, 'ca', 'Subvencions arquitectura / habitatge');
INSERT INTO pfi_traduccio(traduccioid) VALUES (-318);
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-318, 'es', 'Firma del Vicepresidente del FOGAIBA');
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-318, 'ca', 'Firma del Vicepresident del FOGAIBA');
INSERT INTO pfi_traduccio(traduccioid) VALUES (-319);
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-319, 'es', 'Firma del Jefe de servicio técnico y Director General');
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-319, 'ca', 'Firma del Cap de servei tècnic i Director General');
INSERT INTO pfi_traduccio(traduccioid) VALUES (-320);
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-320, 'es', 'Firma del Jefe de departamento de gestión y Director General');
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-320, 'ca', 'Firma del Cap de departament de gestió i Director General');
INSERT INTO pfi_traduccio(traduccioid) VALUES (-321);
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-321, 'es', 'Convocatorias');
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-321, 'ca', 'Convocatòries');
INSERT INTO pfi_traduccio(traduccioid) VALUES (-322);
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-322, 'es', 'Túnel de Sóller');
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-322, 'ca', 'Túnel de Sóller');
INSERT INTO pfi_traduccio(traduccioid) VALUES (-601);
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-601, 'es', 'Cartas de requerimiento');
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-601, 'ca', 'Cartes de requeriment');
INSERT INTO pfi_traduccio(traduccioid) VALUES (-602);
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-602, 'es', 'Cartas de citación');
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-602, 'ca', 'Cartes de citació');
INSERT INTO pfi_traduccio(traduccioid) VALUES (-603);
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-603, 'es', 'Dictámenes técnicos / administrativos');
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-603, 'ca', 'Dictàmens tècnics / administratius');
INSERT INTO pfi_traduccio(traduccioid) VALUES (-604);
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-604, 'es', 'Resoluciones');
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-604, 'ca', 'Resolucions');
INSERT INTO pfi_traduccio(traduccioid) VALUES (-605);
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-605, 'es', 'Certificados/Informes');
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-605, 'ca', 'Certificats/Informes');
INSERT INTO pfi_traduccio(traduccioid) VALUES (-606);
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-606, 'es', 'Oficio remissión a consejería iniciativa parlamentaria');
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-606, 'ca', 'Ofici remissión a conselleria iniciativa parlamentària');
INSERT INTO pfi_traduccio(traduccioid) VALUES (-607);
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-607, 'es', 'Respuesta oficio remisión a consejería iniciativa parlamentaria');
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-607, 'ca', 'Resposta ofici remissió a conselleria iniciativa parlamentària');
INSERT INTO pfi_traduccio(traduccioid) VALUES (-608);
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-608, 'es', 'Oficio de remisión al Parlamento de la respuesta');
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-608, 'ca', 'Ofici de remissió al Parlament de la resposta');
INSERT INTO pfi_traduccio(traduccioid) VALUES (-609);
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-609, 'es', 'Oficio de remisión certificado aprovación moción');
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-609, 'ca', 'Ofici de remissió certificat aprovació moció');
INSERT INTO pfi_traduccio(traduccioid) VALUES (-610);
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-610, 'es', 'Oficio remisión de la iniciativa parlamentaria al Parlamento');
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-610, 'ca', 'Ofici remissió de la iniciativa parlamentària al Parlament');
INSERT INTO pfi_traduccio(traduccioid) VALUES (-611);
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-611, 'es', 'Oficio de remisión a consejería informe omnicomprensivo');
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-611, 'ca', 'Ofici de remissió a conselleria informe omnicomprensiu');
INSERT INTO pfi_traduccio(traduccioid) VALUES (-612);
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-612, 'es', 'Oficio de remisión de la iniciativa al Parlamento');
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-612, 'ca', 'Ofici de remissió de la iniciativa al Parlament');
INSERT INTO pfi_traduccio(traduccioid) VALUES (-613);
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-613, 'es', 'Oficio de remisión deficiencias formales');
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-613, 'ca', 'Ofici de remissió deficiències formals');
INSERT INTO pfi_traduccio(traduccioid) VALUES (-614);
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-614, 'es', 'Oficio de remisión al Parlamento documentación enmienda');
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-614, 'ca', 'Ofici de remissió al Parlament documentació esmena');
INSERT INTO pfi_traduccio(traduccioid) VALUES (-615);
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-615, 'es', 'Oficio de remisión al Parlamento publicación BOIB');
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-615, 'ca', 'Ofici de remisión al Parlament publicació BOIB');
INSERT INTO pfi_traduccio(traduccioid) VALUES (-616);
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-616, 'es', 'Oficio remisión a consejería enmienda de devolución');
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-616, 'ca', 'Ofici remissió a conselleria esmena de devolució');
INSERT INTO pfi_traduccio(traduccioid) VALUES (-617);
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-617, 'es', 'Oficio remisión a consejería enmienda de substitución');
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-617, 'ca', 'Ofici remissió a conselleria esmena de substitució');
INSERT INTO pfi_traduccio(traduccioid) VALUES (-618);
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-618, 'es', 'Oficio de remisión a consejería afectada enmienda incid presupuestaria');
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-618, 'ca', 'Ofici de remissió a conselleria afectada esmena incid pressupostària');
INSERT INTO pfi_traduccio(traduccioid) VALUES (-619);
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-619, 'es', 'Oficio de remisión a vicepresidencia económica enmienda incid presupuestaria');
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-619, 'ca', 'Ofici de remissió a vicepresidència econòmica esmena incid pressupostària');
INSERT INTO pfi_traduccio(traduccioid) VALUES (-620);
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-620, 'es', 'Oficio remisión al Parlamento certificado Consejo de Gobierno (enmienda presupuestaria)');
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-620, 'ca', 'Ofici remissió al Parlament certificat Consell de Govern (esmena pressupostària)');
INSERT INTO pfi_traduccio(traduccioid) VALUES (-621);
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-621, 'es', 'Oficio de remisión al Parlamento certificado aprobación retirada proyecto de ley');
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-621, 'ca', 'Ofici de remissió al Parlament certificat aprovació retirada projecte de llei');
INSERT INTO pfi_traduccio(traduccioid) VALUES (-622);
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-622, 'es', 'Oficio de remisión al Parlamento Certificado acuerdo Consejo de Gobierno');
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-622, 'ca', 'Ofici de remissió al Parlament Certificat acord Consell de Govern');
INSERT INTO pfi_traduccio(traduccioid) VALUES (-623);
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-623, 'es', 'Oficio de remisión al Parlamento del decreto ley');
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-623, 'ca', 'Ofici de remissió al Parlament del decret llei');
INSERT INTO pfi_traduccio(traduccioid) VALUES (-624);
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-624, 'es', 'Oficio de remisión al Parlamento iniciativa parlamentaria');
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-624, 'ca', 'Ofici de remissió al Parlament iniciativa parlamentària');
INSERT INTO pfi_traduccio(traduccioid) VALUES (-625);
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-625, 'es', 'Oficio de remisión a consejería certificado aprovación propuesta');
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-625, 'ca', 'Ofici de remissió a conselleria certificat aprovació proposta');
INSERT INTO pfi_traduccio(traduccioid) VALUES (-626);
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-626, 'es', 'Resolución de desistimiento');
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-626, 'ca', 'Resolució de dessistiment');
INSERT INTO pfi_traduccio(traduccioid) VALUES (-627);
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-627, 'es', 'Petición de documentación');
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-627, 'ca', 'Petició de documentació');
INSERT INTO pfi_traduccio(traduccioid) VALUES (-628);
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-628, 'es', 'Resolución de concesión');
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-628, 'ca', 'Resolució de concessió');
INSERT INTO pfi_traduccio(traduccioid) VALUES (-629);
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-629, 'es', 'Resolución de denegación');
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-629, 'ca', 'Resolució de denegació');
INSERT INTO pfi_traduccio(traduccioid) VALUES (-630);
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-630, 'es', 'Preceptiva autorización de la resolución para la publicación de un trámite telemático');
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-630, 'ca', 'Autorització preceptiva de la resolució per a la publicació d''un tràmit telemàtic');
INSERT INTO pfi_traduccio(traduccioid) VALUES (-634);
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-634, 'es', 'Boletín de situación');
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-634, 'ca', 'Butlletí de situació');
INSERT INTO pfi_traduccio(traduccioid) VALUES (-635);
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-635, 'es', 'Solicitud informe ECA');
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-635, 'ca', 'Sol.licitud informe ECA');
INSERT INTO pfi_traduccio(traduccioid) VALUES (-636);
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-636, 'es', 'Notificación al contribuyente de la propuesta de liquidación');
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-636, 'ca', 'Notificació al contribuent de la proposta de liquidació');
INSERT INTO pfi_traduccio(traduccioid) VALUES (-637);
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-637, 'es', 'Notificación provisional al contribuyente de la propuesta de liquidación');
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-637, 'ca', 'Notificació provisional al contribuent de la proposta de liquidació');
INSERT INTO pfi_traduccio(traduccioid) VALUES (-638);
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-638, 'es', 'Comunicaciones a empreses');
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-638, 'ca', 'Comunicacions a empreses');
INSERT INTO pfi_traduccio(traduccioid) VALUES (-999);
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-999, 'es', 'Otros');
INSERT INTO pfi_traducciomap(traducciomapid, idiomaid, valor) VALUES (-999, 'ca', 'Altres');



INSERT INTO pfi_tipusdocument (tipusdocumentid, descripcio, nom, usuariaplicacioid) VALUES (-1, 'Aprovació de comissió informàtica', -1, NULL);
INSERT INTO pfi_tipusdocument (tipusdocumentid, descripcio, nom, usuariaplicacioid) VALUES (-3, 'Signatura del servei de seguretat de la DGTIC', -3, NULL);
INSERT INTO pfi_tipusdocument (tipusdocumentid, descripcio, nom, usuariaplicacioid) VALUES (-4, 'Assentament registral', -4, NULL);
INSERT INTO pfi_tipusdocument (tipusdocumentid, descripcio, nom, usuariaplicacioid) VALUES (-10, 'Autoritzacions de llicències de jocs', -10, NULL);
INSERT INTO pfi_tipusdocument (tipusdocumentid, descripcio, nom, usuariaplicacioid) VALUES (-11, 'Esmena d''autoritzacions de llicències de jocs', -11, NULL);
INSERT INTO pfi_tipusdocument (tipusdocumentid, descripcio, nom, usuariaplicacioid) VALUES (-13, 'Resolucions d''autoritzacions de llicències de jocs', -13, NULL);
INSERT INTO pfi_tipusdocument (tipusdocumentid, descripcio, nom, usuariaplicacioid) VALUES (-21, 'certificat FPP', -21, NULL);
INSERT INTO pfi_tipusdocument (tipusdocumentid, descripcio, nom, usuariaplicacioid) VALUES (-22, 'Acta FPP activitats internes', -22, NULL);
INSERT INTO pfi_tipusdocument (tipusdocumentid, descripcio, nom, usuariaplicacioid) VALUES (-23, 'Extracte d''expedient personal', -23, NULL);
INSERT INTO pfi_tipusdocument (tipusdocumentid, descripcio, nom, usuariaplicacioid) VALUES (-24, 'Certificat de serveis prestats', -24, NULL);
INSERT INTO pfi_tipusdocument (tipusdocumentid, descripcio, nom, usuariaplicacioid) VALUES (-26, 'Certificat per comissió de serveis de caràcter voluntari', -26, NULL);
INSERT INTO pfi_tipusdocument (tipusdocumentid, descripcio, nom, usuariaplicacioid) VALUES (-27, 'Certificat de serveis previs', -27, NULL);
INSERT INTO pfi_tipusdocument (tipusdocumentid, descripcio, nom, usuariaplicacioid) VALUES (-28, 'Acta curs IBSALUT', -28, NULL);
INSERT INTO pfi_tipusdocument (tipusdocumentid, descripcio, nom, usuariaplicacioid) VALUES (-29, 'Acta assistència curs IBSALUT', -29, NULL);
INSERT INTO pfi_tipusdocument (tipusdocumentid, descripcio, nom, usuariaplicacioid) VALUES (-30, 'Certificat de cursos de l''EBAP', -30, NULL);
INSERT INTO pfi_tipusdocument (tipusdocumentid, descripcio, nom, usuariaplicacioid) VALUES (-31, 'Diplomes cursos EBAP', -31, NULL);
INSERT INTO pfi_tipusdocument (tipusdocumentid, descripcio, nom, usuariaplicacioid) VALUES (-50, 'Notificació', -50, NULL);
INSERT INTO pfi_tipusdocument (tipusdocumentid, descripcio, nom, usuariaplicacioid) VALUES (-51, 'Ofici de notificació', -51, NULL);
INSERT INTO pfi_tipusdocument (tipusdocumentid, descripcio, nom, usuariaplicacioid) VALUES (-52, 'Anunci publicació en català', -52, NULL);
INSERT INTO pfi_tipusdocument (tipusdocumentid, descripcio, nom, usuariaplicacioid) VALUES (-53, 'Anunci publicació en castellà', -53, NULL);
INSERT INTO pfi_tipusdocument (tipusdocumentid, descripcio, nom, usuariaplicacioid) VALUES (-54, 'anunci edicte', -54, NULL);
INSERT INTO pfi_tipusdocument (tipusdocumentid, descripcio, nom, usuariaplicacioid) VALUES (-60, 'Consell de Govern: Ordre del dia', -60, NULL);
INSERT INTO pfi_tipusdocument (tipusdocumentid, descripcio, nom, usuariaplicacioid) VALUES (-61, 'Consell de Govern: Certificats', -61, NULL);
INSERT INTO pfi_tipusdocument (tipusdocumentid, descripcio, nom, usuariaplicacioid) VALUES (-62, 'Consell de Govern: Ordres del dia (Comissions de secretaris)', -62, NULL);
INSERT INTO pfi_tipusdocument (tipusdocumentid, descripcio, nom, usuariaplicacioid) VALUES (-63, 'Consell de Govern: Actes', -63, NULL);
INSERT INTO pfi_tipusdocument (tipusdocumentid, descripcio, nom, usuariaplicacioid) VALUES (-64, 'Consell de Govern: Actes (Comissions de secretaris)', -64, NULL);
INSERT INTO pfi_tipusdocument (tipusdocumentid, descripcio, nom, usuariaplicacioid) VALUES (-65, 'Consell de govern: Decret BOIB', -65, NULL);
INSERT INTO pfi_tipusdocument (tipusdocumentid, descripcio, nom, usuariaplicacioid) VALUES (-66, 'Consell de Govern: Remissió decrets BOIB', -66, NULL);
INSERT INTO pfi_tipusdocument (tipusdocumentid, descripcio, nom, usuariaplicacioid) VALUES (-67, 'Consell de Govern: Acord BOIB', -67, NULL);
INSERT INTO pfi_tipusdocument (tipusdocumentid, descripcio, nom, usuariaplicacioid) VALUES (-68, 'Consell de Govern: Enviament acord BOIB', -68, NULL);
INSERT INTO pfi_tipusdocument (tipusdocumentid, descripcio, nom, usuariaplicacioid) VALUES (-69, 'Consell de Govern: Órden de publicació', -69, NULL);
INSERT INTO pfi_tipusdocument (tipusdocumentid, descripcio, nom, usuariaplicacioid) VALUES (-200, 'Homologació de títols de Català', -200, NULL);
INSERT INTO pfi_tipusdocument (tipusdocumentid, descripcio, nom, usuariaplicacioid) VALUES (-201, 'Exempcions de català', -201, NULL);
INSERT INTO pfi_tipusdocument (tipusdocumentid, descripcio, nom, usuariaplicacioid) VALUES (-202, 'Equivalències de nivell de Català', -202, NULL);
INSERT INTO pfi_tipusdocument (tipusdocumentid, descripcio, nom, usuariaplicacioid) VALUES (-203, 'Certificats de proves de Català', -203, NULL);
INSERT INTO pfi_tipusdocument (tipusdocumentid, descripcio, nom, usuariaplicacioid) VALUES (-204, 'Convalidacions d’assignatures del Pla de Reciclatge i Formació Lingüística i Cultural', -204, NULL);
INSERT INTO pfi_tipusdocument (tipusdocumentid, descripcio, nom, usuariaplicacioid) VALUES (-205, 'Títols del FOLC', -205, NULL);
INSERT INTO pfi_tipusdocument (tipusdocumentid, descripcio, nom, usuariaplicacioid) VALUES (-206, 'Homologacions denegades', -206, NULL);
INSERT INTO pfi_tipusdocument (tipusdocumentid, descripcio, nom, usuariaplicacioid) VALUES (-207, 'Adjudicacions de Transport Escolar', -207, NULL);
INSERT INTO pfi_tipusdocument (tipusdocumentid, descripcio, nom, usuariaplicacioid) VALUES (-208, 'Contractes de Transport Escolar', -208, NULL);
INSERT INTO pfi_tipusdocument (tipusdocumentid, descripcio, nom, usuariaplicacioid) VALUES (-301, 'Actes', -301, NULL);
INSERT INTO pfi_tipusdocument (tipusdocumentid, descripcio, nom, usuariaplicacioid) VALUES (-302, 'Dictàmens', -302, NULL);
INSERT INTO pfi_tipusdocument (tipusdocumentid, descripcio, nom, usuariaplicacioid) VALUES (-303, 'Oficis', -303, NULL);
INSERT INTO pfi_tipusdocument (tipusdocumentid, descripcio, nom, usuariaplicacioid) VALUES (-305, 'Pinfo', -305, NULL);
INSERT INTO pfi_tipusdocument (tipusdocumentid, descripcio, nom, usuariaplicacioid) VALUES (-306, 'Notes internes', -306, NULL);
INSERT INTO pfi_tipusdocument (tipusdocumentid, descripcio, nom, usuariaplicacioid) VALUES (-307, 'Contractes', -307, NULL);
INSERT INTO pfi_tipusdocument (tipusdocumentid, descripcio, nom, usuariaplicacioid) VALUES (-308, 'Diligències', -308, NULL);
INSERT INTO pfi_tipusdocument (tipusdocumentid, descripcio, nom, usuariaplicacioid) VALUES (-309, 'Informes', -309, NULL);
INSERT INTO pfi_tipusdocument (tipusdocumentid, descripcio, nom, usuariaplicacioid) VALUES (-310, 'Carta', -310, NULL);
INSERT INTO pfi_tipusdocument (tipusdocumentid, descripcio, nom, usuariaplicacioid) VALUES (-311, 'Certificat', -311, NULL);
INSERT INTO pfi_tipusdocument (tipusdocumentid, descripcio, nom, usuariaplicacioid) VALUES (-312, 'Resolució', -312, NULL);
INSERT INTO pfi_tipusdocument (tipusdocumentid, descripcio, nom, usuariaplicacioid) VALUES (-313, 'Propostes', -313, NULL);
INSERT INTO pfi_tipusdocument (tipusdocumentid, descripcio, nom, usuariaplicacioid) VALUES (-315, 'Verificacions de l''article 13 reglament (ce) 1828/2006', -315, NULL);
INSERT INTO pfi_tipusdocument (tipusdocumentid, descripcio, nom, usuariaplicacioid) VALUES (-316, 'Homologacions d''estudis reglats', -316, NULL);
INSERT INTO pfi_tipusdocument (tipusdocumentid, descripcio, nom, usuariaplicacioid) VALUES (-317, 'Subvencions arquitectura / habitatge', -317, NULL);
INSERT INTO pfi_tipusdocument (tipusdocumentid, descripcio, nom, usuariaplicacioid) VALUES (-318, 'Firma del Vicepresident del FOGAIBA', -318, NULL);
INSERT INTO pfi_tipusdocument (tipusdocumentid, descripcio, nom, usuariaplicacioid) VALUES (-319, 'Firma del Cap de servei tècnic i Director General', -319, NULL);
INSERT INTO pfi_tipusdocument (tipusdocumentid, descripcio, nom, usuariaplicacioid) VALUES (-320, 'Firma del Cap de departament de gestió i Director General', -320, NULL);
INSERT INTO pfi_tipusdocument (tipusdocumentid, descripcio, nom, usuariaplicacioid) VALUES (-321, 'Convocatòries', -321, NULL);
INSERT INTO pfi_tipusdocument (tipusdocumentid, descripcio, nom, usuariaplicacioid) VALUES (-322, 'Túnel de Sóller', -322, NULL);
INSERT INTO pfi_tipusdocument (tipusdocumentid, descripcio, nom, usuariaplicacioid) VALUES (-601, 'Cartes de requeriment', -601, NULL);
INSERT INTO pfi_tipusdocument (tipusdocumentid, descripcio, nom, usuariaplicacioid) VALUES (-602, 'Cartes de citació', -602, NULL);
INSERT INTO pfi_tipusdocument (tipusdocumentid, descripcio, nom, usuariaplicacioid) VALUES (-603, 'Dictàmens tècnics / administratius', -603, NULL);
INSERT INTO pfi_tipusdocument (tipusdocumentid, descripcio, nom, usuariaplicacioid) VALUES (-604, 'Resolucions', -604, NULL);
INSERT INTO pfi_tipusdocument (tipusdocumentid, descripcio, nom, usuariaplicacioid) VALUES (-605, 'Certificats / Informes', -605, NULL);
INSERT INTO pfi_tipusdocument (tipusdocumentid, descripcio, nom, usuariaplicacioid) VALUES (-606, 'Ofici remissión a conselleria iniciativa parlamentària', -606, NULL);
INSERT INTO pfi_tipusdocument (tipusdocumentid, descripcio, nom, usuariaplicacioid) VALUES (-607, 'Resposta ofici remissió a conselleria iniciativa parlamentària', -607, NULL);
INSERT INTO pfi_tipusdocument (tipusdocumentid, descripcio, nom, usuariaplicacioid) VALUES (-608, 'Ofici de remissió al Parlament de la resposta', -608, NULL);
INSERT INTO pfi_tipusdocument (tipusdocumentid, descripcio, nom, usuariaplicacioid) VALUES (-609, 'Ofici de remissió certificat aprovació moció', -609, NULL);
INSERT INTO pfi_tipusdocument (tipusdocumentid, descripcio, nom, usuariaplicacioid) VALUES (-610, 'Ofici remissió de la iniciativa parlamentària al Parlament', -610, NULL);
INSERT INTO pfi_tipusdocument (tipusdocumentid, descripcio, nom, usuariaplicacioid) VALUES (-611, 'Ofici de remissió a conselleria informe omnicomprensiu', -611, NULL);
INSERT INTO pfi_tipusdocument (tipusdocumentid, descripcio, nom, usuariaplicacioid) VALUES (-612, 'Ofici de remissió de la iniciativa al Parlament', -612, NULL);
INSERT INTO pfi_tipusdocument (tipusdocumentid, descripcio, nom, usuariaplicacioid) VALUES (-613, 'Ofici de remissió deficiències formals', -613, NULL);
INSERT INTO pfi_tipusdocument (tipusdocumentid, descripcio, nom, usuariaplicacioid) VALUES (-614, 'Ofici de remissió al Parlament documentació esmena', -614, NULL);
INSERT INTO pfi_tipusdocument (tipusdocumentid, descripcio, nom, usuariaplicacioid) VALUES (-615, 'Ofici de remisión al Parlament publicació BOIB', -615, NULL);
INSERT INTO pfi_tipusdocument (tipusdocumentid, descripcio, nom, usuariaplicacioid) VALUES (-616, 'Ofici remissió a conselleria esmena de devolució', -616, NULL);
INSERT INTO pfi_tipusdocument (tipusdocumentid, descripcio, nom, usuariaplicacioid) VALUES (-617, 'Ofici remissió a conselleria esmena de substitució', -617, NULL);
INSERT INTO pfi_tipusdocument (tipusdocumentid, descripcio, nom, usuariaplicacioid) VALUES (-618, 'Ofici de remissió a conselleria afectada esmena incid pressupostària', -618, NULL);
INSERT INTO pfi_tipusdocument (tipusdocumentid, descripcio, nom, usuariaplicacioid) VALUES (-619, 'Ofici de remissió a vicepresidència econòmica esmena incid pressupostària', -619, NULL);
INSERT INTO pfi_tipusdocument (tipusdocumentid, descripcio, nom, usuariaplicacioid) VALUES (-620, 'Ofici remissió al Parlament certificat Consell de Govern (esmena pressupostària)', -620, NULL);
INSERT INTO pfi_tipusdocument (tipusdocumentid, descripcio, nom, usuariaplicacioid) VALUES (-621, 'Ofici de remissió al Parlament certificat aprovació retirada projecte de llei', -621, NULL);
INSERT INTO pfi_tipusdocument (tipusdocumentid, descripcio, nom, usuariaplicacioid) VALUES (-622, 'Ofici de remissió al Parlament Certificat acord Consell de Govern', -622, NULL);
INSERT INTO pfi_tipusdocument (tipusdocumentid, descripcio, nom, usuariaplicacioid) VALUES (-623, 'Ofici de remissió al Parlament del decret llei', -623, NULL);
INSERT INTO pfi_tipusdocument (tipusdocumentid, descripcio, nom, usuariaplicacioid) VALUES (-624, 'Ofici de remissió al Parlament iniciativa parlamentària', -624, NULL);
INSERT INTO pfi_tipusdocument (tipusdocumentid, descripcio, nom, usuariaplicacioid) VALUES (-625, 'Ofici de remissió a conselleria certificat aprovació proposta', -625, NULL);
INSERT INTO pfi_tipusdocument (tipusdocumentid, descripcio, nom, usuariaplicacioid) VALUES (-626, 'Resolució de dessistiment', -626, NULL);
INSERT INTO pfi_tipusdocument (tipusdocumentid, descripcio, nom, usuariaplicacioid) VALUES (-627, 'Petició de documentació', -627, NULL);
INSERT INTO pfi_tipusdocument (tipusdocumentid, descripcio, nom, usuariaplicacioid) VALUES (-628, 'Resolució de concessió', -628, NULL);
INSERT INTO pfi_tipusdocument (tipusdocumentid, descripcio, nom, usuariaplicacioid) VALUES (-629, 'Resolució de denegació', -629, NULL);
INSERT INTO pfi_tipusdocument (tipusdocumentid, descripcio, nom, usuariaplicacioid) VALUES (-630, 'Autorització preceptiva de la resolució per a la publicació d''un tràmit telemàtic', -630, NULL);
INSERT INTO pfi_tipusdocument (tipusdocumentid, descripcio, nom, usuariaplicacioid) VALUES (-634, 'Butlletí de situació', -634, NULL);
INSERT INTO pfi_tipusdocument (tipusdocumentid, descripcio, nom, usuariaplicacioid) VALUES (-635, 'Sol.licitud informe ECA', -635, NULL);
INSERT INTO pfi_tipusdocument (tipusdocumentid, descripcio, nom, usuariaplicacioid) VALUES (-636, 'Notificació al contribuent de la proposta de liquidació', -636, NULL);
INSERT INTO pfi_tipusdocument (tipusdocumentid, descripcio, nom, usuariaplicacioid) VALUES (-637, 'Notificació provisional al contribuent de la proposta de liquidació', -637, NULL);
INSERT INTO pfi_tipusdocument (tipusdocumentid, descripcio, nom, usuariaplicacioid) VALUES (-638, 'Comunicacions a empreses', -638, NULL);
INSERT INTO pfi_tipusdocument (tipusdocumentid, descripcio, nom, usuariaplicacioid) VALUES (-999, 'Altres', -999, NULL);
