grant select,insert,delete,update on pfi_estadistica to www_portafib;
grant select,insert,delete,update on pfi_revisordefirma to www_portafib;
grant select,insert,delete,update on pfi_usuariaplicacioconfig to www_portafib;
grant select,insert,delete,update on pfi_pluginfirmawebperusrent to www_portafib;
grant select,insert,delete,update on pfi_pluginfirmawebperusrapp to www_portafib;
grant select,insert,delete,update on pfi_plugincridada to www_portafib;
grant select,insert,delete,update on pfi_usuariaplicacioperfil to www_portafib;
grant select,insert,delete,update on pfi_perfilsperusrapp to www_portafib;
grant select,insert,delete,update on pfi_plugin to www_portafib;