/*
 * API Interna de PortaFIB de consulta de serveis d'utilitat
 * Conjunt de Serveis REST de PortaFIB per atendre consultes generiques de Portafib
 *
 * The version of the OpenAPI document: 1.0-SNAPSHOT
 * Contact: otae@fundaciobit.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package es.caib.portafib.apiinterna.client.utils.v1.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import es.caib.portafib.apiinterna.client.utils.v1.model.FirmaSimpleFile;
import es.caib.portafib.apiinterna.client.utils.v1.model.FirmaSimpleSignedFileInfo;
import es.caib.portafib.apiinterna.client.utils.v1.model.FirmaSimpleStatus;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * FirmaSimpleSignatureRest
 */
@JsonPropertyOrder({
  FirmaSimpleSignatureRest.JSON_PROPERTY_SIGN_I_D,
  FirmaSimpleSignatureRest.JSON_PROPERTY_STATUS,
  FirmaSimpleSignatureRest.JSON_PROPERTY_SIGNED_FILE,
  FirmaSimpleSignatureRest.JSON_PROPERTY_SIGNED_FILE_INFO
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class FirmaSimpleSignatureRest {
  public static final String JSON_PROPERTY_SIGN_I_D = "signID";
  private String signID;

  public static final String JSON_PROPERTY_STATUS = "status";
  private FirmaSimpleStatus status;

  public static final String JSON_PROPERTY_SIGNED_FILE = "signedFile";
  private FirmaSimpleFile signedFile;

  public static final String JSON_PROPERTY_SIGNED_FILE_INFO = "signedFileInfo";
  private FirmaSimpleSignedFileInfo signedFileInfo;

  public FirmaSimpleSignatureRest() {
  }

  public FirmaSimpleSignatureRest signID(String signID) {
    
    this.signID = signID;
    return this;
  }

   /**
   * Get signID
   * @return signID
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SIGN_I_D)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSignID() {
    return signID;
  }


  @JsonProperty(JSON_PROPERTY_SIGN_I_D)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSignID(String signID) {
    this.signID = signID;
  }


  public FirmaSimpleSignatureRest status(FirmaSimpleStatus status) {
    
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public FirmaSimpleStatus getStatus() {
    return status;
  }


  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStatus(FirmaSimpleStatus status) {
    this.status = status;
  }


  public FirmaSimpleSignatureRest signedFile(FirmaSimpleFile signedFile) {
    
    this.signedFile = signedFile;
    return this;
  }

   /**
   * Get signedFile
   * @return signedFile
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SIGNED_FILE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public FirmaSimpleFile getSignedFile() {
    return signedFile;
  }


  @JsonProperty(JSON_PROPERTY_SIGNED_FILE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSignedFile(FirmaSimpleFile signedFile) {
    this.signedFile = signedFile;
  }


  public FirmaSimpleSignatureRest signedFileInfo(FirmaSimpleSignedFileInfo signedFileInfo) {
    
    this.signedFileInfo = signedFileInfo;
    return this;
  }

   /**
   * Get signedFileInfo
   * @return signedFileInfo
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SIGNED_FILE_INFO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public FirmaSimpleSignedFileInfo getSignedFileInfo() {
    return signedFileInfo;
  }


  @JsonProperty(JSON_PROPERTY_SIGNED_FILE_INFO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSignedFileInfo(FirmaSimpleSignedFileInfo signedFileInfo) {
    this.signedFileInfo = signedFileInfo;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FirmaSimpleSignatureRest firmaSimpleSignatureRest = (FirmaSimpleSignatureRest) o;
    return Objects.equals(this.signID, firmaSimpleSignatureRest.signID) &&
        Objects.equals(this.status, firmaSimpleSignatureRest.status) &&
        Objects.equals(this.signedFile, firmaSimpleSignatureRest.signedFile) &&
        Objects.equals(this.signedFileInfo, firmaSimpleSignatureRest.signedFileInfo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(signID, status, signedFile, signedFileInfo);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FirmaSimpleSignatureRest {\n");
    sb.append("    signID: ").append(toIndentedString(signID)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    signedFile: ").append(toIndentedString(signedFile)).append("\n");
    sb.append("    signedFileInfo: ").append(toIndentedString(signedFileInfo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

