
INSERT INTO SC_WL_USUARI (USU_CODI, USU_PASS, USU_DATCAD, USU_NOM, USU_NIF) VALUES ( 'admin', 'admin', null, 'admin', '12345678Z');
INSERT INTO SC_WL_USUARI (USU_CODI, USU_PASS, USU_DATCAD, USU_NOM, USU_NIF) VALUES ( 'aden2', 'aden2', null, 'Admin Entitat deCaib', '00000002E');
INSERT INTO SC_WL_USUARI (USU_CODI, USU_PASS, USU_DATCAD, USU_NOM, USU_NIF) VALUES ( 'senserol', 'senserol', null, 'Sense Rol', '11111111A');
INSERT INTO SC_WL_USUARI (USU_CODI, USU_PASS, USU_DATCAD, USU_NOM, USU_NIF) VALUES ('dest2', 'dest2', null, 'Destinatari2', '00000002T');
INSERT INTO SC_WL_USUARI (USU_CODI, USU_PASS, USU_DATCAD, USU_NOM, USU_NIF) VALUES ( 'soli1', 'soli1', null, 'Solicitant1', '00000001S');
INSERT INTO SC_WL_USUARI (USU_CODI, USU_PASS, USU_DATCAD, USU_NOM, USU_NIF) VALUES ('dest1', 'dest1', null, 'Destinatari1', '00000001T');
INSERT INTO SC_WL_USUARI (USU_CODI, USU_PASS, USU_DATCAD, USU_NOM, USU_NIF) VALUES ( 'dele2', 'dele2', null, 'Delegat 2', '00000002D');
INSERT INTO SC_WL_USUARI (USU_CODI, USU_PASS, USU_DATCAD, USU_NOM, USU_NIF) VALUES ( 'dele1', 'dele1', null, 'Delegat 1', '00000001D');
INSERT INTO SC_WL_USUARI (USU_CODI, USU_PASS, USU_DATCAD, USU_NOM, USU_NIF) VALUES ( 'cola1', 'cola1', null, 'Colaborador 1', '00000001C');
INSERT INTO SC_WL_USUARI (USU_CODI, USU_PASS, USU_DATCAD, USU_NOM, USU_NIF) VALUES ( 'aden1', 'aden1', null, 'Admin Entitat de FundacioBit', '00000001E');
INSERT INTO SC_WL_USUARI (USU_CODI, USU_PASS, USU_DATCAD, USU_NOM, USU_NIF) VALUES ('cola2', 'cola2', null, 'Colaborador 2', '00000002C');
INSERT INTO SC_WL_USUARI (USU_CODI, USU_PASS, USU_DATCAD, USU_NOM, USU_NIF) VALUES ( 'soli2', 'soli2', null, 'Solicitant2', '00000002S');

INSERT INTO SC_WL_USUGRU (UGR_CODUSU, UGR_CODGRU) VALUES ('aden1', 'PFI_USER');
INSERT INTO SC_WL_USUGRU (UGR_CODUSU, UGR_CODGRU) VALUES ('aden2', 'PFI_USER');
INSERT INTO SC_WL_USUGRU (UGR_CODUSU, UGR_CODGRU) VALUES ('admin', 'PFI_ADMIN');
INSERT INTO SC_WL_USUGRU (UGR_CODUSU, UGR_CODGRU) VALUES ('cola1', 'PFI_USER');
INSERT INTO SC_WL_USUGRU (UGR_CODUSU, UGR_CODGRU) VALUES ('cola2', 'PFI_USER');
INSERT INTO SC_WL_USUGRU (UGR_CODUSU, UGR_CODGRU) VALUES ('dele1', 'PFI_USER');
INSERT INTO SC_WL_USUGRU (UGR_CODUSU, UGR_CODGRU) VALUES ('dele2', 'PFI_USER');
INSERT INTO SC_WL_USUGRU (UGR_CODUSU, UGR_CODGRU) VALUES ('dest1', 'PFI_USER');
INSERT INTO SC_WL_USUGRU (UGR_CODUSU, UGR_CODGRU) VALUES ('dest2', 'PFI_USER');
INSERT INTO SC_WL_USUGRU (UGR_CODUSU, UGR_CODGRU) VALUES ('senserol', 'PFI_ADMIN');
INSERT INTO SC_WL_USUGRU (UGR_CODUSU, UGR_CODGRU) VALUES ('soli1', 'PFI_USER');
INSERT INTO SC_WL_USUGRU (UGR_CODUSU, UGR_CODGRU) VALUES ('soli2', 'PFI_USER');