package es.caib.portafib.ws.api.v1.passarelafirmaweb;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.4
 * 2016-08-30T15:18:58.073+02:00
 * Generated source version: 2.6.4
 * 
 */
@WebService(targetNamespace = "http://impl.v1.ws.portafib.caib.es/", name = "PortaFIBPassarelaDeFirmaWebWs")
@XmlSeeAlso({ObjectFactory.class})
public interface PortaFIBPassarelaDeFirmaWebWs {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getEntitatID", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.passarelafirmaweb.GetEntitatID")
    @WebMethod
    @ResponseWrapper(localName = "getEntitatIDResponse", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.passarelafirmaweb.GetEntitatIDResponse")
    public java.lang.String getEntitatID();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getTimeStampPolicy", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.passarelafirmaweb.GetTimeStampPolicy")
    @WebMethod
    @ResponseWrapper(localName = "getTimeStampPolicyResponse", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.passarelafirmaweb.GetTimeStampPolicyResponse")
    public int getTimeStampPolicy() throws WsI18NException;

    @RequestWrapper(localName = "closeTransaction", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.passarelafirmaweb.CloseTransaction")
    @WebMethod
    @ResponseWrapper(localName = "closeTransactionResponse", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.passarelafirmaweb.CloseTransactionResponse")
    public void closeTransaction(
        @WebParam(name = "signaturesSetID", targetNamespace = "")
        java.lang.String signaturesSetID
    ) throws WsI18NException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getSupportedSignatureAlgorithms", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.passarelafirmaweb.GetSupportedSignatureAlgorithms")
    @WebMethod
    @ResponseWrapper(localName = "getSupportedSignatureAlgorithmsResponse", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.passarelafirmaweb.GetSupportedSignatureAlgorithmsResponse")
    public java.util.List<java.lang.String> getSupportedSignatureAlgorithms(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.util.List<java.lang.Long> arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.util.List<java.lang.String> arg2
    ) throws WsI18NException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getSupportedBarCodeTypes", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.passarelafirmaweb.GetSupportedBarCodeTypes")
    @WebMethod
    @ResponseWrapper(localName = "getSupportedBarCodeTypesResponse", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.passarelafirmaweb.GetSupportedBarCodeTypesResponse")
    public java.util.List<java.lang.String> getSupportedBarCodeTypes() throws WsI18NException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getSignatureResultsOfTransaction", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.passarelafirmaweb.GetSignatureResultsOfTransaction")
    @WebMethod
    @ResponseWrapper(localName = "getSignatureResultsOfTransactionResponse", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.passarelafirmaweb.GetSignatureResultsOfTransactionResponse")
    public java.util.List<es.caib.portafib.ws.api.v1.passarelafirmaweb.PassarelaSignatureResult> getSignatureResultsOfTransaction(
        @WebParam(name = "signaturesSetID", targetNamespace = "")
        java.lang.String signaturesSetID
    ) throws WsI18NException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getVersionWs", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.passarelafirmaweb.GetVersionWs")
    @WebMethod
    @ResponseWrapper(localName = "getVersionWsResponse", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.passarelafirmaweb.GetVersionWsResponse")
    public int getVersionWs();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getStatusTransaction", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.passarelafirmaweb.GetStatusTransaction")
    @WebMethod
    @ResponseWrapper(localName = "getStatusTransactionResponse", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.passarelafirmaweb.GetStatusTransactionResponse")
    public es.caib.portafib.ws.api.v1.passarelafirmaweb.PassarelaSignatureStatus getStatusTransaction(
        @WebParam(name = "signaturesSetID", targetNamespace = "")
        java.lang.String signaturesSetID
    ) throws WsI18NException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "providesTimeStampGenerator", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.passarelafirmaweb.ProvidesTimeStampGenerator")
    @WebMethod
    @ResponseWrapper(localName = "providesTimeStampGeneratorResponse", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.passarelafirmaweb.ProvidesTimeStampGeneratorResponse")
    public boolean providesTimeStampGenerator(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.util.List<java.lang.Long> arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.util.List<java.lang.String> arg2
    ) throws WsI18NException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getSupportedLanguages", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.passarelafirmaweb.GetSupportedLanguages")
    @WebMethod
    @ResponseWrapper(localName = "getSupportedLanguagesResponse", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.passarelafirmaweb.GetSupportedLanguagesResponse")
    public java.util.List<java.lang.String> getSupportedLanguages() throws WsI18NException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "downloadFileUsingEncryptedFileID", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.passarelafirmaweb.DownloadFileUsingEncryptedFileID")
    @WebMethod
    @ResponseWrapper(localName = "downloadFileUsingEncryptedFileIDResponse", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.passarelafirmaweb.DownloadFileUsingEncryptedFileIDResponse")
    public es.caib.portafib.ws.api.v1.passarelafirmaweb.FitxerBean downloadFileUsingEncryptedFileID(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    ) throws WsI18NException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getSupportedSignatureTypes", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.passarelafirmaweb.GetSupportedSignatureTypes")
    @WebMethod
    @ResponseWrapper(localName = "getSupportedSignatureTypesResponse", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.passarelafirmaweb.GetSupportedSignatureTypesResponse")
    public java.util.List<java.lang.String> getSupportedSignatureTypes(
        @WebParam(name = "arg0", targetNamespace = "")
        java.util.List<java.lang.Long> arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.util.List<java.lang.String> arg1
    ) throws WsI18NException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getAllPluginIDCustodia", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.passarelafirmaweb.GetAllPluginIDCustodia")
    @WebMethod
    @ResponseWrapper(localName = "getAllPluginIDCustodiaResponse", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.passarelafirmaweb.GetAllPluginIDCustodiaResponse")
    public java.util.List<java.lang.Long> getAllPluginIDCustodia() throws WsI18NException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getCustodiaPolicy", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.passarelafirmaweb.GetCustodiaPolicy")
    @WebMethod
    @ResponseWrapper(localName = "getCustodiaPolicyResponse", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.passarelafirmaweb.GetCustodiaPolicyResponse")
    public int getCustodiaPolicy() throws WsI18NException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "startTransaction", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.passarelafirmaweb.StartTransaction")
    @WebMethod
    @ResponseWrapper(localName = "startTransactionResponse", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.passarelafirmaweb.StartTransactionResponse")
    public java.lang.String startTransaction(
        @WebParam(name = "signaturesSet", targetNamespace = "")
        es.caib.portafib.ws.api.v1.passarelafirmaweb.PassarelaSignaturesSet signaturesSet
    ) throws WsI18NException, WsValidationException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getDefaultCustodiaInfo", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.passarelafirmaweb.GetDefaultCustodiaInfo")
    @WebMethod
    @ResponseWrapper(localName = "getDefaultCustodiaInfoResponse", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.passarelafirmaweb.GetDefaultCustodiaInfoResponse")
    public es.caib.portafib.ws.api.v1.passarelafirmaweb.CustodiaInfoBean getDefaultCustodiaInfo(
        @WebParam(name = "title", targetNamespace = "")
        java.lang.String title,
        @WebParam(name = "language", targetNamespace = "")
        java.lang.String language
    ) throws WsI18NException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getAllCustodiaInfoTemplates", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.passarelafirmaweb.GetAllCustodiaInfoTemplates")
    @WebMethod
    @ResponseWrapper(localName = "getAllCustodiaInfoTemplatesResponse", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.passarelafirmaweb.GetAllCustodiaInfoTemplatesResponse")
    public java.util.List<es.caib.portafib.ws.api.v1.passarelafirmaweb.CustodiaInfoBean> getAllCustodiaInfoTemplates() throws WsI18NException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getVersion", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.passarelafirmaweb.GetVersion")
    @WebMethod
    @ResponseWrapper(localName = "getVersionResponse", targetNamespace = "http://impl.v1.ws.portafib.caib.es/", className = "es.caib.portafib.ws.api.v1.passarelafirmaweb.GetVersionResponse")
    public java.lang.String getVersion();
}
