package es.caib.portafib.ws.api.v1.passarelafirmaweb;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.6.4
 * 2016-08-30T15:18:58.088+02:00
 * Generated source version: 2.6.4
 * 
 */
@WebServiceClient(name = "PortaFIBPassarelaDeFirmaWebWsService", 
                  wsdlLocation = "http://localhost:8080/portafib/ws/v1/PortaFIBPassarelaDeFirmaWeb?wsdl",
                  targetNamespace = "http://impl.v1.ws.portafib.caib.es/") 
public class PortaFIBPassarelaDeFirmaWebWsService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.v1.ws.portafib.caib.es/", "PortaFIBPassarelaDeFirmaWebWsService");
    public final static QName PortaFIBPassarelaDeFirmaWebWs = new QName("http://impl.v1.ws.portafib.caib.es/", "PortaFIBPassarelaDeFirmaWebWs");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/portafib/ws/v1/PortaFIBPassarelaDeFirmaWeb?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(PortaFIBPassarelaDeFirmaWebWsService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/portafib/ws/v1/PortaFIBPassarelaDeFirmaWeb?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public PortaFIBPassarelaDeFirmaWebWsService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PortaFIBPassarelaDeFirmaWebWsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PortaFIBPassarelaDeFirmaWebWsService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns PortaFIBPassarelaDeFirmaWebWs
     */
    @WebEndpoint(name = "PortaFIBPassarelaDeFirmaWebWs")
    public PortaFIBPassarelaDeFirmaWebWs getPortaFIBPassarelaDeFirmaWebWs() {
        return super.getPort(PortaFIBPassarelaDeFirmaWebWs, PortaFIBPassarelaDeFirmaWebWs.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PortaFIBPassarelaDeFirmaWebWs
     */
    @WebEndpoint(name = "PortaFIBPassarelaDeFirmaWebWs")
    public PortaFIBPassarelaDeFirmaWebWs getPortaFIBPassarelaDeFirmaWebWs(WebServiceFeature... features) {
        return super.getPort(PortaFIBPassarelaDeFirmaWebWs, PortaFIBPassarelaDeFirmaWebWs.class, features);
    }

}
