
package es.caib.portafib.ws.api.v1.passarelafirmaweb;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.4
 * 2017-07-26T13:41:43.775+02:00
 * Generated source version: 2.6.4
 */

@WebFault(name = "WsValidationErrors", targetNamespace = "http://impl.v1.ws.portafib.caib.es/")
public class WsValidationException extends Exception {
    
    private es.caib.portafib.ws.api.v1.passarelafirmaweb.WsValidationErrors wsValidationErrors;

    public WsValidationException() {
        super();
    }
    
    public WsValidationException(String message) {
        super(message);
    }
    
    public WsValidationException(String message, Throwable cause) {
        super(message, cause);
    }

    public WsValidationException(String message, es.caib.portafib.ws.api.v1.passarelafirmaweb.WsValidationErrors wsValidationErrors) {
        super(message);
        this.wsValidationErrors = wsValidationErrors;
    }

    public WsValidationException(String message, es.caib.portafib.ws.api.v1.passarelafirmaweb.WsValidationErrors wsValidationErrors, Throwable cause) {
        super(message, cause);
        this.wsValidationErrors = wsValidationErrors;
    }

    public es.caib.portafib.ws.api.v1.passarelafirmaweb.WsValidationErrors getFaultInfo() {
        return this.wsValidationErrors;
    }
}
