
package es.caib.portafib.ws.callback.api.v1;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.4
 * 2015-11-25T10:41:32.635+01:00
 * Generated source version: 2.6.4
 */

@WebFault(name = "CallBackFault", targetNamespace = "http://v1.server.callback.ws.portafib.caib.es/")
public class CallBackException extends Exception {
    
    private es.caib.portafib.ws.callback.api.v1.CallBackFault callBackFault;

    public CallBackException() {
        super();
    }
    
    public CallBackException(String message) {
        super(message);
    }
    
    public CallBackException(String message, Throwable cause) {
        super(message, cause);
    }

    public CallBackException(String message, es.caib.portafib.ws.callback.api.v1.CallBackFault callBackFault) {
        super(message);
        this.callBackFault = callBackFault;
    }

    public CallBackException(String message, es.caib.portafib.ws.callback.api.v1.CallBackFault callBackFault, Throwable cause) {
        super(message, cause);
        this.callBackFault = callBackFault;
    }

    public es.caib.portafib.ws.callback.api.v1.CallBackFault getFaultInfo() {
        return this.callBackFault;
    }
}
