package es.caib.portafib.ws.api.v1.passarelafirmaservidor;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.6.4
 * 2017-07-26T13:40:57.794+02:00
 * Generated source version: 2.6.4
 * 
 */
@WebServiceClient(name = "PortaFIBPassarelaDeFirmaEnServidorWsService", 
                  wsdlLocation = "http://localhost:8080/portafib/ws/v1/PortaFIBPassarelaDeFirmaEnServidor?wsdl",
                  targetNamespace = "http://impl.v1.ws.portafib.caib.es/") 
public class PortaFIBPassarelaDeFirmaEnServidorWsService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.v1.ws.portafib.caib.es/", "PortaFIBPassarelaDeFirmaEnServidorWsService");
    public final static QName PortaFIBPassarelaDeFirmaEnServidorWs = new QName("http://impl.v1.ws.portafib.caib.es/", "PortaFIBPassarelaDeFirmaEnServidorWs");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/portafib/ws/v1/PortaFIBPassarelaDeFirmaEnServidor?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(PortaFIBPassarelaDeFirmaEnServidorWsService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/portafib/ws/v1/PortaFIBPassarelaDeFirmaEnServidor?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public PortaFIBPassarelaDeFirmaEnServidorWsService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PortaFIBPassarelaDeFirmaEnServidorWsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PortaFIBPassarelaDeFirmaEnServidorWsService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns PortaFIBPassarelaDeFirmaEnServidorWs
     */
    @WebEndpoint(name = "PortaFIBPassarelaDeFirmaEnServidorWs")
    public PortaFIBPassarelaDeFirmaEnServidorWs getPortaFIBPassarelaDeFirmaEnServidorWs() {
        return super.getPort(PortaFIBPassarelaDeFirmaEnServidorWs, PortaFIBPassarelaDeFirmaEnServidorWs.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PortaFIBPassarelaDeFirmaEnServidorWs
     */
    @WebEndpoint(name = "PortaFIBPassarelaDeFirmaEnServidorWs")
    public PortaFIBPassarelaDeFirmaEnServidorWs getPortaFIBPassarelaDeFirmaEnServidorWs(WebServiceFeature... features) {
        return super.getPort(PortaFIBPassarelaDeFirmaEnServidorWs, PortaFIBPassarelaDeFirmaEnServidorWs.class, features);
    }

}
