/*
 * API Interna de PortaFIB de consulta de serveis d'utilitat
 * Conjunt de Serveis REST de PortaFIB per atendre consultes generiques de Portafib
 *
 * The version of the OpenAPI document: 1.0-SNAPSHOT
 * Contact: otae@fundaciobit.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package es.caib.portafib.apiinterna.client.firma.v1.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import es.caib.portafib.apiinterna.client.firma.v1.model.FirmaSimpleSignatureStatus;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * FirmaSimpleGetTransactionStatusResponse
 */
@JsonPropertyOrder({
  FirmaSimpleGetTransactionStatusResponse.JSON_PROPERTY_TRANSACTION_STATUS,
  FirmaSimpleGetTransactionStatusResponse.JSON_PROPERTY_SIGNATURES_STATUS_LIST
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class FirmaSimpleGetTransactionStatusResponse {
  public static final String JSON_PROPERTY_TRANSACTION_STATUS = "transactionStatus";
  @javax.annotation.Nonnull
  private FirmaSimpleStatus transactionStatus;

  public static final String JSON_PROPERTY_SIGNATURES_STATUS_LIST = "signaturesStatusList";
  @javax.annotation.Nonnull
  private List<FirmaSimpleSignatureStatus> signaturesStatusList = new ArrayList<>();

  public FirmaSimpleGetTransactionStatusResponse() {
  }

  public FirmaSimpleGetTransactionStatusResponse transactionStatus(@javax.annotation.Nonnull FirmaSimpleStatus transactionStatus) {
    
    this.transactionStatus = transactionStatus;
    return this;
  }

  /**
   * Get transactionStatus
   * @return transactionStatus
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TRANSACTION_STATUS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public FirmaSimpleStatus getTransactionStatus() {
    return transactionStatus;
  }


  @JsonProperty(JSON_PROPERTY_TRANSACTION_STATUS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTransactionStatus(@javax.annotation.Nonnull FirmaSimpleStatus transactionStatus) {
    this.transactionStatus = transactionStatus;
  }

  public FirmaSimpleGetTransactionStatusResponse signaturesStatusList(@javax.annotation.Nonnull List<FirmaSimpleSignatureStatus> signaturesStatusList) {
    
    this.signaturesStatusList = signaturesStatusList;
    return this;
  }

  public FirmaSimpleGetTransactionStatusResponse addSignaturesStatusListItem(FirmaSimpleSignatureStatus signaturesStatusListItem) {
    if (this.signaturesStatusList == null) {
      this.signaturesStatusList = new ArrayList<>();
    }
    this.signaturesStatusList.add(signaturesStatusListItem);
    return this;
  }

  /**
   * Estat de cada firma. Pot passar que l&#39;estat general sigui que tot ha anat bé, però que totes o algunes de les firmes no.
   * @return signaturesStatusList
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SIGNATURES_STATUS_LIST)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<FirmaSimpleSignatureStatus> getSignaturesStatusList() {
    return signaturesStatusList;
  }


  @JsonProperty(JSON_PROPERTY_SIGNATURES_STATUS_LIST)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSignaturesStatusList(@javax.annotation.Nonnull List<FirmaSimpleSignatureStatus> signaturesStatusList) {
    this.signaturesStatusList = signaturesStatusList;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FirmaSimpleGetTransactionStatusResponse firmaSimpleGetTransactionStatusResponse = (FirmaSimpleGetTransactionStatusResponse) o;
    return Objects.equals(this.transactionStatus, firmaSimpleGetTransactionStatusResponse.transactionStatus) &&
        Objects.equals(this.signaturesStatusList, firmaSimpleGetTransactionStatusResponse.signaturesStatusList);
  }

  @Override
  public int hashCode() {
    return Objects.hash(transactionStatus, signaturesStatusList);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FirmaSimpleGetTransactionStatusResponse {\n");
    sb.append("    transactionStatus: ").append(toIndentedString(transactionStatus)).append("\n");
    sb.append("    signaturesStatusList: ").append(toIndentedString(signaturesStatusList)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

