/*
 * API Interna de PortaFIB de consulta de serveis d'utilitat
 * Conjunt de Serveis REST de PortaFIB per atendre consultes generiques de Portafib
 *
 * The version of the OpenAPI document: 1.0-SNAPSHOT
 * Contact: otae@fundaciobit.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package es.caib.portafib.apiinterna.client.firma.v1.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import es.caib.portafib.apiinterna.client.firma.v1.model.FirmaSimpleFileInfoSignature;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * FirmaSimpleAddFileToSignRequest
 */
@JsonPropertyOrder({
  FirmaSimpleAddFileToSignRequest.JSON_PROPERTY_TRANSACTION_I_D,
  FirmaSimpleAddFileToSignRequest.JSON_PROPERTY_FILE_INFO_SIGNATURE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class FirmaSimpleAddFileToSignRequest {
  public static final String JSON_PROPERTY_TRANSACTION_I_D = "transactionID";
  @javax.annotation.Nonnull
  private String transactionID;

  public static final String JSON_PROPERTY_FILE_INFO_SIGNATURE = "fileInfoSignature";
  @javax.annotation.Nonnull
  private FirmaSimpleFileInfoSignature fileInfoSignature;

  public FirmaSimpleAddFileToSignRequest() {
  }

  public FirmaSimpleAddFileToSignRequest transactionID(@javax.annotation.Nonnull String transactionID) {
    
    this.transactionID = transactionID;
    return this;
  }

  /**
   * Identificador de transacció
   * @return transactionID
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TRANSACTION_I_D)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getTransactionID() {
    return transactionID;
  }


  @JsonProperty(JSON_PROPERTY_TRANSACTION_I_D)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTransactionID(@javax.annotation.Nonnull String transactionID) {
    this.transactionID = transactionID;
  }

  public FirmaSimpleAddFileToSignRequest fileInfoSignature(@javax.annotation.Nonnull FirmaSimpleFileInfoSignature fileInfoSignature) {
    
    this.fileInfoSignature = fileInfoSignature;
    return this;
  }

  /**
   * Get fileInfoSignature
   * @return fileInfoSignature
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_FILE_INFO_SIGNATURE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public FirmaSimpleFileInfoSignature getFileInfoSignature() {
    return fileInfoSignature;
  }


  @JsonProperty(JSON_PROPERTY_FILE_INFO_SIGNATURE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFileInfoSignature(@javax.annotation.Nonnull FirmaSimpleFileInfoSignature fileInfoSignature) {
    this.fileInfoSignature = fileInfoSignature;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FirmaSimpleAddFileToSignRequest firmaSimpleAddFileToSignRequest = (FirmaSimpleAddFileToSignRequest) o;
    return Objects.equals(this.transactionID, firmaSimpleAddFileToSignRequest.transactionID) &&
        Objects.equals(this.fileInfoSignature, firmaSimpleAddFileToSignRequest.fileInfoSignature);
  }

  @Override
  public int hashCode() {
    return Objects.hash(transactionID, fileInfoSignature);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FirmaSimpleAddFileToSignRequest {\n");
    sb.append("    transactionID: ").append(toIndentedString(transactionID)).append("\n");
    sb.append("    fileInfoSignature: ").append(toIndentedString(fileInfoSignature)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

