/*
 * API Interna de PortaFIB que ofereix serveis associats amb la firma digital
 * Conjunt de Serveis REST de PortaFIB per atendre peticions de firma en servidor, firma web, firma asincrona, utilitats de firma i plantilla de flux de firma.
 *
 * The version of the OpenAPI document: 1.0-SNAPSHOT
 * Contact: firma@fundaciobit.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package es.caib.portafib.apiinterna.client.firma.v1.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import es.caib.portafib.apiinterna.client.firma.v1.model.FirmaSimpleCustodyInfo;
import es.caib.portafib.apiinterna.client.firma.v1.model.FirmaSimpleSignerInfo;
import es.caib.portafib.apiinterna.client.firma.v1.model.FirmaSimpleValidationInfo;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Informació del fitxer signat.
 */
@JsonPropertyOrder({
  FirmaSimpleSignedFileInfo.JSON_PROPERTY_SIGN_OPERATION,
  FirmaSimpleSignedFileInfo.JSON_PROPERTY_SIGN_TYPE,
  FirmaSimpleSignedFileInfo.JSON_PROPERTY_SIGN_ALGORITHM,
  FirmaSimpleSignedFileInfo.JSON_PROPERTY_SIGN_MODE,
  FirmaSimpleSignedFileInfo.JSON_PROPERTY_SIGNATURES_TABLE_LOCATION,
  FirmaSimpleSignedFileInfo.JSON_PROPERTY_TIME_STAMP_INCLUDED,
  FirmaSimpleSignedFileInfo.JSON_PROPERTY_POLICY_INCLUDED,
  FirmaSimpleSignedFileInfo.JSON_PROPERTY_ENI_TIPO_FIRMA,
  FirmaSimpleSignedFileInfo.JSON_PROPERTY_ENI_PERFIL_FIRMA,
  FirmaSimpleSignedFileInfo.JSON_PROPERTY_SIGNER_INFO,
  FirmaSimpleSignedFileInfo.JSON_PROPERTY_CUSTODY_INFO,
  FirmaSimpleSignedFileInfo.JSON_PROPERTY_VALIDATION_INFO
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class FirmaSimpleSignedFileInfo {
  public static final String JSON_PROPERTY_SIGN_OPERATION = "signOperation";
  @javax.annotation.Nonnull
  private Integer signOperation;

  public static final String JSON_PROPERTY_SIGN_TYPE = "signType";
  @javax.annotation.Nonnull
  private String signType;

  public static final String JSON_PROPERTY_SIGN_ALGORITHM = "signAlgorithm";
  @javax.annotation.Nonnull
  private String signAlgorithm;

  public static final String JSON_PROPERTY_SIGN_MODE = "signMode";
  @javax.annotation.Nonnull
  private Integer signMode;

  public static final String JSON_PROPERTY_SIGNATURES_TABLE_LOCATION = "signaturesTableLocation";
  @javax.annotation.Nonnull
  private Integer signaturesTableLocation;

  public static final String JSON_PROPERTY_TIME_STAMP_INCLUDED = "timeStampIncluded";
  @javax.annotation.Nonnull
  private Boolean timeStampIncluded;

  public static final String JSON_PROPERTY_POLICY_INCLUDED = "policyIncluded";
  @javax.annotation.Nonnull
  private Boolean policyIncluded;

  public static final String JSON_PROPERTY_ENI_TIPO_FIRMA = "eniTipoFirma";
  @javax.annotation.Nullable
  private String eniTipoFirma;

  public static final String JSON_PROPERTY_ENI_PERFIL_FIRMA = "eniPerfilFirma";
  @javax.annotation.Nullable
  private String eniPerfilFirma;

  public static final String JSON_PROPERTY_SIGNER_INFO = "signerInfo";
  @javax.annotation.Nonnull
  private FirmaSimpleSignerInfo signerInfo;

  public static final String JSON_PROPERTY_CUSTODY_INFO = "custodyInfo";
  @javax.annotation.Nullable
  private FirmaSimpleCustodyInfo custodyInfo;

  public static final String JSON_PROPERTY_VALIDATION_INFO = "validationInfo";
  @javax.annotation.Nullable
  private FirmaSimpleValidationInfo validationInfo;

  public FirmaSimpleSignedFileInfo() {
  }

  public FirmaSimpleSignedFileInfo signOperation(@javax.annotation.Nonnull Integer signOperation) {
    
    this.signOperation = signOperation;
    return this;
  }

  /**
   * Operació de firma realitzada: Firma (0), Cofirma (1) o Contrafirma (2).
   * @return signOperation
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SIGN_OPERATION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getSignOperation() {
    return signOperation;
  }


  @JsonProperty(JSON_PROPERTY_SIGN_OPERATION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSignOperation(@javax.annotation.Nonnull Integer signOperation) {
    this.signOperation = signOperation;
  }

  public FirmaSimpleSignedFileInfo signType(@javax.annotation.Nonnull String signType) {
    
    this.signType = signType;
    return this;
  }

  /**
   * Tipus de Firma. Valors possibles:      - “PAdES” (Constant SIGN_TYPE_PADES)      - “XAdES” (Constant SIGN_TYPE_XADES)      - “CAdES” (Constant SIGN_TYPE_CADES)      - “FacturaE” (Constant SIGN_TYPE_FACTURAE)      - “OOXML” (Constant SIGN_TYPE_OOXML)      - “ODF” (Constant SIGN_TYPE_ODF)      - “SMIME” (Constant SIGN_TYPE_SMIME)      - “CAdES-ASiC-S” (Constant SIGN_TYPE_CADES_ASIC_S)      - “XAdES-ASiC-S” (Constant SIGN_TYPE_XADES_ASIC_S)      - “PKCS#1” (Constant SIGN_TYPE_PKCS1)
   * @return signType
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SIGN_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getSignType() {
    return signType;
  }


  @JsonProperty(JSON_PROPERTY_SIGN_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSignType(@javax.annotation.Nonnull String signType) {
    this.signType = signType;
  }

  public FirmaSimpleSignedFileInfo signAlgorithm(@javax.annotation.Nonnull String signAlgorithm) {
    
    this.signAlgorithm = signAlgorithm;
    return this;
  }

  /**
   * Algorisme de Firma. Valors:       - \&quot;SHA-1\&quot;      - \&quot;SHA-256\&quot;      - \&quot;SHA-384\&quot;      - \&quot;SHA-512\&quot;
   * @return signAlgorithm
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SIGN_ALGORITHM)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getSignAlgorithm() {
    return signAlgorithm;
  }


  @JsonProperty(JSON_PROPERTY_SIGN_ALGORITHM)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSignAlgorithm(@javax.annotation.Nonnull String signAlgorithm) {
    this.signAlgorithm = signAlgorithm;
  }

  public FirmaSimpleSignedFileInfo signMode(@javax.annotation.Nonnull Integer signMode) {
    
    this.signMode = signMode;
    return this;
  }

  /**
   * Valors:      - 0: Implicit o Attached. La firma resultante incluye internamente una copia de los datos firmados.       - 1: Explicit o Detached: La firma resultante no incluye los datos firmados. 
   * @return signMode
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SIGN_MODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getSignMode() {
    return signMode;
  }


  @JsonProperty(JSON_PROPERTY_SIGN_MODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSignMode(@javax.annotation.Nonnull Integer signMode) {
    this.signMode = signMode;
  }

  public FirmaSimpleSignedFileInfo signaturesTableLocation(@javax.annotation.Nonnull Integer signaturesTableLocation) {
    
    this.signaturesTableLocation = signaturesTableLocation;
    return this;
  }

  /**
   * Posició de la Taula de firmes:      - 0: Sense taula de firmes      - 1: Taula de firmes en la 1a pàgina      - -1: Darrera pàgina
   * @return signaturesTableLocation
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SIGNATURES_TABLE_LOCATION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getSignaturesTableLocation() {
    return signaturesTableLocation;
  }


  @JsonProperty(JSON_PROPERTY_SIGNATURES_TABLE_LOCATION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSignaturesTableLocation(@javax.annotation.Nonnull Integer signaturesTableLocation) {
    this.signaturesTableLocation = signaturesTableLocation;
  }

  public FirmaSimpleSignedFileInfo timeStampIncluded(@javax.annotation.Nonnull Boolean timeStampIncluded) {
    
    this.timeStampIncluded = timeStampIncluded;
    return this;
  }

  /**
   * Indica si s&#39;ha afegit un segell de Temps durant la firma
   * @return timeStampIncluded
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TIME_STAMP_INCLUDED)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Boolean getTimeStampIncluded() {
    return timeStampIncluded;
  }


  @JsonProperty(JSON_PROPERTY_TIME_STAMP_INCLUDED)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTimeStampIncluded(@javax.annotation.Nonnull Boolean timeStampIncluded) {
    this.timeStampIncluded = timeStampIncluded;
  }

  public FirmaSimpleSignedFileInfo policyIncluded(@javax.annotation.Nonnull Boolean policyIncluded) {
    
    this.policyIncluded = policyIncluded;
    return this;
  }

  /**
   * Indica si inclou política de firma (true, EPES) o no (false)
   * @return policyIncluded
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_POLICY_INCLUDED)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Boolean getPolicyIncluded() {
    return policyIncluded;
  }


  @JsonProperty(JSON_PROPERTY_POLICY_INCLUDED)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPolicyIncluded(@javax.annotation.Nonnull Boolean policyIncluded) {
    this.policyIncluded = policyIncluded;
  }

  public FirmaSimpleSignedFileInfo eniTipoFirma(@javax.annotation.Nullable String eniTipoFirma) {
    
    this.eniTipoFirma = eniTipoFirma;
    return this;
  }

  /**
   * Denominación normalizada del tipo de firma. Los posibles valores asignables son los siguientes:       - TF01 - CSV       - TF02 - XAdES internally detached signature\&quot;);       - TF03 - XAdES enveloped signature.      - TF04 - CAdES detached/explicit signature.      - TF05 – CadES attached/implicit signature.      - TF06 - PAdES. El tipo TF04 será establecido por defecto para documentos firmados, exceptuando los documentos en formato PDF o PDF/A, cuyo tipo será TF06.
   * @return eniTipoFirma
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ENI_TIPO_FIRMA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getEniTipoFirma() {
    return eniTipoFirma;
  }


  @JsonProperty(JSON_PROPERTY_ENI_TIPO_FIRMA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEniTipoFirma(@javax.annotation.Nullable String eniTipoFirma) {
    this.eniTipoFirma = eniTipoFirma;
  }

  public FirmaSimpleSignedFileInfo eniPerfilFirma(@javax.annotation.Nullable String eniPerfilFirma) {
    
    this.eniPerfilFirma = eniPerfilFirma;
    return this;
  }

  /**
   * Perfil empleado en una firma con certificado electrónico. Los posibles valores asignables son los siguientes:    AdES-BES    AdES-EPES    AdES-T    AdES-C    AdES-X    AdES-X1    AdES-X2    AdES-XL    AdES-XL1    AdES-XL2    AdES-A    PAdES-LTV    PAdES-Basic
   * @return eniPerfilFirma
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ENI_PERFIL_FIRMA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getEniPerfilFirma() {
    return eniPerfilFirma;
  }


  @JsonProperty(JSON_PROPERTY_ENI_PERFIL_FIRMA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEniPerfilFirma(@javax.annotation.Nullable String eniPerfilFirma) {
    this.eniPerfilFirma = eniPerfilFirma;
  }

  public FirmaSimpleSignedFileInfo signerInfo(@javax.annotation.Nonnull FirmaSimpleSignerInfo signerInfo) {
    
    this.signerInfo = signerInfo;
    return this;
  }

  /**
   * Get signerInfo
   * @return signerInfo
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SIGNER_INFO)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public FirmaSimpleSignerInfo getSignerInfo() {
    return signerInfo;
  }


  @JsonProperty(JSON_PROPERTY_SIGNER_INFO)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSignerInfo(@javax.annotation.Nonnull FirmaSimpleSignerInfo signerInfo) {
    this.signerInfo = signerInfo;
  }

  public FirmaSimpleSignedFileInfo custodyInfo(@javax.annotation.Nullable FirmaSimpleCustodyInfo custodyInfo) {
    
    this.custodyInfo = custodyInfo;
    return this;
  }

  /**
   * Get custodyInfo
   * @return custodyInfo
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CUSTODY_INFO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public FirmaSimpleCustodyInfo getCustodyInfo() {
    return custodyInfo;
  }


  @JsonProperty(JSON_PROPERTY_CUSTODY_INFO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCustodyInfo(@javax.annotation.Nullable FirmaSimpleCustodyInfo custodyInfo) {
    this.custodyInfo = custodyInfo;
  }

  public FirmaSimpleSignedFileInfo validationInfo(@javax.annotation.Nullable FirmaSimpleValidationInfo validationInfo) {
    
    this.validationInfo = validationInfo;
    return this;
  }

  /**
   * Get validationInfo
   * @return validationInfo
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VALIDATION_INFO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public FirmaSimpleValidationInfo getValidationInfo() {
    return validationInfo;
  }


  @JsonProperty(JSON_PROPERTY_VALIDATION_INFO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setValidationInfo(@javax.annotation.Nullable FirmaSimpleValidationInfo validationInfo) {
    this.validationInfo = validationInfo;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FirmaSimpleSignedFileInfo firmaSimpleSignedFileInfo = (FirmaSimpleSignedFileInfo) o;
    return Objects.equals(this.signOperation, firmaSimpleSignedFileInfo.signOperation) &&
        Objects.equals(this.signType, firmaSimpleSignedFileInfo.signType) &&
        Objects.equals(this.signAlgorithm, firmaSimpleSignedFileInfo.signAlgorithm) &&
        Objects.equals(this.signMode, firmaSimpleSignedFileInfo.signMode) &&
        Objects.equals(this.signaturesTableLocation, firmaSimpleSignedFileInfo.signaturesTableLocation) &&
        Objects.equals(this.timeStampIncluded, firmaSimpleSignedFileInfo.timeStampIncluded) &&
        Objects.equals(this.policyIncluded, firmaSimpleSignedFileInfo.policyIncluded) &&
        Objects.equals(this.eniTipoFirma, firmaSimpleSignedFileInfo.eniTipoFirma) &&
        Objects.equals(this.eniPerfilFirma, firmaSimpleSignedFileInfo.eniPerfilFirma) &&
        Objects.equals(this.signerInfo, firmaSimpleSignedFileInfo.signerInfo) &&
        Objects.equals(this.custodyInfo, firmaSimpleSignedFileInfo.custodyInfo) &&
        Objects.equals(this.validationInfo, firmaSimpleSignedFileInfo.validationInfo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(signOperation, signType, signAlgorithm, signMode, signaturesTableLocation, timeStampIncluded, policyIncluded, eniTipoFirma, eniPerfilFirma, signerInfo, custodyInfo, validationInfo);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FirmaSimpleSignedFileInfo {\n");
    sb.append("    signOperation: ").append(toIndentedString(signOperation)).append("\n");
    sb.append("    signType: ").append(toIndentedString(signType)).append("\n");
    sb.append("    signAlgorithm: ").append(toIndentedString(signAlgorithm)).append("\n");
    sb.append("    signMode: ").append(toIndentedString(signMode)).append("\n");
    sb.append("    signaturesTableLocation: ").append(toIndentedString(signaturesTableLocation)).append("\n");
    sb.append("    timeStampIncluded: ").append(toIndentedString(timeStampIncluded)).append("\n");
    sb.append("    policyIncluded: ").append(toIndentedString(policyIncluded)).append("\n");
    sb.append("    eniTipoFirma: ").append(toIndentedString(eniTipoFirma)).append("\n");
    sb.append("    eniPerfilFirma: ").append(toIndentedString(eniPerfilFirma)).append("\n");
    sb.append("    signerInfo: ").append(toIndentedString(signerInfo)).append("\n");
    sb.append("    custodyInfo: ").append(toIndentedString(custodyInfo)).append("\n");
    sb.append("    validationInfo: ").append(toIndentedString(validationInfo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

