/*
 * API Interna de PortaFIB que ofereix serveis de firma web.
 * Conjunt de Serveis REST de PortaFIB per atendre peticions de firma a través de web de PortaFIB
 *
 * The version of the OpenAPI document: 1.0-SNAPSHOT
 * Contact: otae@fundaciobit.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package es.caib.portafib.apiinterna.client.firma.v1.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Perfils de firma disponibles
 */
public enum SignProfile {
  
  AD_ES_BES("AdES-BES"),
  
  AD_ES_EPES("AdES-EPES"),
  
  AD_ES_T("AdES-T"),
  
  AD_ES_C("AdES-C"),
  
  AD_ES_X("AdES-X"),
  
  AD_ES_X1("AdES-X1"),
  
  AD_ES_X2("AdES-X2"),
  
  AD_ES_XL("AdES-XL"),
  
  AD_ES_XL1("AdES-XL1"),
  
  AD_ES_XL2("AdES-XL2"),
  
  AD_ES_A("AdES-A"),
  
  PAD_ES_LTV("PAdES-LTV"),
  
  PAD_ES_BASIC("PAdES-Basic");

  private String value;

  SignProfile(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static SignProfile fromValue(String value) {
    for (SignProfile b : SignProfile.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }
}

