/*
 * API Interna de PortaFIB de consulta de serveis d'utilitat
 * Conjunt de Serveis REST de PortaFIB per atendre consultes generiques de Portafib
 *
 * The version of the OpenAPI document: 1.0-SNAPSHOT
 * Contact: otae@fundaciobit.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package es.caib.portafib.apiinterna.client.firma.v1.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * TextNode
 */
@JsonPropertyOrder({
  TextNode.JSON_PROPERTY_TEXTUAL,
  TextNode.JSON_PROPERTY_BINARY_VALUE,
  TextNode.JSON_PROPERTY_TEXT_VALUE,
  TextNode.JSON_PROPERTY_VALUE_NODE,
  TextNode.JSON_PROPERTY_NUMBER_TYPE,
  TextNode.JSON_PROPERTY_ARRAY,
  TextNode.JSON_PROPERTY_FIELDS,
  TextNode.JSON_PROPERTY_NULL,
  TextNode.JSON_PROPERTY_ELEMENTS,
  TextNode.JSON_PROPERTY_DOUBLE_VALUE,
  TextNode.JSON_PROPERTY_LONG_VALUE,
  TextNode.JSON_PROPERTY_BOOLEAN_VALUE,
  TextNode.JSON_PROPERTY_NUMBER,
  TextNode.JSON_PROPERTY_INT,
  TextNode.JSON_PROPERTY_INT_VALUE,
  TextNode.JSON_PROPERTY_FLOATING_POINT_NUMBER,
  TextNode.JSON_PROPERTY_CONTAINER_NODE,
  TextNode.JSON_PROPERTY_MISSING_NODE,
  TextNode.JSON_PROPERTY_OBJECT,
  TextNode.JSON_PROPERTY_LONG,
  TextNode.JSON_PROPERTY_POJO,
  TextNode.JSON_PROPERTY_BIG_DECIMAL,
  TextNode.JSON_PROPERTY_BIG_INTEGER,
  TextNode.JSON_PROPERTY_BOOLEAN,
  TextNode.JSON_PROPERTY_DOUBLE,
  TextNode.JSON_PROPERTY_BINARY,
  TextNode.JSON_PROPERTY_INTEGRAL_NUMBER,
  TextNode.JSON_PROPERTY_BIG_INTEGER_VALUE,
  TextNode.JSON_PROPERTY_DECIMAL_VALUE,
  TextNode.JSON_PROPERTY_VALUE_AS_BOOLEAN,
  TextNode.JSON_PROPERTY_NUMBER_VALUE,
  TextNode.JSON_PROPERTY_VALUE_AS_INT,
  TextNode.JSON_PROPERTY_VALUE_AS_LONG,
  TextNode.JSON_PROPERTY_VALUE_AS_DOUBLE,
  TextNode.JSON_PROPERTY_VALUE_AS_TEXT,
  TextNode.JSON_PROPERTY_FIELD_NAMES
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class TextNode {
  public static final String JSON_PROPERTY_TEXTUAL = "textual";
  @javax.annotation.Nullable
  private Boolean textual;

  public static final String JSON_PROPERTY_BINARY_VALUE = "binaryValue";
  @javax.annotation.Nullable
  private List<byte[]> binaryValue = new ArrayList<>();

  public static final String JSON_PROPERTY_TEXT_VALUE = "textValue";
  @javax.annotation.Nullable
  private String textValue;

  public static final String JSON_PROPERTY_VALUE_NODE = "valueNode";
  @javax.annotation.Nullable
  private Boolean valueNode;

  /**
   * Gets or Sets numberType
   */
  public enum NumberTypeEnum {
    INT(String.valueOf("INT")),
    
    LONG(String.valueOf("LONG")),
    
    BIG_INTEGER(String.valueOf("BIG_INTEGER")),
    
    FLOAT(String.valueOf("FLOAT")),
    
    DOUBLE(String.valueOf("DOUBLE")),
    
    BIG_DECIMAL(String.valueOf("BIG_DECIMAL"));

    private String value;

    NumberTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static NumberTypeEnum fromValue(String value) {
      for (NumberTypeEnum b : NumberTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_NUMBER_TYPE = "numberType";
  @javax.annotation.Nullable
  private NumberTypeEnum numberType;

  public static final String JSON_PROPERTY_ARRAY = "array";
  @javax.annotation.Nullable
  private Boolean array;

  public static final String JSON_PROPERTY_FIELDS = "fields";
  @javax.annotation.Nullable
  private Object fields;

  public static final String JSON_PROPERTY_NULL = "null";
  @javax.annotation.Nullable
  private Boolean _null;

  public static final String JSON_PROPERTY_ELEMENTS = "elements";
  @javax.annotation.Nullable
  private Object elements;

  public static final String JSON_PROPERTY_DOUBLE_VALUE = "doubleValue";
  @javax.annotation.Nullable
  private Double doubleValue;

  public static final String JSON_PROPERTY_LONG_VALUE = "longValue";
  @javax.annotation.Nullable
  private Long longValue;

  public static final String JSON_PROPERTY_BOOLEAN_VALUE = "booleanValue";
  @javax.annotation.Nullable
  private Boolean booleanValue;

  public static final String JSON_PROPERTY_NUMBER = "number";
  @javax.annotation.Nullable
  private Boolean number;

  public static final String JSON_PROPERTY_INT = "int";
  @javax.annotation.Nullable
  private Boolean _int;

  public static final String JSON_PROPERTY_INT_VALUE = "intValue";
  @javax.annotation.Nullable
  private Integer intValue;

  public static final String JSON_PROPERTY_FLOATING_POINT_NUMBER = "floatingPointNumber";
  @javax.annotation.Nullable
  private Boolean floatingPointNumber;

  public static final String JSON_PROPERTY_CONTAINER_NODE = "containerNode";
  @javax.annotation.Nullable
  private Boolean containerNode;

  public static final String JSON_PROPERTY_MISSING_NODE = "missingNode";
  @javax.annotation.Nullable
  private Boolean missingNode;

  public static final String JSON_PROPERTY_OBJECT = "object";
  @javax.annotation.Nullable
  private Boolean _object;

  public static final String JSON_PROPERTY_LONG = "long";
  @javax.annotation.Nullable
  private Boolean _long;

  public static final String JSON_PROPERTY_POJO = "pojo";
  @javax.annotation.Nullable
  private Boolean pojo;

  public static final String JSON_PROPERTY_BIG_DECIMAL = "bigDecimal";
  @javax.annotation.Nullable
  private Boolean bigDecimal;

  public static final String JSON_PROPERTY_BIG_INTEGER = "bigInteger";
  @javax.annotation.Nullable
  private Boolean bigInteger;

  public static final String JSON_PROPERTY_BOOLEAN = "boolean";
  @javax.annotation.Nullable
  private Boolean _boolean;

  public static final String JSON_PROPERTY_DOUBLE = "double";
  @javax.annotation.Nullable
  private Boolean _double;

  public static final String JSON_PROPERTY_BINARY = "binary";
  @javax.annotation.Nullable
  private Boolean binary;

  public static final String JSON_PROPERTY_INTEGRAL_NUMBER = "integralNumber";
  @javax.annotation.Nullable
  private Boolean integralNumber;

  public static final String JSON_PROPERTY_BIG_INTEGER_VALUE = "bigIntegerValue";
  @javax.annotation.Nullable
  private Integer bigIntegerValue;

  public static final String JSON_PROPERTY_DECIMAL_VALUE = "decimalValue";
  @javax.annotation.Nullable
  private BigDecimal decimalValue;

  public static final String JSON_PROPERTY_VALUE_AS_BOOLEAN = "valueAsBoolean";
  @javax.annotation.Nullable
  private Boolean valueAsBoolean;

  public static final String JSON_PROPERTY_NUMBER_VALUE = "numberValue";
  @javax.annotation.Nullable
  private BigDecimal numberValue;

  public static final String JSON_PROPERTY_VALUE_AS_INT = "valueAsInt";
  @javax.annotation.Nullable
  private Integer valueAsInt;

  public static final String JSON_PROPERTY_VALUE_AS_LONG = "valueAsLong";
  @javax.annotation.Nullable
  private Long valueAsLong;

  public static final String JSON_PROPERTY_VALUE_AS_DOUBLE = "valueAsDouble";
  @javax.annotation.Nullable
  private Double valueAsDouble;

  public static final String JSON_PROPERTY_VALUE_AS_TEXT = "valueAsText";
  @javax.annotation.Nullable
  private String valueAsText;

  public static final String JSON_PROPERTY_FIELD_NAMES = "fieldNames";
  @javax.annotation.Nullable
  private Object fieldNames;

  public TextNode() {
  }

  public TextNode textual(@javax.annotation.Nullable Boolean textual) {
    
    this.textual = textual;
    return this;
  }

  /**
   * Get textual
   * @return textual
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TEXTUAL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getTextual() {
    return textual;
  }


  @JsonProperty(JSON_PROPERTY_TEXTUAL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTextual(@javax.annotation.Nullable Boolean textual) {
    this.textual = textual;
  }

  public TextNode binaryValue(@javax.annotation.Nullable List<byte[]> binaryValue) {
    
    this.binaryValue = binaryValue;
    return this;
  }

  public TextNode addBinaryValueItem(byte[] binaryValueItem) {
    if (this.binaryValue == null) {
      this.binaryValue = new ArrayList<>();
    }
    this.binaryValue.add(binaryValueItem);
    return this;
  }

  /**
   * Get binaryValue
   * @return binaryValue
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_BINARY_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<byte[]> getBinaryValue() {
    return binaryValue;
  }


  @JsonProperty(JSON_PROPERTY_BINARY_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBinaryValue(@javax.annotation.Nullable List<byte[]> binaryValue) {
    this.binaryValue = binaryValue;
  }

  public TextNode textValue(@javax.annotation.Nullable String textValue) {
    
    this.textValue = textValue;
    return this;
  }

  /**
   * Get textValue
   * @return textValue
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TEXT_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTextValue() {
    return textValue;
  }


  @JsonProperty(JSON_PROPERTY_TEXT_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTextValue(@javax.annotation.Nullable String textValue) {
    this.textValue = textValue;
  }

  public TextNode valueNode(@javax.annotation.Nullable Boolean valueNode) {
    
    this.valueNode = valueNode;
    return this;
  }

  /**
   * Get valueNode
   * @return valueNode
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VALUE_NODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getValueNode() {
    return valueNode;
  }


  @JsonProperty(JSON_PROPERTY_VALUE_NODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setValueNode(@javax.annotation.Nullable Boolean valueNode) {
    this.valueNode = valueNode;
  }

  public TextNode numberType(@javax.annotation.Nullable NumberTypeEnum numberType) {
    
    this.numberType = numberType;
    return this;
  }

  /**
   * Get numberType
   * @return numberType
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NUMBER_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public NumberTypeEnum getNumberType() {
    return numberType;
  }


  @JsonProperty(JSON_PROPERTY_NUMBER_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNumberType(@javax.annotation.Nullable NumberTypeEnum numberType) {
    this.numberType = numberType;
  }

  public TextNode array(@javax.annotation.Nullable Boolean array) {
    
    this.array = array;
    return this;
  }

  /**
   * Get array
   * @return array
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ARRAY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getArray() {
    return array;
  }


  @JsonProperty(JSON_PROPERTY_ARRAY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setArray(@javax.annotation.Nullable Boolean array) {
    this.array = array;
  }

  public TextNode fields(@javax.annotation.Nullable Object fields) {
    
    this.fields = fields;
    return this;
  }

  /**
   * Get fields
   * @return fields
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FIELDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Object getFields() {
    return fields;
  }


  @JsonProperty(JSON_PROPERTY_FIELDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFields(@javax.annotation.Nullable Object fields) {
    this.fields = fields;
  }

  public TextNode _null(@javax.annotation.Nullable Boolean _null) {
    
    this._null = _null;
    return this;
  }

  /**
   * Get _null
   * @return _null
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NULL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getNull() {
    return _null;
  }


  @JsonProperty(JSON_PROPERTY_NULL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNull(@javax.annotation.Nullable Boolean _null) {
    this._null = _null;
  }

  public TextNode elements(@javax.annotation.Nullable Object elements) {
    
    this.elements = elements;
    return this;
  }

  /**
   * Get elements
   * @return elements
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ELEMENTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Object getElements() {
    return elements;
  }


  @JsonProperty(JSON_PROPERTY_ELEMENTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setElements(@javax.annotation.Nullable Object elements) {
    this.elements = elements;
  }

  public TextNode doubleValue(@javax.annotation.Nullable Double doubleValue) {
    
    this.doubleValue = doubleValue;
    return this;
  }

  /**
   * Get doubleValue
   * @return doubleValue
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DOUBLE_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getDoubleValue() {
    return doubleValue;
  }


  @JsonProperty(JSON_PROPERTY_DOUBLE_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDoubleValue(@javax.annotation.Nullable Double doubleValue) {
    this.doubleValue = doubleValue;
  }

  public TextNode longValue(@javax.annotation.Nullable Long longValue) {
    
    this.longValue = longValue;
    return this;
  }

  /**
   * Get longValue
   * @return longValue
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LONG_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getLongValue() {
    return longValue;
  }


  @JsonProperty(JSON_PROPERTY_LONG_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLongValue(@javax.annotation.Nullable Long longValue) {
    this.longValue = longValue;
  }

  public TextNode booleanValue(@javax.annotation.Nullable Boolean booleanValue) {
    
    this.booleanValue = booleanValue;
    return this;
  }

  /**
   * Get booleanValue
   * @return booleanValue
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_BOOLEAN_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getBooleanValue() {
    return booleanValue;
  }


  @JsonProperty(JSON_PROPERTY_BOOLEAN_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBooleanValue(@javax.annotation.Nullable Boolean booleanValue) {
    this.booleanValue = booleanValue;
  }

  public TextNode number(@javax.annotation.Nullable Boolean number) {
    
    this.number = number;
    return this;
  }

  /**
   * Get number
   * @return number
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getNumber() {
    return number;
  }


  @JsonProperty(JSON_PROPERTY_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNumber(@javax.annotation.Nullable Boolean number) {
    this.number = number;
  }

  public TextNode _int(@javax.annotation.Nullable Boolean _int) {
    
    this._int = _int;
    return this;
  }

  /**
   * Get _int
   * @return _int
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_INT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getInt() {
    return _int;
  }


  @JsonProperty(JSON_PROPERTY_INT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setInt(@javax.annotation.Nullable Boolean _int) {
    this._int = _int;
  }

  public TextNode intValue(@javax.annotation.Nullable Integer intValue) {
    
    this.intValue = intValue;
    return this;
  }

  /**
   * Get intValue
   * @return intValue
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_INT_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getIntValue() {
    return intValue;
  }


  @JsonProperty(JSON_PROPERTY_INT_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIntValue(@javax.annotation.Nullable Integer intValue) {
    this.intValue = intValue;
  }

  public TextNode floatingPointNumber(@javax.annotation.Nullable Boolean floatingPointNumber) {
    
    this.floatingPointNumber = floatingPointNumber;
    return this;
  }

  /**
   * Get floatingPointNumber
   * @return floatingPointNumber
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FLOATING_POINT_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getFloatingPointNumber() {
    return floatingPointNumber;
  }


  @JsonProperty(JSON_PROPERTY_FLOATING_POINT_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFloatingPointNumber(@javax.annotation.Nullable Boolean floatingPointNumber) {
    this.floatingPointNumber = floatingPointNumber;
  }

  public TextNode containerNode(@javax.annotation.Nullable Boolean containerNode) {
    
    this.containerNode = containerNode;
    return this;
  }

  /**
   * Get containerNode
   * @return containerNode
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CONTAINER_NODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getContainerNode() {
    return containerNode;
  }


  @JsonProperty(JSON_PROPERTY_CONTAINER_NODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setContainerNode(@javax.annotation.Nullable Boolean containerNode) {
    this.containerNode = containerNode;
  }

  public TextNode missingNode(@javax.annotation.Nullable Boolean missingNode) {
    
    this.missingNode = missingNode;
    return this;
  }

  /**
   * Get missingNode
   * @return missingNode
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MISSING_NODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getMissingNode() {
    return missingNode;
  }


  @JsonProperty(JSON_PROPERTY_MISSING_NODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMissingNode(@javax.annotation.Nullable Boolean missingNode) {
    this.missingNode = missingNode;
  }

  public TextNode _object(@javax.annotation.Nullable Boolean _object) {
    
    this._object = _object;
    return this;
  }

  /**
   * Get _object
   * @return _object
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_OBJECT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getObject() {
    return _object;
  }


  @JsonProperty(JSON_PROPERTY_OBJECT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setObject(@javax.annotation.Nullable Boolean _object) {
    this._object = _object;
  }

  public TextNode _long(@javax.annotation.Nullable Boolean _long) {
    
    this._long = _long;
    return this;
  }

  /**
   * Get _long
   * @return _long
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LONG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getLong() {
    return _long;
  }


  @JsonProperty(JSON_PROPERTY_LONG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLong(@javax.annotation.Nullable Boolean _long) {
    this._long = _long;
  }

  public TextNode pojo(@javax.annotation.Nullable Boolean pojo) {
    
    this.pojo = pojo;
    return this;
  }

  /**
   * Get pojo
   * @return pojo
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_POJO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getPojo() {
    return pojo;
  }


  @JsonProperty(JSON_PROPERTY_POJO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPojo(@javax.annotation.Nullable Boolean pojo) {
    this.pojo = pojo;
  }

  public TextNode bigDecimal(@javax.annotation.Nullable Boolean bigDecimal) {
    
    this.bigDecimal = bigDecimal;
    return this;
  }

  /**
   * Get bigDecimal
   * @return bigDecimal
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_BIG_DECIMAL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getBigDecimal() {
    return bigDecimal;
  }


  @JsonProperty(JSON_PROPERTY_BIG_DECIMAL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBigDecimal(@javax.annotation.Nullable Boolean bigDecimal) {
    this.bigDecimal = bigDecimal;
  }

  public TextNode bigInteger(@javax.annotation.Nullable Boolean bigInteger) {
    
    this.bigInteger = bigInteger;
    return this;
  }

  /**
   * Get bigInteger
   * @return bigInteger
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_BIG_INTEGER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getBigInteger() {
    return bigInteger;
  }


  @JsonProperty(JSON_PROPERTY_BIG_INTEGER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBigInteger(@javax.annotation.Nullable Boolean bigInteger) {
    this.bigInteger = bigInteger;
  }

  public TextNode _boolean(@javax.annotation.Nullable Boolean _boolean) {
    
    this._boolean = _boolean;
    return this;
  }

  /**
   * Get _boolean
   * @return _boolean
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_BOOLEAN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getBoolean() {
    return _boolean;
  }


  @JsonProperty(JSON_PROPERTY_BOOLEAN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBoolean(@javax.annotation.Nullable Boolean _boolean) {
    this._boolean = _boolean;
  }

  public TextNode _double(@javax.annotation.Nullable Boolean _double) {
    
    this._double = _double;
    return this;
  }

  /**
   * Get _double
   * @return _double
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DOUBLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getDouble() {
    return _double;
  }


  @JsonProperty(JSON_PROPERTY_DOUBLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDouble(@javax.annotation.Nullable Boolean _double) {
    this._double = _double;
  }

  public TextNode binary(@javax.annotation.Nullable Boolean binary) {
    
    this.binary = binary;
    return this;
  }

  /**
   * Get binary
   * @return binary
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_BINARY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getBinary() {
    return binary;
  }


  @JsonProperty(JSON_PROPERTY_BINARY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBinary(@javax.annotation.Nullable Boolean binary) {
    this.binary = binary;
  }

  public TextNode integralNumber(@javax.annotation.Nullable Boolean integralNumber) {
    
    this.integralNumber = integralNumber;
    return this;
  }

  /**
   * Get integralNumber
   * @return integralNumber
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_INTEGRAL_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getIntegralNumber() {
    return integralNumber;
  }


  @JsonProperty(JSON_PROPERTY_INTEGRAL_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIntegralNumber(@javax.annotation.Nullable Boolean integralNumber) {
    this.integralNumber = integralNumber;
  }

  public TextNode bigIntegerValue(@javax.annotation.Nullable Integer bigIntegerValue) {
    
    this.bigIntegerValue = bigIntegerValue;
    return this;
  }

  /**
   * Get bigIntegerValue
   * @return bigIntegerValue
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_BIG_INTEGER_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getBigIntegerValue() {
    return bigIntegerValue;
  }


  @JsonProperty(JSON_PROPERTY_BIG_INTEGER_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBigIntegerValue(@javax.annotation.Nullable Integer bigIntegerValue) {
    this.bigIntegerValue = bigIntegerValue;
  }

  public TextNode decimalValue(@javax.annotation.Nullable BigDecimal decimalValue) {
    
    this.decimalValue = decimalValue;
    return this;
  }

  /**
   * Get decimalValue
   * @return decimalValue
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DECIMAL_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getDecimalValue() {
    return decimalValue;
  }


  @JsonProperty(JSON_PROPERTY_DECIMAL_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDecimalValue(@javax.annotation.Nullable BigDecimal decimalValue) {
    this.decimalValue = decimalValue;
  }

  public TextNode valueAsBoolean(@javax.annotation.Nullable Boolean valueAsBoolean) {
    
    this.valueAsBoolean = valueAsBoolean;
    return this;
  }

  /**
   * Get valueAsBoolean
   * @return valueAsBoolean
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VALUE_AS_BOOLEAN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getValueAsBoolean() {
    return valueAsBoolean;
  }


  @JsonProperty(JSON_PROPERTY_VALUE_AS_BOOLEAN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setValueAsBoolean(@javax.annotation.Nullable Boolean valueAsBoolean) {
    this.valueAsBoolean = valueAsBoolean;
  }

  public TextNode numberValue(@javax.annotation.Nullable BigDecimal numberValue) {
    
    this.numberValue = numberValue;
    return this;
  }

  /**
   * Get numberValue
   * @return numberValue
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NUMBER_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getNumberValue() {
    return numberValue;
  }


  @JsonProperty(JSON_PROPERTY_NUMBER_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNumberValue(@javax.annotation.Nullable BigDecimal numberValue) {
    this.numberValue = numberValue;
  }

  public TextNode valueAsInt(@javax.annotation.Nullable Integer valueAsInt) {
    
    this.valueAsInt = valueAsInt;
    return this;
  }

  /**
   * Get valueAsInt
   * @return valueAsInt
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VALUE_AS_INT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getValueAsInt() {
    return valueAsInt;
  }


  @JsonProperty(JSON_PROPERTY_VALUE_AS_INT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setValueAsInt(@javax.annotation.Nullable Integer valueAsInt) {
    this.valueAsInt = valueAsInt;
  }

  public TextNode valueAsLong(@javax.annotation.Nullable Long valueAsLong) {
    
    this.valueAsLong = valueAsLong;
    return this;
  }

  /**
   * Get valueAsLong
   * @return valueAsLong
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VALUE_AS_LONG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getValueAsLong() {
    return valueAsLong;
  }


  @JsonProperty(JSON_PROPERTY_VALUE_AS_LONG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setValueAsLong(@javax.annotation.Nullable Long valueAsLong) {
    this.valueAsLong = valueAsLong;
  }

  public TextNode valueAsDouble(@javax.annotation.Nullable Double valueAsDouble) {
    
    this.valueAsDouble = valueAsDouble;
    return this;
  }

  /**
   * Get valueAsDouble
   * @return valueAsDouble
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VALUE_AS_DOUBLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getValueAsDouble() {
    return valueAsDouble;
  }


  @JsonProperty(JSON_PROPERTY_VALUE_AS_DOUBLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setValueAsDouble(@javax.annotation.Nullable Double valueAsDouble) {
    this.valueAsDouble = valueAsDouble;
  }

  public TextNode valueAsText(@javax.annotation.Nullable String valueAsText) {
    
    this.valueAsText = valueAsText;
    return this;
  }

  /**
   * Get valueAsText
   * @return valueAsText
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VALUE_AS_TEXT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getValueAsText() {
    return valueAsText;
  }


  @JsonProperty(JSON_PROPERTY_VALUE_AS_TEXT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setValueAsText(@javax.annotation.Nullable String valueAsText) {
    this.valueAsText = valueAsText;
  }

  public TextNode fieldNames(@javax.annotation.Nullable Object fieldNames) {
    
    this.fieldNames = fieldNames;
    return this;
  }

  /**
   * Get fieldNames
   * @return fieldNames
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FIELD_NAMES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Object getFieldNames() {
    return fieldNames;
  }


  @JsonProperty(JSON_PROPERTY_FIELD_NAMES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFieldNames(@javax.annotation.Nullable Object fieldNames) {
    this.fieldNames = fieldNames;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TextNode textNode = (TextNode) o;
    return Objects.equals(this.textual, textNode.textual) &&
        Objects.equals(this.binaryValue, textNode.binaryValue) &&
        Objects.equals(this.textValue, textNode.textValue) &&
        Objects.equals(this.valueNode, textNode.valueNode) &&
        Objects.equals(this.numberType, textNode.numberType) &&
        Objects.equals(this.array, textNode.array) &&
        Objects.equals(this.fields, textNode.fields) &&
        Objects.equals(this._null, textNode._null) &&
        Objects.equals(this.elements, textNode.elements) &&
        Objects.equals(this.doubleValue, textNode.doubleValue) &&
        Objects.equals(this.longValue, textNode.longValue) &&
        Objects.equals(this.booleanValue, textNode.booleanValue) &&
        Objects.equals(this.number, textNode.number) &&
        Objects.equals(this._int, textNode._int) &&
        Objects.equals(this.intValue, textNode.intValue) &&
        Objects.equals(this.floatingPointNumber, textNode.floatingPointNumber) &&
        Objects.equals(this.containerNode, textNode.containerNode) &&
        Objects.equals(this.missingNode, textNode.missingNode) &&
        Objects.equals(this._object, textNode._object) &&
        Objects.equals(this._long, textNode._long) &&
        Objects.equals(this.pojo, textNode.pojo) &&
        Objects.equals(this.bigDecimal, textNode.bigDecimal) &&
        Objects.equals(this.bigInteger, textNode.bigInteger) &&
        Objects.equals(this._boolean, textNode._boolean) &&
        Objects.equals(this._double, textNode._double) &&
        Objects.equals(this.binary, textNode.binary) &&
        Objects.equals(this.integralNumber, textNode.integralNumber) &&
        Objects.equals(this.bigIntegerValue, textNode.bigIntegerValue) &&
        Objects.equals(this.decimalValue, textNode.decimalValue) &&
        Objects.equals(this.valueAsBoolean, textNode.valueAsBoolean) &&
        Objects.equals(this.numberValue, textNode.numberValue) &&
        Objects.equals(this.valueAsInt, textNode.valueAsInt) &&
        Objects.equals(this.valueAsLong, textNode.valueAsLong) &&
        Objects.equals(this.valueAsDouble, textNode.valueAsDouble) &&
        Objects.equals(this.valueAsText, textNode.valueAsText) &&
        Objects.equals(this.fieldNames, textNode.fieldNames);
  }

  @Override
  public int hashCode() {
    return Objects.hash(textual, binaryValue, textValue, valueNode, numberType, array, fields, _null, elements, doubleValue, longValue, booleanValue, number, _int, intValue, floatingPointNumber, containerNode, missingNode, _object, _long, pojo, bigDecimal, bigInteger, _boolean, _double, binary, integralNumber, bigIntegerValue, decimalValue, valueAsBoolean, numberValue, valueAsInt, valueAsLong, valueAsDouble, valueAsText, fieldNames);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TextNode {\n");
    sb.append("    textual: ").append(toIndentedString(textual)).append("\n");
    sb.append("    binaryValue: ").append(toIndentedString(binaryValue)).append("\n");
    sb.append("    textValue: ").append(toIndentedString(textValue)).append("\n");
    sb.append("    valueNode: ").append(toIndentedString(valueNode)).append("\n");
    sb.append("    numberType: ").append(toIndentedString(numberType)).append("\n");
    sb.append("    array: ").append(toIndentedString(array)).append("\n");
    sb.append("    fields: ").append(toIndentedString(fields)).append("\n");
    sb.append("    _null: ").append(toIndentedString(_null)).append("\n");
    sb.append("    elements: ").append(toIndentedString(elements)).append("\n");
    sb.append("    doubleValue: ").append(toIndentedString(doubleValue)).append("\n");
    sb.append("    longValue: ").append(toIndentedString(longValue)).append("\n");
    sb.append("    booleanValue: ").append(toIndentedString(booleanValue)).append("\n");
    sb.append("    number: ").append(toIndentedString(number)).append("\n");
    sb.append("    _int: ").append(toIndentedString(_int)).append("\n");
    sb.append("    intValue: ").append(toIndentedString(intValue)).append("\n");
    sb.append("    floatingPointNumber: ").append(toIndentedString(floatingPointNumber)).append("\n");
    sb.append("    containerNode: ").append(toIndentedString(containerNode)).append("\n");
    sb.append("    missingNode: ").append(toIndentedString(missingNode)).append("\n");
    sb.append("    _object: ").append(toIndentedString(_object)).append("\n");
    sb.append("    _long: ").append(toIndentedString(_long)).append("\n");
    sb.append("    pojo: ").append(toIndentedString(pojo)).append("\n");
    sb.append("    bigDecimal: ").append(toIndentedString(bigDecimal)).append("\n");
    sb.append("    bigInteger: ").append(toIndentedString(bigInteger)).append("\n");
    sb.append("    _boolean: ").append(toIndentedString(_boolean)).append("\n");
    sb.append("    _double: ").append(toIndentedString(_double)).append("\n");
    sb.append("    binary: ").append(toIndentedString(binary)).append("\n");
    sb.append("    integralNumber: ").append(toIndentedString(integralNumber)).append("\n");
    sb.append("    bigIntegerValue: ").append(toIndentedString(bigIntegerValue)).append("\n");
    sb.append("    decimalValue: ").append(toIndentedString(decimalValue)).append("\n");
    sb.append("    valueAsBoolean: ").append(toIndentedString(valueAsBoolean)).append("\n");
    sb.append("    numberValue: ").append(toIndentedString(numberValue)).append("\n");
    sb.append("    valueAsInt: ").append(toIndentedString(valueAsInt)).append("\n");
    sb.append("    valueAsLong: ").append(toIndentedString(valueAsLong)).append("\n");
    sb.append("    valueAsDouble: ").append(toIndentedString(valueAsDouble)).append("\n");
    sb.append("    valueAsText: ").append(toIndentedString(valueAsText)).append("\n");
    sb.append("    fieldNames: ").append(toIndentedString(fieldNames)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

