/*
 * API Interna de PortaFIB que ofereix serveis de firma web immediada.
 * Conjunt de Serveis REST de PortaFIB per atendre peticions de firma a través de web de forma immediata.
 *
 * The version of the OpenAPI document: 1.0-SNAPSHOT
 * Contact: otae@fundaciobit.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package es.caib.portafib.apiinterna.client.signature.v1.api;

import es.caib.portafib.apiinterna.client.signature.v1.services.ApiException;
import es.caib.portafib.apiinterna.client.signature.v1.model.RestExceptionInfo;
import es.caib.portafib.apiinterna.client.signature.v1.model.ValidateSignatureRequest;
import es.caib.portafib.apiinterna.client.signature.v1.model.ValidateSignatureResponse;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SignatureValidationV1Api
 */
class SignatureValidationV1ApiTest {

    private final SignatureValidationV1Api api = new SignatureValidationV1Api();

    /**
     * Operacio de firma simple en servidor d&#39;un document
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    void validateSignatureTest() throws ApiException {
        //
        //String languageUI = null;
        //
        //ValidateSignatureRequest validateSignatureRequest = null;
        //
        //ValidateSignatureResponse response = api.validateSignature(languageUI, validateSignatureRequest);

        // TODO: test validations
    }
}
