<%@   taglib prefix="spring" uri="http://www.springframework.org/tags" 
%><%@ taglib prefix="form"   uri="http://www.springframework.org/tags/form" 
%><%@ taglib prefix="c"      uri="http://java.sun.com/jsp/jstl/core" 
%><%@ taglib prefix="fmt"    uri="http://java.sun.com/jsp/jstl/fmt" 
%><%@ taglib prefix="fn"     uri="http://java.sun.com/jsp/jstl/functions" 
%><%@ taglib prefix="pfi"    uri="/WEB-INF/jstl/portafib.tld"
%><%@ taglib prefix="gen"    uri="/WEB-INF/jstl/genapp.tld"
%><%@ taglib prefix="tiles"  uri="http://tiles.apache.org/tags-tiles" 
%><%@ taglib  prefix="un" uri="http://jakarta.apache.org/taglibs/unstandard-1.0"
%><%@ taglib prefix="sec" uri="http://www.springframework.org/security/tags"
%><%@ page errorPage="/error.jsp" trimDirectiveWhitespaces="true"%><%--  page errorPage="/WEB-INF/jsp/error.jsp"  --%>