/*
 * API REST INTERNA de PortaFIB
 * Conjunt de Serveis REST de PortaFIB per ser accedits des de l'interior
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: otae@fundaciobit.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package es.caib.portafib.apiinterna.client.api;

import es.caib.portafib.apiinterna.client.services.ApiException;
import es.caib.portafib.apiinterna.client.model.InfoVersion;
import es.caib.portafib.apiinterna.client.model.RestExceptionInfo;
import org.junit.Test;
import org.junit.Ignore;
import org.junit.Assert;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for InfoVersionApi
 */
public class InfoVersionApiTest {

    private final InfoVersionApi api = new InfoVersionApi();

    /**
     * Retorna la versió de PortaFIB REST
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void versionApiTest() throws ApiException {
        //
        //InfoVersion response = api.versionApi();

        // TODO: test validations
    }
    /**
     * Retorna la versió de PortaFIB
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void versionAppTest() throws ApiException {
        //
        //InfoVersion response = api.versionApp();

        // TODO: test validations
    }
}
