/*
 * API Interna de PortaFIB de consulta de serveis d'utilitat
 * Conjunt de Serveis REST de PortaFIB per atendre consultes generiques de Portafib
 *
 * The version of the OpenAPI document: 1.0-SNAPSHOT
 * Contact: otae@fundaciobit.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package es.caib.portafib.apiinterna.client.firmaservidor.v1.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * FirmaSimpleValidationInfo
 */
@JsonPropertyOrder({
  FirmaSimpleValidationInfo.JSON_PROPERTY_CHECK_ADMINISTRATION_I_D_OF_SIGNER,
  FirmaSimpleValidationInfo.JSON_PROPERTY_CHECK_DOCUMENT_MODIFICATIONS,
  FirmaSimpleValidationInfo.JSON_PROPERTY_CHECK_VALIDATION_SIGNATURE,
  FirmaSimpleValidationInfo.JSON_PROPERTY_NO_CHECK_VALIDATION_REASON
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class FirmaSimpleValidationInfo {
  public static final String JSON_PROPERTY_CHECK_ADMINISTRATION_I_D_OF_SIGNER = "checkAdministrationIDOfSigner";
  private Boolean checkAdministrationIDOfSigner;

  public static final String JSON_PROPERTY_CHECK_DOCUMENT_MODIFICATIONS = "checkDocumentModifications";
  private Boolean checkDocumentModifications;

  public static final String JSON_PROPERTY_CHECK_VALIDATION_SIGNATURE = "checkValidationSignature";
  private Boolean checkValidationSignature;

  public static final String JSON_PROPERTY_NO_CHECK_VALIDATION_REASON = "noCheckValidationReason";
  private String noCheckValidationReason;

  public FirmaSimpleValidationInfo() {
  }

  public FirmaSimpleValidationInfo checkAdministrationIDOfSigner(Boolean checkAdministrationIDOfSigner) {
    
    this.checkAdministrationIDOfSigner = checkAdministrationIDOfSigner;
    return this;
  }

   /**
   * Get checkAdministrationIDOfSigner
   * @return checkAdministrationIDOfSigner
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CHECK_ADMINISTRATION_I_D_OF_SIGNER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getCheckAdministrationIDOfSigner() {
    return checkAdministrationIDOfSigner;
  }


  @JsonProperty(JSON_PROPERTY_CHECK_ADMINISTRATION_I_D_OF_SIGNER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCheckAdministrationIDOfSigner(Boolean checkAdministrationIDOfSigner) {
    this.checkAdministrationIDOfSigner = checkAdministrationIDOfSigner;
  }


  public FirmaSimpleValidationInfo checkDocumentModifications(Boolean checkDocumentModifications) {
    
    this.checkDocumentModifications = checkDocumentModifications;
    return this;
  }

   /**
   * Get checkDocumentModifications
   * @return checkDocumentModifications
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CHECK_DOCUMENT_MODIFICATIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getCheckDocumentModifications() {
    return checkDocumentModifications;
  }


  @JsonProperty(JSON_PROPERTY_CHECK_DOCUMENT_MODIFICATIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCheckDocumentModifications(Boolean checkDocumentModifications) {
    this.checkDocumentModifications = checkDocumentModifications;
  }


  public FirmaSimpleValidationInfo checkValidationSignature(Boolean checkValidationSignature) {
    
    this.checkValidationSignature = checkValidationSignature;
    return this;
  }

   /**
   * Get checkValidationSignature
   * @return checkValidationSignature
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CHECK_VALIDATION_SIGNATURE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getCheckValidationSignature() {
    return checkValidationSignature;
  }


  @JsonProperty(JSON_PROPERTY_CHECK_VALIDATION_SIGNATURE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCheckValidationSignature(Boolean checkValidationSignature) {
    this.checkValidationSignature = checkValidationSignature;
  }


  public FirmaSimpleValidationInfo noCheckValidationReason(String noCheckValidationReason) {
    
    this.noCheckValidationReason = noCheckValidationReason;
    return this;
  }

   /**
   * Get noCheckValidationReason
   * @return noCheckValidationReason
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NO_CHECK_VALIDATION_REASON)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getNoCheckValidationReason() {
    return noCheckValidationReason;
  }


  @JsonProperty(JSON_PROPERTY_NO_CHECK_VALIDATION_REASON)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNoCheckValidationReason(String noCheckValidationReason) {
    this.noCheckValidationReason = noCheckValidationReason;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FirmaSimpleValidationInfo firmaSimpleValidationInfo = (FirmaSimpleValidationInfo) o;
    return Objects.equals(this.checkAdministrationIDOfSigner, firmaSimpleValidationInfo.checkAdministrationIDOfSigner) &&
        Objects.equals(this.checkDocumentModifications, firmaSimpleValidationInfo.checkDocumentModifications) &&
        Objects.equals(this.checkValidationSignature, firmaSimpleValidationInfo.checkValidationSignature) &&
        Objects.equals(this.noCheckValidationReason, firmaSimpleValidationInfo.noCheckValidationReason);
  }

  @Override
  public int hashCode() {
    return Objects.hash(checkAdministrationIDOfSigner, checkDocumentModifications, checkValidationSignature, noCheckValidationReason);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FirmaSimpleValidationInfo {\n");
    sb.append("    checkAdministrationIDOfSigner: ").append(toIndentedString(checkAdministrationIDOfSigner)).append("\n");
    sb.append("    checkDocumentModifications: ").append(toIndentedString(checkDocumentModifications)).append("\n");
    sb.append("    checkValidationSignature: ").append(toIndentedString(checkValidationSignature)).append("\n");
    sb.append("    noCheckValidationReason: ").append(toIndentedString(noCheckValidationReason)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

