-- create index pfi_annex_pk_i on pfi_annex (annexid);
create index pfi_annex_fitxerid_fk_i on pfi_annex (fitxerid);
create index pfi_annexfirmat_fitxerid_fk_i on pfi_annexfirmat (fitxerid);
create index pfi_annexfirmat_firmaid_fk_i on pfi_annexfirmat (firmaid);
create index pfi_bitacola_enttipope_i on pfi_bitacola (entitatid, tipusoperacio);
create index pfi_bitacola_enttipobj_i on pfi_bitacola (tipusobjecte);
-- create index pfi_blocdefirmes_pk_i on pfi_blocdefirmes (blocdefirmesid);
-- create index pfi_codibarres_pk_i on pfi_codibarres (codibarresid);
create index pfi_colabdeleg_destid_fk_i on pfi_colaboraciodelegacio (destinatariid);
create index pfi_colabdeleg_fitautoid_fk_i on pfi_colaboraciodelegacio (fitxerautoritzacioid);
create index pfi_custodiainfo_pluginid_fk_i on pfi_custodiainfo (pluginid);
create index pfi_custodia_codibarid_fk_i on pfi_custodiainfo (codibarresid);
create index pfi_custodia_usrentid_fk_i on pfi_custodiainfo (usuarientitatid);
create index pfi_custodia_entitatid_fk_i on pfi_custodiainfo (entitatid);
create index pfi_entitat_faviconid_fk_i on pfi_entitat (faviconid);
create index pfi_entitat_logowebpeuid_fk_i on pfi_entitat (logowebpeuid);
create index pfi_entitat_pdfautoriid_fk_i on pfi_entitat (pdfautoritzaciodelegacioid);
create index pfi_entitat_motiudele_fk_i on pfi_entitat (motiudelegacioid);
create index pfi_entitat_algofirma_fk_i on pfi_entitat (algorismedefirmaid);
create index pfi_entitat_segelltemps_fk_i on pfi_entitat (pluginid);
create index pfi_entitat_pluginvalfir_fk_i on pfi_entitat (pluginvalidafirmesid);
-- create index pfi_estadistica_pk_i on pfi_estadistica (estadisticaid);
-- create index pfi_estatdefirma_pk_i on pfi_estatdefirma (estatdefirmaid);
create index pfi_estatfirma_usuenti_fk_i on pfi_estatdefirma (usuarientitatid, tipusestatdefirmainicialid, tipusestatdefirmafinalid);
-- create index pfi_firma_pk_i on pfi_firma (firmaid);
create index pfi_firma_blocdefirmaid_fk_i on pfi_firma (blocdefirmaid);
create index pfi_firma_estatfirmaid_fk_i on pfi_firma (tipusestatdefirmafinalid);
-- create index pfi_fluxdefirmes_pk_i on pfi_fluxdefirmes (fluxdefirmesid);
create index pfi_grupentitat_entitatid_fk_i on pfi_grupentitat (entitatid);
create index pfi_grupusrent_usrentid_fk_i on pfi_grupentitatusuarientitat (usuarientitatid);
-- create index pfi_metadada_pk_i on pfi_metadada (metadadaid);
create index pfi_metadada_tipusmetaid_fk_i on pfi_metadada (tipusmetadadaid);
create index pfi_mofitido_tipusdoc_fk_i on pfi_modulfirmapertipusdoc (tipusdocumentid);
create index pfi_notifica_peticioid_i on pfi_notificacio (peticiodefirmaid);
create index pfi_notificacio_datacreacio_i on pfi_notificacio (datacreacio);
create index pfi_notificacio_usrappid_i on pfi_notificacio (usuariaplicacioid);
create index pfi_perfilsua_perfilid_fk_i on pfi_perfilsperusrapp (usuariaplicacioperfilid);
create index pfi_permisgrpl_grupentid_fk_i on pfi_permisgrupplantilla (grupentitatid);
create index pfi_permisuspl_usrentid_fk_i on pfi_permisusuariplantilla (usuarientitatid);
create index pfi_petifirma_fitxerid_fk_i on pfi_peticiodefirma (fitxerafirmarid);
create index pfi_petifirma_fitxeadaid_fk_i on pfi_peticiodefirma (fitxeradaptatid);
create index pfi_petifirma_tipofirmid_fk_i on pfi_peticiodefirma (tipusfirmaid);
create index pfi_petifirma_estatid_fk_i on pfi_peticiodefirma (tipusestatpeticiodefirmaid);
create index pfi_petifirma_prioritatid_fk_i on pfi_peticiodefirma (prioritatid);
create index pfi_petifirma_usrappid_fk_i on pfi_peticiodefirma (usuariaplicacioid);
create index pfi_petifirma_custinfoid_fk_i on pfi_peticiodefirma (custodiainfoid);
create index pfi_petifirma_solipers2_fk_i on pfi_peticiodefirma (solicitantpersona2id);
create index pfi_petifirma_conffirma_fk_i on pfi_peticiodefirma (configuraciodefirmaid);
create index pfi_plantiflfi_usrentiid_fk_i on pfi_plantillafluxdefirmes (usuarientitatid);
-- create index pfi_plugin_pk_i on pfi_plugin (pluginid);
create index pfi_plugin_desccurtaid_fk_i on pfi_plugin (descripciocurtaid);
-- create index pfi_plugincridada_pk_i on pfi_plugincridada (plugincridadaid);
create index pfi_plugcrida_pluginid_fk_i on pfi_plugincridada (pluginid);
create index pfi_plugcrida_retorfitxer_fk_i on pfi_plugincridada (retornfitxerid);
create index pfi_pfwpua_usrappid_fk_i on pfi_pluginfirmawebperusrapp (usuariaplicacioid);
create index pfi_pfwpue_usrentid_fk_i on pfi_pluginfirmawebperusrent (usuarientitatid);
create index pfi_propietat_entitatid_fk_i on pfi_propietatglobal (entitatid);
create index pfi_rebreavis_usrentid_fk_i on pfi_rebreavis (usuarientitatid);
create index pfi_revdedest_destid_fk_i on pfi_revisordedestinatari (destinatariid);
create index pfi_revfirma_usrentitat_fk_i on pfi_revisordefirma (usuarientitatid);
-- create index pfi_role_pk_i on pfi_role (roleid);
create index pfi_roleusrent_roleid_fk_i on pfi_roleusuarientitat (roleid);
create index pfi_tipusdocument_nom_fk_i on pfi_tipusdocument (nom);
-- create index pfi_tipusdocumentcoladele_pk_i on pfi_tipusdocumentcoladele (id);
create index pfi_tipusdoccd_tipusdocid_fk_i on pfi_tipusdocumentcoladele (tipusdocumentid);
-- create index pfi_traduccio_pk_i on pfi_traduccio (traduccioid);
create index pfi_usrapp_entitatid_fk_i on pfi_usuariaplicacio (entitatid);
create index pfi_usrapp_logosegellid_fk_i on pfi_usuariaplicacio (logosegellid);
-- create index pfi_usuariaplicacioconfig_pk_i on pfi_usuariaplicacioconfig (usuariaplicacioconfigid);
create index pfi_confapp_tipusfirma_fk_i on pfi_usuariaplicacioconfig (tipusfirmaid);
create index pfi_confapp_motiudele_fk_i on pfi_usuariaplicacioconfig (motiudelegacioid);
create index pfi_confapp_plugsegell_fk_i on pfi_usuariaplicacioconfig (pluginsegellatid);
-- create index pfi_usuariaplicacioperfil_pk_i on pfi_usuariaplicacioperfil (usuariaplicacioperfilid);
create index pfi_perfilapp_appconf2id_fk_i on pfi_usuariaplicacioperfil (usrappconfiguracio2id);
create index pfi_perfilapp_appconf4id_fk_i on pfi_usuariaplicacioperfil (usrappconfiguracio4id);
create index pfi_usrentitat_personaid_fk_i on pfi_usuarientitat (usuaripersonaid);
create index pfi_usrentitat_logosegid_fk_i on pfi_usuarientitat (logosegellid);
create index pfi_favorit_origenid_fk_i on pfi_usuarientitatfavorit (origenid);
create index pfi_usuaripersona_nif_i on pfi_usuaripersona (nif);
create index pfi_persona_rubricaid_fk_i on pfi_usuaripersona (rubricaid);
